Hydra: hydra::AddPdf< PDF1, PDF2, PDFs > Struct Template Reference
hydra::AddPdf< PDF1, PDF2, PDFs > Struct Template Reference
Build a pdf adding other pdfs.
Public Types
typedef detail::AddPdfBase< PDF1, PDF2, PDFs... >::type base_type
base class type
typedef void hydra_sum_pdf_tag
tag
typedef thrust::tuple< PDF1, PDF2, PDFs... > pdfs_tuple_type
type of the tuple of pdfs
Public Member Functions
AddPdf (PDF1 const &pdf1, PDF2 const &pdf2, PDFs const &...pdfs, std::array< Parameter *, npdfs >const &coef, GBool_t extend=kTrue)
Ctor for used to build AddPdf usable in extended likelihood fits.
AddPdf (PDF1 const &pdf1, PDF2 const &pdf2, PDFs const &...pdfs, std::array< Parameter *, npdfs-1 >const &coef)
Ctor for used to build AddPdf not-usable in extended likelihood fits.
__host__ __device__ AddPdf (AddPdf< PDF1, PDF2, PDFs... > const &other)
copy ctor.
__host__ __device__ const Parameter & GetCoeficient (size_t i) const
__host__ __device__ GReal_t GetCoefSum () const
__host__ __device__ const thrust::tuple< PDF1, PDF2, PDFs... > & GetPdFs () const
__host__ __device__ GBool_t IsExtended () const
__host__ __device__ GBool_t IsFractioned () const
template<typename T1 >
__host__ __device__ GReal_t operator() (T1 &&t)
template<typename T1 , typename T2 >
__host__ __device__ GReal_t operator() (T1 &&t, T2 &&cache)
template<typename T >
__host__ __device__ GReal_t operator() (T *x, T *p)
__host__ __device__ AddPdf< PDF1, PDF2, PDFs... > & operator= (AddPdf< PDF1, PDF2, PDFs... > const &other)
assignment operator.
__host__ void PrintRegisteredParameters ()
print all registered parameters
__host__ void SetParameters (const std::vector< double > &parameters)
Set the coefficients and parameters of all pdfs.
Static Public Attributes
static constexpr size_t npdfs = sizeof...(PDFs)+2
number of pdfs
Detailed Description
template<typename PDF1, typename PDF2, typename... PDFs>
struct hydra::AddPdf< PDF1, PDF2, PDFs >
Given N unnormalized pdfs \(F_i\) , this class define a object representing the sum
\[ F_t = \sum_i^N c_i \times F_i \]
The coefficients of the pdfs can represent fractions or yields. If the number of coefficients is equal to the number of pdfs, the coefficients are interpreted as yields. If the number of coefficients is \((N-1)\), the coefficients are interpreted as fractions defined in the interval [0,1]. The coefficient of the last term is calculated as \(c_N=1 -\sum_i^{(N-1)} c_i \).
Definition at line 76 of file AddPdf.h.
Member Typedef Documentation
template<typename PDF1, typename PDF2, typename... PDFs> typedef detail::AddPdfBase<PDF1,PDF2,PDFs...>::type hydra::AddPdf< PDF1, PDF2, PDFs >::base_type
Definition at line 84 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> typedef void hydra::AddPdf< PDF1, PDF2, PDFs >::hydra_sum_pdf_tag
Definition at line 79 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> typedef thrust::tuple<PDF1, PDF2, PDFs...> hydra::AddPdf< PDF1, PDF2, PDFs >::pdfs_tuple_type
Definition at line 88 of file AddPdf.h.
Constructor & Destructor Documentation
template<typename PDF1, typename PDF2, typename... PDFs> hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf (PDF1 const & pdf1, PDF2 const & pdf2, PDFs const &... pdfs, std::array< Parameter *, npdfs >const & coef, GBool_t extend = kTrue) inline
Parameters
pdf1 first pdf object,
pdf2 second pdf object,
pdfs remaining pdfs.
coef arrary of Parameters, each parameter correspond to a coefficient
extend build pdf to be used in extended fit. Default is true.
Each component pdf is normalized properly before evaluation each time SetParameters(const std::vector<double>& parameters) is called. The sum is normalized also.
Definition at line 102 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf (PDF1 const & pdf1, PDF2 const & pdf2, PDFs const &... pdfs, std::array< Parameter *, npdfs-1 >const & coef) inline
Parameters
pdf1 first pdf object,
pdf2 second pdf object,
pdfs remaining pdfs.
coef arrary of Parameters, each parameter correspond to a fractional coefficient
Each component pdf is normalized properly before evaluation each time SetParameters(const std::vector<double>& parameters) is called. The sum is normalized also.
Definition at line 128 of file AddPdf.h.
References HYDRA_ENDL, HYDRA_LOG, HYDRA_MSG, and hydra::WARNING.
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf (AddPdf< PDF1, PDF2, PDFs... > const & other) inline
Definition at line 159 of file AddPdf.h.
References hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoeficient().
Member Function Documentation
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ const Parameter& hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoeficient (size_t i) const inline
Definition at line 225 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf(), and hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoefSum () const inline
Definition at line 243 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ const thrust::tuple<PDF1,PDF2,PDFs...>& hydra::AddPdf< PDF1, PDF2, PDFs >::GetPdFs () const inline
Definition at line 237 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ GBool_t hydra::AddPdf< PDF1, PDF2, PDFs >::IsExtended () const inline
Definition at line 231 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ GBool_t hydra::AddPdf< PDF1, PDF2, PDFs >::IsFractioned () const inline
Definition at line 249 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> template<typename T1 > __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::operator() (T1 && t) inline
Definition at line 256 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> template<typename T1 , typename T2 > __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::operator() (T1 && t, T2 && cache) inline
Definition at line 272 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> template<typename T > __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::operator() (T * x, T * p) inline
Definition at line 288 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ AddPdf<PDF1, PDF2, PDFs...>& hydra::AddPdf< PDF1, PDF2, PDFs >::operator= (AddPdf< PDF1, PDF2, PDFs... > const & other) inline
Definition at line 175 of file AddPdf.h.
References hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoeficient(), hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoefSum(), hydra::AddPdf< PDF1, PDF2, PDFs >::GetPdFs(), and hydra::AddPdf< PDF1, PDF2, PDFs >::IsExtended().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ void hydra::AddPdf< PDF1, PDF2, PDFs >::PrintRegisteredParameters () inline
Definition at line 213 of file AddPdf.h.
References HYDRA_CALLER, HYDRA_ENDL, and HYDRA_MSG.
template<typename PDF1, typename PDF2, typename... PDFs> __host__ void hydra::AddPdf< PDF1, PDF2, PDFs >::SetParameters (const std::vector< double > & parameters) inline
This method sets the values of all coefficients and parameters of pdfs stored in the AddPdf object. User should ensure this method is called before the object evaluation.
Definition at line 194 of file AddPdf.h.
Member Data Documentation
template<typename PDF1, typename PDF2, typename... PDFs> constexpr size_t hydra::AddPdf< PDF1, PDF2, PDFs >::npdfs = sizeof...(PDFs)+2 static
Definition at line 86 of file AddPdf.h.
The documentation for this struct was generated from the following file:
AddPdf.h