Hydra: hydra::BaseFunctor< Functor, ReturnType, NPARAM > Struct Template Reference
hydra::BaseFunctor< Functor, ReturnType, NPARAM > Struct Template Reference
Public Types
typedef void hydra_functor_tag
typedef std::true_type is_functor
typedef ReturnType return_type
Public Member Functions
__host__ __device__ BaseFunctor ()
__host__ __device__ BaseFunctor (BaseFunctor< Functor, ReturnType, NPARAM > const &other)
__host__ __device__ ~BaseFunctor ()
__host__ __device__ int GetCacheIndex () const
__host__ __device__ Functor & GetFunctor ()
__host__ const Parameter * GetParameter (size_t i) const
__host__ Parameter * GetParameter (size_t i)
template<typename T >
__host__ __device__ thrust::detail::enable_if< detail::is_homogeneous< typename thrust::tuple_element< 0, typename std::remove_reference< T >::type >::type, typename std::remove_reference< T >::type >::value, return_type >::type interface (T &&x)
template<typename T >
__host__ __device__ thrust::detail::enable_if<!detail::is_homogeneous< typename thrust::tuple_element< 0, typename std::remove_reference< T >::type >::type, typename std::remove_reference< T >::type >::value, return_type >::type interface (T &&x)
__host__ __device__ bool IsCached () const
template<typename T >
__host__ __device__ return_type operator() (T *x, T *p=0)
template<typename T >
__host__ __device__ return_type operator() (T &&x)
template<typename T1 , typename T2 >
__host__ __device__ return_type operator() (T1 &&x, T2 &&cache)
__host__ __device__ BaseFunctor< Functor, ReturnType, NPARAM > & operator= (BaseFunctor< Functor, ReturnType, NPARAM > const &other)
void PrintRegisteredParameters ()
__host__ __device__ void RegistryParameters (std::initializer_list< Parameter * > var_list)
__host__ __device__ void SetCached (bool cached=true)
__host__ __device__ void SetCacheIndex (int index)
__host__ void SetParameters (const std::vector< double > &parameters)
Static Public Attributes
static const size_t parameter_count =NPARAM
Detailed Description
template<typename Functor, typename ReturnType, size_t NPARAM>
struct hydra::BaseFunctor< Functor, ReturnType, NPARAM >
Examples:
HydraRandomExample.cpp, and HydraRandomExample.cu.
Definition at line 252 of file Function.h.
Member Typedef Documentation
template<typename Functor, typename ReturnType, size_t NPARAM> typedef void hydra::BaseFunctor< Functor, ReturnType, NPARAM >::hydra_functor_tag
Definition at line 255 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> typedef std::true_type hydra::BaseFunctor< Functor, ReturnType, NPARAM >::is_functor
Definition at line 258 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> typedef ReturnType hydra::BaseFunctor< Functor, ReturnType, NPARAM >::return_type
Definition at line 257 of file Function.h.
Constructor & Destructor Documentation
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ hydra::BaseFunctor< Functor, ReturnType, NPARAM >::BaseFunctor () inline
Definition at line 262 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ hydra::BaseFunctor< Functor, ReturnType, NPARAM >::BaseFunctor (BaseFunctor< Functor, ReturnType, NPARAM > const & other) inline
Definition at line 270 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ hydra::BaseFunctor< Functor, ReturnType, NPARAM >::~BaseFunctor () inline
Definition at line 294 of file Function.h.
Member Function Documentation
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ int hydra::BaseFunctor< Functor, ReturnType, NPARAM >::GetCacheIndex () const inline
Definition at line 301 of file Function.h.
Referenced by hydra::BaseFunctor< LambdaWrapper< ReturnType(ArgType), L >, ReturnType, 0 >::operator=().
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ Functor& hydra::BaseFunctor< Functor, ReturnType, NPARAM >::GetFunctor () inline
Definition at line 298 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ const Parameter* hydra::BaseFunctor< Functor, ReturnType, NPARAM >::GetParameter (size_t i) const inline
Definition at line 374 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ Parameter* hydra::BaseFunctor< Functor, ReturnType, NPARAM >::GetParameter (size_t i) inline
Definition at line 380 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> template<typename T > __host__ __device__ thrust::detail::enable_if< detail::is_homogeneous< typename thrust::tuple_element<0, typename std::remove_reference<T>::type>::type, typename std::remove_reference<T>::type>::value, return_type>::type hydra::BaseFunctor< Functor, ReturnType, NPARAM >::interface (T && x) inline
Definition at line 390 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> template<typename T > __host__ __device__ thrust::detail::enable_if<!detail::is_homogeneous< typename thrust::tuple_element<0, typename std::remove_reference<T>::type>::type, typename std::remove_reference<T>::type>::value, return_type>::type hydra::BaseFunctor< Functor, ReturnType, NPARAM >::interface (T && x) inline
Definition at line 409 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ bool hydra::BaseFunctor< Functor, ReturnType, NPARAM >::IsCached () const inline
Definition at line 307 of file Function.h.
Referenced by hydra::BaseFunctor< LambdaWrapper< ReturnType(ArgType), L >, ReturnType, 0 >::operator=().
template<typename Functor, typename ReturnType, size_t NPARAM> template<typename T > __host__ __device__ return_type hydra::BaseFunctor< Functor, ReturnType, NPARAM >::operator() (T * x, T * p = 0) inline
Definition at line 421 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> template<typename T > __host__ __device__ return_type hydra::BaseFunctor< Functor, ReturnType, NPARAM >::operator() (T && x) inline
Definition at line 427 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> template<typename T1 , typename T2 > __host__ __device__ return_type hydra::BaseFunctor< Functor, ReturnType, NPARAM >::operator() (T1 && x, T2 && cache) inline
Definition at line 433 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ BaseFunctor<Functor,ReturnType, NPARAM>& hydra::BaseFunctor< Functor, ReturnType, NPARAM >::operator= (BaseFunctor< Functor, ReturnType, NPARAM > const & other) inline
Definition at line 279 of file Function.h.
Referenced by examples::Exp::operator=(), and examples::Gauss< N >::operator=().
template<typename Functor, typename ReturnType, size_t NPARAM> void hydra::BaseFunctor< Functor, ReturnType, NPARAM >::PrintRegisteredParameters () inline
Definition at line 331 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ void hydra::BaseFunctor< Functor, ReturnType, NPARAM >::RegistryParameters (std::initializer_list< Parameter * > var_list) inline
Definition at line 315 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ void hydra::BaseFunctor< Functor, ReturnType, NPARAM >::SetCached (bool cached = true) inline
Definition at line 311 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ __device__ void hydra::BaseFunctor< Functor, ReturnType, NPARAM >::SetCacheIndex (int index) inline
Definition at line 304 of file Function.h.
template<typename Functor, typename ReturnType, size_t NPARAM> __host__ void hydra::BaseFunctor< Functor, ReturnType, NPARAM >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 349 of file Function.h.
Member Data Documentation
template<typename Functor, typename ReturnType, size_t NPARAM> const size_t hydra::BaseFunctor< Functor, ReturnType, NPARAM >::parameter_count =NPARAM static
Definition at line 259 of file Function.h.
Referenced by hydra::BaseFunctor< LambdaWrapper< ReturnType(ArgType), L >, ReturnType, 0 >::PrintRegisteredParameters(), and hydra::BaseFunctor< LambdaWrapper< ReturnType(ArgType), L >, ReturnType, 0 >::SetParameters().
The documentation for this struct was generated from the following file:
Function.h