Hydra: hydra::Divide< F1, F2 > Struct Template Reference
hydra::Divide< F1, F2 > Struct Template Reference
Public Types
typedef void hydra_functor_tag
typedef std::true_type is_functor
typedef detail::divide_result< typename F1::return_type, typename F2::return_type >::type return_type
typedef thrust::tuple< F1, F2 > functors_type
Public Member Functions
__host__ Divide ()
__host__ Divide (F1 const &f1, F2 const &f2)
__host__ __device__ Divide (Divide< F1, F2 > const &other)
__host__ __device__ Divide< F1, F2 > & operator= (Divide< F1, F2 > const &other)
__host__ void SetParameters (const std::vector< double > &parameters)
__host__ void PrintRegisteredParameters ()
__host__ __device__ functors_type GetFunctors () const
__host__ __device__ int GetIndex () const
__host__ __device__ void SetIndex (int index)
__host__ __device__ bool IsCached () const
__host__ __device__ void SetCached (bool cached=true)
template<typename T1 >
__host__ __device__ return_type operator() (T1 &t)
template<typename T1 , typename T2 >
__host__ __device__ return_type operator() (T1 &t, T2 &cache)
Detailed Description
template<typename F1, typename F2>
struct hydra::Divide< F1, F2 >
Definition at line 45 of file Divide.h.
Member Typedef Documentation
template<typename F1, typename F2> typedef thrust::tuple<F1, F2> hydra::Divide< F1, F2 >::functors_type
Definition at line 51 of file Divide.h.
template<typename F1, typename F2> typedef void hydra::Divide< F1, F2 >::hydra_functor_tag
Definition at line 48 of file Divide.h.
template<typename F1, typename F2> typedef std::true_type hydra::Divide< F1, F2 >::is_functor
Definition at line 49 of file Divide.h.
template<typename F1, typename F2> typedef detail::divide_result<typename F1::return_type, typename F2::return_type>::type hydra::Divide< F1, F2 >::return_type
Definition at line 50 of file Divide.h.
Constructor & Destructor Documentation
template<typename F1, typename F2> __host__ hydra::Divide< F1, F2 >::Divide () inline
Definition at line 54 of file Divide.h.
template<typename F1, typename F2> __host__ hydra::Divide< F1, F2 >::Divide (F1 const & f1, F2 const & f2) inline
Definition at line 60 of file Divide.h.
template<typename F1, typename F2> __host__ __device__ hydra::Divide< F1, F2 >::Divide (Divide< F1, F2 > const & other) inline
Definition at line 67 of file Divide.h.
Member Function Documentation
template<typename F1, typename F2> __host__ __device__ functors_type hydra::Divide< F1, F2 >::GetFunctors () const inline
Definition at line 101 of file Divide.h.
Referenced by hydra::Divide< F1, F2 >::operator=().
template<typename F1, typename F2> __host__ __device__ int hydra::Divide< F1, F2 >::GetIndex () const inline
Definition at line 104 of file Divide.h.
Referenced by hydra::Divide< F1, F2 >::operator=().
template<typename F1, typename F2> __host__ __device__ bool hydra::Divide< F1, F2 >::IsCached () const inline
Definition at line 110 of file Divide.h.
Referenced by hydra::Divide< F1, F2 >::operator=().
template<typename F1, typename F2> template<typename T1 > __host__ __device__ return_type hydra::Divide< F1, F2 >::operator() (T1 & t) inline
Definition at line 120 of file Divide.h.
template<typename F1, typename F2> template<typename T1 , typename T2 > __host__ __device__ return_type hydra::Divide< F1, F2 >::operator() (T1 & t, T2 & cache) inline
Definition at line 127 of file Divide.h.
template<typename F1, typename F2> __host__ __device__ Divide<F1,F2>& hydra::Divide< F1, F2 >::operator= (Divide< F1, F2 > const & other) inline
Definition at line 74 of file Divide.h.
References hydra::Divide< F1, F2 >::GetFunctors(), hydra::Divide< F1, F2 >::GetIndex(), and hydra::Divide< F1, F2 >::IsCached().
template<typename F1, typename F2> __host__ void hydra::Divide< F1, F2 >::PrintRegisteredParameters () inline
Definition at line 91 of file Divide.h.
References HYDRA_CALLER, HYDRA_ENDL, and HYDRA_MSG.
template<typename F1, typename F2> __host__ __device__ void hydra::Divide< F1, F2 >::SetCached (bool cached = true) inline
Definition at line 114 of file Divide.h.
template<typename F1, typename F2> __host__ __device__ void hydra::Divide< F1, F2 >::SetIndex (int index) inline
Definition at line 107 of file Divide.h.
template<typename F1, typename F2> __host__ void hydra::Divide< F1, F2 >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 85 of file Divide.h.
The documentation for this struct was generated from the following file:
Divide.h