Hydra: hydra::DecayMothers< N, BACKEND, GRND > Struct Template Reference
hydra::DecayMothers< N, BACKEND, GRND > Struct Template Reference
Public Types
typedef detail::BackendTraits< BACKEND > system_t
typedef system_t::template container< GReal_t > vector_real
Public Member Functions
DecayMothers (vector_real const &_masses, const GInt_t _ndaughters, const GInt_t _seed)
__host__ __device__ GReal_t pdk (const GReal_t a, const GReal_t b, const GReal_t c) const
__host__ __device__ void bbsort (GReal_t *array, GInt_t n)
__host__ __device__ size_t hash (size_t a, size_t b)
__host__ __device__ GReal_t process (const GInt_t evt, Vector4R **particles)
template<typename Tuple >
__host__ __device__ GReal_t operator() (const GInt_t evt, Tuple &particles)
Public Attributes
const GInt_t fSeed
const GInt_t fNDaughters
const GReal_t *__restrict__ fMasses
Detailed Description
template<size_t N, unsigned int BACKEND, typename GRND>
struct hydra::DecayMothers< N, BACKEND, GRND >
Definition at line 54 of file DecayMothers.h.
Member Typedef Documentation
template<size_t N, unsigned int BACKEND, typename GRND> typedef detail::BackendTraits<BACKEND> hydra::DecayMothers< N, BACKEND, GRND >::system_t
Definition at line 56 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> typedef system_t::template container<GReal_t> hydra::DecayMothers< N, BACKEND, GRND >::vector_real
Definition at line 57 of file DecayMothers.h.
Constructor & Destructor Documentation
template<size_t N, unsigned int BACKEND, typename GRND> hydra::DecayMothers< N, BACKEND, GRND >::DecayMothers (vector_real const & _masses, const GInt_t _ndaughters, const GInt_t _seed) inline
Definition at line 64 of file DecayMothers.h.
Member Function Documentation
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ void hydra::DecayMothers< N, BACKEND, GRND >::bbsort (GReal_t * array, GInt_t n) inline
Definition at line 81 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ size_t hydra::DecayMothers< N, BACKEND, GRND >::hash (size_t a, size_t b) inline
Definition at line 105 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> template<typename Tuple > __host__ __device__ GReal_t hydra::DecayMothers< N, BACKEND, GRND >::operator() (const GInt_t evt, Tuple & particles) inline
Definition at line 264 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ GReal_t hydra::DecayMothers< N, BACKEND, GRND >::pdk (const GReal_t a, const GReal_t b, const GReal_t c) const inline
Definition at line 72 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ GReal_t hydra::DecayMothers< N, BACKEND, GRND >::process (const GInt_t evt, Vector4R ** particles) inline
Definition at line 116 of file DecayMothers.h.
References hydra::Vector4R::applyBoostTo(), hydra::Vector4R::d3mag(), hydra::Vector4R::get(), kMAXP, hydra::Vector4R::mass(), PI, hydra::Vector4R::set(), and hydra::sum().
Member Data Documentation
template<size_t N, unsigned int BACKEND, typename GRND> const GReal_t* __restrict__ hydra::DecayMothers< N, BACKEND, GRND >::fMasses
Definition at line 61 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> const GInt_t hydra::DecayMothers< N, BACKEND, GRND >::fNDaughters
Definition at line 60 of file DecayMothers.h.
template<size_t N, unsigned int BACKEND, typename GRND> const GInt_t hydra::DecayMothers< N, BACKEND, GRND >::fSeed
Definition at line 59 of file DecayMothers.h.
The documentation for this struct was generated from the following file:
DecayMothers.h