Hydra: hydra::detail::TypeTraits< T > Struct Template Reference
hydra::detail::TypeTraits< T > Struct Template Reference
Public Types
typedef T type
Static Public Member Functions
__host__ static __device__ type zero ()
__host__ static __device__ type one ()
__host__ static __device__ type invalid ()
Detailed Description
template<typename T>
struct hydra::detail::TypeTraits< T >
Definition at line 67 of file TypeTraits.h.
Member Typedef Documentation
template<typename T > typedef T hydra::detail::TypeTraits< T >::type
Definition at line 70 of file TypeTraits.h.
Member Function Documentation
template<typename T > __host__ static __device__ type hydra::detail::TypeTraits< T >::invalid () inline static
Definition at line 73 of file TypeTraits.h.
References hydra::detail::kInvalidNumber.
template<typename T > __host__ static __device__ type hydra::detail::TypeTraits< T >::one () inline static
Definition at line 72 of file TypeTraits.h.
Referenced by hydra::detail::product(), and hydra::detail::product2().
template<typename T > __host__ static __device__ type hydra::detail::TypeTraits< T >::zero () inline static
Definition at line 71 of file TypeTraits.h.
Referenced by hydra::detail::accumulate(), and hydra::detail::accumulate2().
The documentation for this struct was generated from the following file:
TypeTraits.h