Hydra: hydra::Vector4R Class Reference
hydra::Vector4R Class Reference
Public Member Functions
__host__ __device__ Vector4R ()
__host__ __device__ Vector4R (GReal_t e, GReal_t px, GReal_t py, GReal_t pz)
__host__ __device__ Vector4R (const Vector4R &other)
__host__ __device__ void set (GInt_t i, GReal_t d)
__host__ __device__ void set (GReal_t e, GReal_t px, GReal_t py, GReal_t pz)
__host__ __device__ Vector4R & operator*= (GReal_t c)
__host__ __device__ Vector4R & operator/= (GReal_t c)
__host__ __device__ Vector4R & operator= (const Vector4R &v2)
__host__ __device__ Vector4R & operator+= (const Vector4R &v2)
__host__ __device__ Vector4R & operator-= (const Vector4R &v2)
__host__ __device__ GReal_t get (GInt_t i) const
__host__ __device__ GReal_t cont (const Vector4R &v4) const
__host__ __device__ GReal_t mass2 () const
__host__ __device__ GReal_t mass () const
__host__ __device__ void applyRotateEuler (GReal_t alpha, GReal_t beta, GReal_t gamma)
__host__ __device__ void applyBoostTo (const Vector4R &p4, bool inverse=false)
__host__ __device__ void applyBoostTo (const Vector3R &boost, bool inverse=false)
__host__ __device__ void applyBoostTo (const GReal_t bx, const GReal_t by, const GReal_t bz, bool inverse=false)
__host__ __device__ Vector4R cross (const Vector4R &v2)
__host__ __device__ GReal_t dot (const Vector4R &v2) const
__host__ __device__ GReal_t d3mag () const
__host__ __device__ GReal_t scalartripler3 (const Vector4R &p1, const Vector4R &p2, const Vector4R &p3) const
__host__ __device__ GReal_t dotr3 (const Vector4R &p1, const Vector4R &p2) const
__host__ __device__ GReal_t mag2r3 (const Vector4R &p1) const
__host__ __device__ GReal_t magr3 (const Vector4R &p1) const
Friends
__host__ __device__ friend Vector4R operator* (GReal_t d, const Vector4R &v2)
__host__ __device__ friend Vector4R operator* (const Vector4R &v2, GReal_t d)
__host__ __device__ friend Vector4R operator/ (const Vector4R &v2, GReal_t d)
__host__ __device__ friend GReal_t operator* (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ friend Vector4R operator+ (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ friend Vector4R operator- (const Vector4R &v1, const Vector4R &v2)
__host__ friend std::ostream & operator<< (std::ostream &s, const Vector4R &v)
Detailed Description
Definition at line 49 of file Vector4R.h.
Constructor & Destructor Documentation
__host__ __device__ hydra::Vector4R::Vector4R () inline
Definition at line 133 of file Vector4R.inl.
Referenced by hydra::operator*(), hydra::operator+(), hydra::operator-(), and hydra::operator/().
__host__ __device__ hydra::Vector4R::Vector4R (GReal_t e, GReal_t px, GReal_t py, GReal_t pz) inline
Definition at line 141 of file Vector4R.inl.
__host__ __device__ hydra::Vector4R::Vector4R (const Vector4R & other) inline
Definition at line 150 of file Vector4R.inl.
References get().
Member Function Documentation
__host__ __device__ void hydra::Vector4R::applyBoostTo (const Vector4R & p4, bool inverse = false) inline
Definition at line 200 of file Vector4R.inl.
References get().
Referenced by hydra::boostTo(), hydra::DecayMothers< N, BACKEND, GRND >::process(), and hydra::DecayMother< N, BACKEND, GRND >::process().
__host__ __device__ void hydra::Vector4R::applyBoostTo (const Vector3R & boost, bool inverse = false) inline
Definition at line 213 of file Vector4R.inl.
References hydra::Vector3R::get().
__host__ __device__ void hydra::Vector4R::applyBoostTo (const GReal_t bx, const GReal_t by, const GReal_t bz, bool inverse = false) inline
Definition at line 275 of file Vector4R.inl.
__host__ __device__ void hydra::Vector4R::applyRotateEuler (GReal_t alpha, GReal_t beta, GReal_t gamma) inline
Definition at line 176 of file Vector4R.inl.
Referenced by hydra::rotateEuler().
__host__ __device__ GReal_t hydra::Vector4R::cont (const Vector4R & v4) const inline
Definition at line 102 of file Vector4R.inl.
__host__ __device__ Vector4R hydra::Vector4R::cross (const Vector4R & v2) inline
Definition at line 334 of file Vector4R.inl.
__host__ __device__ GReal_t hydra::Vector4R::d3mag () const inline
Definition at line 350 of file Vector4R.inl.
Referenced by hydra::DecayMother< N, BACKEND, GRND >::DecayMother(), and hydra::DecayMothers< N, BACKEND, GRND >::process().
__host__ __device__ GReal_t hydra::Vector4R::dot (const Vector4R & v2) const inline
Definition at line 363 of file Vector4R.inl.
__host__ __device__ GReal_t hydra::Vector4R::dotr3 (const Vector4R & p1, const Vector4R & p2) const inline
Definition at line 383 of file Vector4R.inl.
References mass2().
__host__ __device__ GReal_t hydra::Vector4R::get (GInt_t i) const inline
Definition at line 110 of file Vector4R.inl.
Referenced by applyBoostTo(), hydra::DecayMother< N, BACKEND, GRND >::DecayMother(), operator=(), hydra::DecayMothers< N, BACKEND, GRND >::process(), hydra::DecayMother< N, BACKEND, GRND >::process(), and Vector4R().
__host__ __device__ GReal_t hydra::Vector4R::mag2r3 (const Vector4R & p1) const inline
Definition at line 391 of file Vector4R.inl.
References mass2().
Referenced by magr3().
__host__ __device__ GReal_t hydra::Vector4R::magr3 (const Vector4R & p1) const inline
Definition at line 398 of file Vector4R.inl.
References mag2r3().
__host__ __device__ GReal_t hydra::Vector4R::mass () const inline
Definition at line 159 of file Vector4R.inl.
Referenced by hydra::DecayMother< N, BACKEND, GRND >::DecayMother(), and hydra::DecayMothers< N, BACKEND, GRND >::process().
__host__ __device__ GReal_t hydra::Vector4R::mass2 () const inline
Definition at line 68 of file Vector4R.inl.
Referenced by dotr3(), and mag2r3().
__host__ __device__ Vector4R & hydra::Vector4R::operator*= (GReal_t c) inline
Definition at line 76 of file Vector4R.inl.
__host__ __device__ Vector4R & hydra::Vector4R::operator+= (const Vector4R & v2) inline
Definition at line 46 of file Vector4R.inl.
__host__ __device__ Vector4R & hydra::Vector4R::operator-= (const Vector4R & v2) inline
Definition at line 57 of file Vector4R.inl.
__host__ __device__ Vector4R & hydra::Vector4R::operator/= (GReal_t c) inline
Definition at line 88 of file Vector4R.inl.
__host__ __device__ Vector4R & hydra::Vector4R::operator= (const Vector4R & v2) inline
Definition at line 35 of file Vector4R.inl.
References get().
__host__ __device__ GReal_t hydra::Vector4R::scalartripler3 (const Vector4R & p1, const Vector4R & p2, const Vector4R & p3) const inline
__host__ __device__ void hydra::Vector4R::set (GInt_t i, GReal_t d) inline
Definition at line 115 of file Vector4R.inl.
Referenced by hydra::DecayMothers< N, BACKEND, GRND >::process(), and hydra::DecayMother< N, BACKEND, GRND >::process().
__host__ __device__ void hydra::Vector4R::set (GReal_t e, GReal_t px, GReal_t py, GReal_t pz) inline
Definition at line 121 of file Vector4R.inl.
Friends And Related Function Documentation
__host__ __device__ friend Vector4R operator* (GReal_t d, const Vector4R & v2) friend
Definition at line 166 of file Vector4R.h.
__host__ __device__ friend Vector4R operator* (const Vector4R & v2, GReal_t d) friend
Definition at line 172 of file Vector4R.h.
__host__ __device__ friend GReal_t operator* (const Vector4R & v1, const Vector4R & v2) friend
Definition at line 209 of file Vector4R.h.
__host__ __device__ friend Vector4R operator+ (const Vector4R & v1, const Vector4R & v2) friend
Definition at line 231 of file Vector4R.h.
__host__ __device__ friend Vector4R operator- (const Vector4R & v1, const Vector4R & v2) friend
Definition at line 225 of file Vector4R.h.
__host__ __device__ friend Vector4R operator/ (const Vector4R & v2, GReal_t d) friend
Definition at line 178 of file Vector4R.h.
__host__ friend std::ostream& operator<< (std::ostream & s, const Vector4R & v) friend
Definition at line 356 of file Vector4R.h.
The documentation for this class was generated from the following files:
Vector4R.h
Vector4R.inl