Hydra: hydra::detail Namespace Reference
hydra::detail Namespace Reference
Classes
struct _merge_and_renumber
struct _merge_and_renumber< index_sequence< I1... >, index_sequence< I2... > >
struct AddPdfBase
struct AddPdfChecker
struct append_to_type_seq
struct append_to_type_seq< T, TT< Ts... > >
struct are_base_of
struct are_base_of< Base, T >
struct BackendTraits
struct BackendTraits< device >
struct BackendTraits< host >
struct bool_pack
struct conditions_and
struct conditions_and< Cond, Conds... >
struct copy_type
struct divide_result
struct function_traits
struct function_traits< ReturnType(ClassType::*)(Args &...)>
struct function_traits< ReturnType(ClassType::*)(Args...) const >
struct has_analytical_integral
struct has_analytical_integral< C, Ret(Args...)>
class if_then_else
class if_then_else< false, T1, T2 >
class if_then_else< true, T1, T2 >
struct if_then_else_tt
struct if_then_else_tt< false, T1, T2 >
struct if_then_else_tt< true, T1, T2 >
struct index_sequence
struct is_homogeneous
struct is_homogeneous_base
struct is_homogeneous_base< A, Tp, 0 >
struct is_hydra_functor
struct is_hydra_functor< T, typename tag_type< typename T::hydra_functor_tag >::type >
struct is_hydra_integrator
struct is_hydra_integrator< T, typename tag_type< typename T::hydra_integrator_tag >::type >
struct is_hydra_pdf
struct is_hydra_pdf< T, typename tag_type< typename T::hydra_pdf_tag >::type >
struct is_hydra_sum_pdf
struct is_hydra_sum_pdf< T, typename tag_type< typename T::hydra_sum_pdf_tag >::type >
struct is_specialization
struct is_specialization< REF< Args... >, REF >
struct make_index_sequence
struct make_index_sequence< 0 >
struct make_index_sequence< 1 >
struct minus_result
struct multiply_result
struct ObjSelector
struct ObjSelector< false >
struct ObjSelector< true >
struct PdfBase
struct process
struct repeat
struct repeat< T, 0, TT >
struct sum_result
struct tag_type
struct tuple_type
struct TypeTraits
struct TypeTraits< thrust::complex< T > >
Typedefs
template<class... T>
using common_type_t = typename std::common_type< T... >::type
template<bool... bs>
using all_true = std::is_same< bool_pack< bs..., true >, bool_pack< true, bs... > >
template<class R , class... Ts>
using are_all_same = all_true< std::is_same< Ts, R >::value... >
Enumerations
enum { kInvalidNumber = -111 }
Functions
template<typename T , template< typename, typename... > class V, size_t N>
size_t get_size (std::array< V< T > *, N >const &Array)
template<typename Functor >
bool HasAnalyticalIntegral (Functor &f)
template<class T >
void hash_combine (std::size_t &seed, T const &v)
template<class It >
std::size_t hash_range (It first, It last)
template<class It >
void hash_range (std::size_t &seed, It first, It last)
template<size_t N, unsigned int BACKEND, typename GRND >
__host__ void launch_decayer (DecayMother< N, BACKEND, GRND > const &decayer, Events< N, BACKEND > &events)
template<size_t N, unsigned int BACKEND, typename GRND >
__host__ void launch_decayer (DecayMothers< N, BACKEND, GRND > const &decayer, typename Events< N, BACKEND >::vector_particles_iterator mothers_begin, Events< N, BACKEND > &events)
template<size_t I, typename... T>
__host__ __device__ thrust::tuple_element< I, thrust::tuple< T... > >::type addTuplesHelper (const thrust::tuple< T... > &a, const thrust::tuple< T... > &b)
template<typename... T, size_t... I>
__host__ __device__ thrust::tuple< T... > addTuples (const thrust::tuple< T... > &a, const thrust::tuple< T... > &b, index_sequence< I... >)
template<typename... T>
__host__ __device__ thrust::tuple< T... > addTuples (const thrust::tuple< T... > &a, const thrust::tuple< T... > &b)
template<typename Iterator , size_t... Index>
__host__ auto get_zip_iterator_helper (std::array< Iterator, sizeof...(Index)>const &array_of_iterators, index_sequence< Index... >) -> decltype(thrust::make_zip_iterator(thrust::make_tuple(array_of_iterators[Index]...)))
template<typename IteratorHead , typename IteratorTail , size_t... Index>
__host__ auto get_zip_iterator_helper (IteratorHead head, std::array< IteratorTail, sizeof...(Index)>const &array_of_iterators, index_sequence< Index... >) -> decltype(thrust::make_zip_iterator(thrust::make_tuple(head, array_of_iterators[Index]...)))
template<typename Iterator , size_t N>
__host__ auto get_zip_iterator (std::array< Iterator, N >const &array_of_iterators) -> decltype(get_zip_iterator_helper(array_of_iterators, make_index_sequence< N >
template<typename IteratorHead , typename IteratorTail , size_t N>
__host__ auto get_zip_iterator (IteratorHead head, std::array< IteratorTail, N >const &array_of_iterators) -> decltype(get_zip_iterator_helper(head, array_of_iterators, make_index_sequence< N >
template<typename T , size_t... Is>
auto make_tuple_helper (std::array< T, sizeof...(Is)> &Array, index_sequence< Is... >) -> decltype(thrust::make_tuple(Array[Is]...))
template<typename T , size_t N>
auto make_tuple (T value) -> decltype(make_tuple_helper(std::array< T, N >(), make_index_sequence< N >
for (auto v:Array) v
return make_tuple_helper (Array, make_index_sequence< N >{})
template<typename T , size_t... Is>
auto arrayToTupleHelper (std::array< T, sizeof...(Is)>const &Array, index_sequence< Is... >) -> decltype(thrust::make_tuple(Array[Is]...))
template<typename T , size_t N>
auto arrayToTuple (std::array< T, N >const &Array) -> decltype(arrayToTupleHelper(Array, make_index_sequence< N >
template<typename T , size_t... Indices>
__host__ __device__ auto arrayToTupleHelper (T *Array, index_sequence< Indices... >) -> decltype(thrust::make_tuple(Array[Indices]...))
template<typename T , size_t N>
__host__ __device__ auto arrayToTuple (T *Array) -> decltype(arrayToTupleHelper(Array, make_index_sequence< N >
template<size_t I = 0, typename FistType , typename... OtherTypes>
thrust::detail::enable_if< I==(sizeof...(OtherTypes)+1)&&are_all_same< FistType, OtherTypes... >::value, void >::type tupleToArray (thrust::tuple< FistType, OtherTypes... > const &, std::array< FistType, sizeof...(OtherTypes)+1 > &Array)
template<size_t I = 0, typename FistType , typename... OtherTypes>
thrust::detail::enable_if<(I< sizeof...(OtherTypes)+1)&&are_all_same< FistType, OtherTypes... >::value, void >::type tupleToArray (thrust::tuple< FistType, OtherTypes... > const &t, std::array< FistType, sizeof...(OtherTypes)+1 > &Array)
template<size_t I = 0, typename FistType , typename... OtherTypes>
__host__ __device__ thrust::detail::enable_if< I==(sizeof...(OtherTypes)+1)&&are_all_same< FistType, OtherTypes... >::value, void >::type tupleToArray (thrust::tuple< FistType, OtherTypes... > &, typename std::remove_reference< FistType >::type *Array)
template<size_t I = 0, typename FistType , typename... OtherTypes>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(OtherTypes)+1)&&are_all_same< FistType, OtherTypes... >::value, void >::type tupleToArray (thrust::tuple< FistType, OtherTypes... > &t, typename std::remove_reference< FistType >::type *Array)
template<size_t I = 0, typename Array_Type , typename T >
__host__ __device__ thrust::detail::enable_if<(I==thrust::tuple_size< T >::value)&&is_homogeneous< Array_Type, T >::value, void >::type set_ptrs_to_tuple (T &t, Array_Type **)
template<size_t I = 0, typename Array_Type , typename T >
__host__ __device__ thrust::detail::enable_if<(I< thrust::tuple_size< T >::value)&&is_homogeneous< Array_Type, T >::value, void >::type set_ptrs_to_tuple (T &t, Array_Type **Array)
template<typename T1 , typename T2 >
void ptr_setter (T1 *&ptr, typename thrust::detail::enable_if< thrust::detail::is_same< T1, T2 >::value, T2 >::type *el)
template<typename T1 , typename T2 >
void ptr_setter (T1 *&ptr, typename thrust::detail::enable_if<!thrust::detail::is_same< T1, T2 >::value, T2 >::type *el)
template<unsigned int I, typename Ptr , typename... Tp>
thrust::detail::enable_if< I==sizeof...(Tp), void >::type set_ptr_to_tuple_element (const int, std::tuple< Tp... > &, Ptr *&)
template<unsigned int I = 0, typename Ptr , typename... Tp>
thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type set_ptr_to_tuple_element (const int index, std::tuple< Tp... > &t, Ptr *&ptr)
template<unsigned int I = 0, typename T , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type get_tuple_element (const int, thrust::tuple< Tp... > const &, T &x)
template<unsigned int I = 0, typename T , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type get_tuple_element (const int index, thrust::tuple< Tp... > const &t, T &x)
template<unsigned int I = 0, typename T , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type set_tuple_element (const int, thrust::tuple< Tp... > const &, T &x)
template<unsigned int I = 0, typename T , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type set_tuple_element (const int index, thrust::tuple< Tp... > &t, const T &x)
template<unsigned int I = 0, typename FuncT , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type eval_on_tuple_element (int, thrust::tuple< Tp... > const &, FuncT const &)
template<unsigned int I = 0, typename FuncT , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type eval_on_tuple_element (int index, thrust::tuple< Tp... > const &t, FuncT const &f)
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type eval_tuple_element (Return_Type &, int, thrust::tuple< Tp... > const &, ArgType const &)
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type eval_tuple_element (Return_Type &r, int index, thrust::tuple< Tp... > const &t, ArgType const &arg)
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type sum_tuple (Return_Type &, thrust::tuple< Tp... > const &, ArgType const &)
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type sum_tuple (Return_Type &r, thrust::tuple< Tp... > &t, ArgType &arg)
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type sum_tuple2 (Return_Type &, thrust::tuple< Tp... > &, ArgType1 &, ArgType2 &)
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type sum_tuple2 (Return_Type &r, thrust::tuple< Tp... > &t, ArgType1 &arg1, ArgType2 &arg2)
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type product_tuple (Return_Type &, thrust::tuple< Tp... > &, ArgType &)
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type product_tuple (Return_Type &r, thrust::tuple< Tp... > &t, ArgType &arg)
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type product_tuple2 (Return_Type &, thrust::tuple< Tp... > const &, ArgType1 const &, ArgType2 const &)
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< (sizeof...(Tp))), void >::type product_tuple2 (Return_Type &r, thrust::tuple< Tp... > const &t, ArgType1 const &arg1, ArgType2 const &arg2)
template<size_t I = 0, size_t N, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp>
__host__ __device__ thrust::detail::enable_if< I==N, void >::type product_tuple3 (Return_Type &, thrust::tuple< Tp... > &, ArgType1 &, ArgType2 &)
template<size_t I = 0, size_t N, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp>
__host__ __device__ thrust::detail::enable_if<(I< N), void >::type product_tuple3 (Return_Type &r, thrust::tuple< Tp... > &t, ArgType1 &arg1, ArgType2 &arg2)
template<typename Tup , typename ArgType , size_t... index>
__host__ __device__ auto invoke_helper (ArgType &x, Tup &tup, index_sequence< index... >) -> decltype(thrust::make_tuple(thrust::get< index >(tup)(x)...))
template<typename Tup , typename ArgType >
__host__ __device__ auto invoke (ArgType &x, Tup &tup) -> decltype(invoke_helper(x, tup, make_index_sequence< thrust::tuple_size< Tup >::value >
return invoke_helper (x, tup, make_index_sequence< Size >{})
template<typename Tup , typename ArgType1 , typename ArgType2 , size_t... index>
__host__ __device__ auto invoke_helper (ArgType1 &x, ArgType2 &y, Tup &tup, index_sequence< index... >) -> decltype(thrust::make_tuple(thrust::get< index >(tup)(x, y)...))
template<typename Return_type , typename Tup , typename ArgType1 , typename ArgType2 >
__host__ __device__ auto invoke (ArgType1 &x, ArgType2 &y, Tup &tup) -> decltype(invoke_helper(x, y, tup, make_index_sequence< thrust::tuple_size< Tup >::value >
return invoke_helper (x, y, tup, make_index_sequence< Size >{})
template<size_t I = 0, typename... Tp>
__host__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type set_functors_in_tuple (thrust::tuple< Tp... > &, const std::vector< double > &parameters)
template<size_t I = 0, typename... Tp>
__host__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type set_functors_in_tuple (thrust::tuple< Tp... > &t, const std::vector< double > &parameters)
template<size_t I = 0, typename... Tp>
__host__ thrust::detail::enable_if< I==sizeof...(Tp), void >::type print_parameters_in_tuple (thrust::tuple< Tp... > &)
template<size_t I = 0, typename... Tp>
__host__ thrust::detail::enable_if<(I< sizeof...(Tp)), void >::type print_parameters_in_tuple (thrust::tuple< Tp... > &t)
template<typename Type , typename Tuple >
__host__ __device__ Type extract (const int idx, const Tuple &t)
template<typename Return_Type , typename ArgType , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value >::type>
__host__ __device__ Return_Type accumulate (ArgType &x, thrust::tuple< Tp... > &t)
template<typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value>::type>
__host__ __device__ Return_Type accumulate2 (ArgType1 &x, ArgType2 &y, thrust::tuple< Tp... > &t)
template<typename Return_Type , typename ArgType , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value >::type>
__host__ __device__ Return_Type product (ArgType const &x, thrust::tuple< Tp... > const &t)
template<typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value >::type>
__host__ __device__ Return_Type product2 (ArgType1 &x, ArgType2 &y, thrust::tuple< Tp... > &t)
template<typename L , typename ReturnType , typename... Args>
auto wrap_lambda_helper (L const &f, ReturnType r, thrust::tuple< Args... > t) -> LambdaWrapper< ReturnType(Args...), L >
Class Documentation
struct hydra::detail::_merge_and_renumber
template<class Sequence1, class Sequence2>
struct hydra::detail::_merge_and_renumber< Sequence1, Sequence2 >
Definition at line 97 of file Generic.h.
struct hydra::detail::append_to_type_seq
template<typename, typename>
struct hydra::detail::append_to_type_seq< typename, typename >
Definition at line 113 of file Generic.h.
struct hydra::detail::append_to_type_seq< T, TT< Ts... > >
template<typename T, typename... Ts, template< typename... > class TT>
struct hydra::detail::append_to_type_seq< T, TT< Ts... > >
Definition at line 116 of file Generic.h.
Class Members
type
struct hydra::detail::BackendTraits
template<int BACKEND>
struct hydra::detail::BackendTraits< BACKEND >
Definition at line 90 of file TypeTraits.h.
struct hydra::detail::bool_pack
template<bool...>
struct hydra::detail::bool_pack<... >
Definition at line 58 of file Generic.h.
struct hydra::detail::copy_type
template<template< typename... > class CONTAINER, typename T, unsigned int BACKEND>
struct hydra::detail::copy_type< CONTAINER, T, BACKEND >
Definition at line 27 of file Copy.h.
Class Members
typedef BackendTraits< BACKEND > system_t
typedef template container< T > type
struct hydra::detail::divide_result
template<typename F1, typename F2, typename... Fs>
struct hydra::detail::divide_result< F1, F2, Fs >
Definition at line 56 of file base_functor.h.
Class Members
type
struct hydra::detail::function_traits
template<typename T>
struct hydra::detail::function_traits< T >
Definition at line 156 of file TypeTraits.h.
struct hydra::detail::function_traits< ReturnType(ClassType::*)(Args &...)>
template<typename ClassType, typename ReturnType, typename... Args>
struct hydra::detail::function_traits< ReturnType(ClassType::*)(Args &...)>
Definition at line 177 of file TypeTraits.h.
Class Members
args_type
typedef ReturnType return_type
Class Members
__unnamed__
struct hydra::detail::function_traits< ReturnType(ClassType::*)(Args...) const >
template<typename ClassType, typename ReturnType, typename... Args>
struct hydra::detail::function_traits< ReturnType(ClassType::*)(Args...) const >
Definition at line 161 of file TypeTraits.h.
Class Members
args_type
typedef ReturnType return_type
Class Members
__unnamed__
struct hydra::detail::has_analytical_integral
template<typename, typename T>
struct hydra::detail::has_analytical_integral< typename, T >
Definition at line 86 of file FunctorTraits.h.
class hydra::detail::if_then_else
template<bool C, typename T1, typename T2>
class hydra::detail::if_then_else< C, T1, T2 >
Definition at line 133 of file TypeTraits.h.
class hydra::detail::if_then_else< false, T1, T2 >
template<typename T1, typename T2>
class hydra::detail::if_then_else< false, T1, T2 >
Definition at line 143 of file TypeTraits.h.
Class Members
typedef T2 type
class hydra::detail::if_then_else< true, T1, T2 >
template<typename T1, typename T2>
class hydra::detail::if_then_else< true, T1, T2 >
Definition at line 136 of file TypeTraits.h.
Class Members
typedef T1 type
struct hydra::detail::if_then_else_tt
template<bool Condition, template< typename... > class T1, template< typename... > class T2>
struct hydra::detail::if_then_else_tt< Condition, T1, T2 >
Definition at line 113 of file TypeTraits.h.
struct hydra::detail::if_then_else_tt< false, T1, T2 >
template<template< typename... > class T1, template< typename... > class T2>
struct hydra::detail::if_then_else_tt< false, T1, T2 >
Definition at line 123 of file TypeTraits.h.
Class Members
type
struct hydra::detail::if_then_else_tt< true, T1, T2 >
template<template< typename... > class T1, template< typename... > class T2>
struct hydra::detail::if_then_else_tt< true, T1, T2 >
Definition at line 116 of file TypeTraits.h.
Class Members
type
struct hydra::detail::minus_result
template<typename F1, typename F2, typename... Fs>
struct hydra::detail::minus_result< F1, F2, Fs >
Definition at line 61 of file base_functor.h.
Class Members
type
struct hydra::detail::multiply_result
template<typename F1, typename F2, typename... Fs>
struct hydra::detail::multiply_result< F1, F2, Fs >
Definition at line 51 of file base_functor.h.
Class Members
type
struct hydra::detail::ObjSelector
template<bool FLAG>
struct hydra::detail::ObjSelector< FLAG >
Definition at line 130 of file Generic.h.
struct hydra::detail::repeat
template<typename T, unsigned int N, template< typename... > class TT>
struct hydra::detail::repeat< T, N, TT >
Definition at line 119 of file Generic.h.
Class Members
typedef typename
append_to_type_seq< T,
typename repeat< T, N-1, TT >
::type >::type type
struct hydra::detail::repeat< T, 0, TT >
template<typename T, template< typename... > class TT>
struct hydra::detail::repeat< T, 0, TT >
Definition at line 125 of file Generic.h.
Class Members
typedef TT<> type
struct hydra::detail::sum_result
template<typename F1, typename F2, typename... Fs>
struct hydra::detail::sum_result< F1, F2, Fs >
Definition at line 46 of file base_functor.h.
Class Members
type
struct hydra::detail::tag_type
template<class T, class R = void>
struct hydra::detail::tag_type< T, R >
Definition at line 45 of file FunctorTraits.h.
Class Members
typedef R type
struct hydra::detail::tuple_type
template<size_t N, typename T>
struct hydra::detail::tuple_type< N, T >
Definition at line 66 of file Utility_Tuple.h.
Class Members
typedef repeat< T, N, tuple >::type type
Typedef Documentation
template<bool... bs> using hydra::detail::all_true = typedef std::is_same<bool_pack<bs..., true>, bool_pack<true, bs...> >
Definition at line 60 of file Generic.h.
template<class R , class... Ts> using hydra::detail::are_all_same = typedef all_true<std::is_same<Ts, R>::value...>
Definition at line 63 of file Generic.h.
template<class... T> using hydra::detail::common_type_t = typedef typename std::common_type<T...>::type
Definition at line 151 of file TypeTraits.h.
Enumeration Type Documentation
anonymous enum
Enumerator
kInvalidNumber
Definition at line 64 of file TypeTraits.h.
Function Documentation
template<typename Return_Type , typename ArgType , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value >::type> __host__ __device__ Return_Type hydra::detail::accumulate (ArgType & x, thrust::tuple< Tp... > & t) inline
Definition at line 510 of file Utility_Tuple.h.
References sum_tuple(), and hydra::detail::TypeTraits< T >::zero().
Referenced by hydra::Sum< F1, F2, Fs >::operator()().
template<typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value>::type> __host__ __device__ Return_Type hydra::detail::accumulate2 (ArgType1 & x, ArgType2 & y, thrust::tuple< Tp... > & t) inline
Definition at line 520 of file Utility_Tuple.h.
References sum_tuple2(), and hydra::detail::TypeTraits< T >::zero().
Referenced by hydra::Sum< F1, F2, Fs >::operator()().
template<typename... T, size_t... I> __host__ __device__ thrust::tuple<T...> hydra::detail::addTuples (const thrust::tuple< T... > & a, const thrust::tuple< T... > & b, index_sequence< I... >) inline
Definition at line 58 of file Arithmetic_Tuple.h.
References make_tuple().
Referenced by addTuples(), and hydra::operator+().
template<typename... T> __host__ __device__ thrust::tuple<T...> hydra::detail::addTuples (const thrust::tuple< T... > & a, const thrust::tuple< T... > & b) inline
Definition at line 65 of file Arithmetic_Tuple.h.
References addTuples().
template<size_t I, typename... T> __host__ __device__ thrust::tuple_element<I, thrust::tuple<T...> >::type hydra::detail::addTuplesHelper (const thrust::tuple< T... > & a, const thrust::tuple< T... > & b) inline
Definition at line 51 of file Arithmetic_Tuple.h.
template<typename T , size_t N> auto hydra::detail::arrayToTuple (std::array< T, N >const & Array) -> decltype(arrayToTupleHelper(Array, make_index_sequence<N>
Definition at line 141 of file Utility_Tuple.h.
References arrayToTupleHelper().
template<typename T , size_t N> __host__ __device__ auto hydra::detail::arrayToTuple (T * Array) -> decltype(arrayToTupleHelper(Array, make_index_sequence<N> inline
Definition at line 160 of file Utility_Tuple.h.
References arrayToTupleHelper().
template<typename T , size_t... Is> auto hydra::detail::arrayToTupleHelper (std::array< T, sizeof...(Is)>const & Array, index_sequence< Is... >) -> decltype(thrust::make_tuple(Array[Is]...))
Definition at line 134 of file Utility_Tuple.h.
References make_tuple().
Referenced by arrayToTuple().
template<typename T , size_t... Indices> __host__ __device__ auto hydra::detail::arrayToTupleHelper (T * Array, index_sequence< Indices... >) -> decltype(thrust::make_tuple(Array[Indices]...)) inline
Definition at line 151 of file Utility_Tuple.h.
References make_tuple().
template<unsigned int I = 0, typename FuncT , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::eval_on_tuple_element (int , thrust::tuple< Tp... > const & , FuncT const &) inline
Definition at line 302 of file Utility_Tuple.h.
Referenced by eval_on_tuple_element().
template<unsigned int I = 0, typename FuncT , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::eval_on_tuple_element (int index, thrust::tuple< Tp... > const & t, FuncT const & f) inline
Definition at line 308 of file Utility_Tuple.h.
References eval_on_tuple_element().
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::eval_tuple_element (Return_Type & , int , thrust::tuple< Tp... > const & , ArgType const &) inline
Definition at line 322 of file Utility_Tuple.h.
Referenced by eval_tuple_element().
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::eval_tuple_element (Return_Type & r, int index, thrust::tuple< Tp... > const & t, ArgType const & arg) inline
Definition at line 328 of file Utility_Tuple.h.
References eval_tuple_element().
template<typename Type , typename Tuple > __host__ __device__ Type hydra::detail::extract (const int idx, const Tuple & t) inline
Definition at line 497 of file Utility_Tuple.h.
References get_tuple_element().
hydra::detail::for (auto v:Array)
template<typename T , template< typename, typename... > class V, size_t N> size_t hydra::detail::get_size (std::array< V< T > *, N >const & Array) inline
Definition at line 63 of file Evaluate.inl.
template<unsigned int I = 0, typename T , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::get_tuple_element (const int , thrust::tuple< Tp... > const & , T & x) inline
Definition at line 266 of file Utility_Tuple.h.
Referenced by extract(), get_tuple_element(), and set_tuple_element().
template<unsigned int I = 0, typename T , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::get_tuple_element (const int index, thrust::tuple< Tp... > const & t, T & x) inline
Definition at line 272 of file Utility_Tuple.h.
References get_tuple_element().
template<typename Iterator , size_t N> __host__ auto hydra::detail::get_zip_iterator (std::array< Iterator, N >const & array_of_iterators) -> decltype(get_zip_iterator_helper(array_of_iterators , make_index_sequence<N> inline
Definition at line 94 of file Utility_Tuple.h.
References get_zip_iterator_helper().
Referenced by hydra::Events< N, BACKEND >::Events(), launch_decayer(), and hydra::Events< N, BACKEND >::operator=().
template<typename IteratorHead , typename IteratorTail , size_t N> __host__ auto hydra::detail::get_zip_iterator (IteratorHead head, std::array< IteratorTail, N >const & array_of_iterators) -> decltype(get_zip_iterator_helper(head, array_of_iterators , make_index_sequence<N> inline
Definition at line 103 of file Utility_Tuple.h.
References get_zip_iterator_helper().
template<typename Iterator , size_t... Index> __host__ auto hydra::detail::get_zip_iterator_helper (std::array< Iterator, sizeof...(Index)>const & array_of_iterators, index_sequence< Index... >) -> decltype(thrust::make_zip_iterator(thrust::make_tuple(array_of_iterators[Index]...))) inline
Definition at line 74 of file Utility_Tuple.h.
References make_tuple().
Referenced by get_zip_iterator().
template<typename IteratorHead , typename IteratorTail , size_t... Index> __host__ auto hydra::detail::get_zip_iterator_helper (IteratorHead head, std::array< IteratorTail, sizeof...(Index)>const & array_of_iterators, index_sequence< Index... >) -> decltype(thrust::make_zip_iterator(thrust::make_tuple(head, array_of_iterators[Index]...))) inline
Definition at line 84 of file Utility_Tuple.h.
References make_tuple().
template<typename Functor > bool hydra::detail::HasAnalyticalIntegral (Functor & f)
Definition at line 115 of file FunctorTraits.h.
template<class T > void hydra::detail::hash_combine (std::size_t & seed, T const & v) inline
Definition at line 39 of file Hash.h.
Referenced by hash_range().
template<class It > std::size_t hydra::detail::hash_range (It first, It last) inline
Definition at line 45 of file Hash.h.
References hash_combine().
Referenced by hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetFcnCache().
template<class It > void hydra::detail::hash_range (std::size_t & seed, It first, It last) inline
Definition at line 56 of file Hash.h.
References hash_combine().
template<typename Tup , typename ArgType > __host__ __device__ auto hydra::detail::invoke (ArgType & x, Tup & tup) -> decltype(invoke_helper(x, tup, make_index_sequence< thrust::tuple_size<Tup>::value> inline
Definition at line 436 of file Utility_Tuple.h.
References invoke_helper().
template<typename Return_type , typename Tup , typename ArgType1 , typename ArgType2 > __host__ __device__ auto hydra::detail::invoke (ArgType1 & x, ArgType2 & y, Tup & tup) -> decltype(invoke_helper(x, y, tup, make_index_sequence< thrust::tuple_size<Tup>::value> inline
Definition at line 454 of file Utility_Tuple.h.
References invoke_helper().
template<typename Tup , typename ArgType , size_t... index> __host__ __device__ auto hydra::detail::invoke_helper (ArgType & x, Tup & tup, index_sequence< index... >) -> decltype(thrust::make_tuple(thrust::get<index>(tup)(x)...)) inline
Definition at line 428 of file Utility_Tuple.h.
References make_tuple().
Referenced by invoke().
return hydra::detail::invoke_helper (x , tup , make_index_sequence< Size >{})
template<typename Tup , typename ArgType1 , typename ArgType2 , size_t... index> __host__ __device__ auto hydra::detail::invoke_helper (ArgType1 & x, ArgType2 & y, Tup & tup, index_sequence< index... >) -> decltype(thrust::make_tuple(thrust::get<index>(tup)(x,y)...)) inline
Definition at line 446 of file Utility_Tuple.h.
References make_tuple().
return hydra::detail::invoke_helper (x , y , tup , make_index_sequence< Size >{})
template<size_t N, unsigned int BACKEND, typename GRND > __host__ void hydra::detail::launch_decayer (DecayMother< N, BACKEND, GRND > const & decayer, Events< N, BACKEND > & events) inline
Definition at line 69 of file launch_decayers.inl.
References hydra::Events< N, BACKEND >::DaughtersBegin(), get_zip_iterator(), hydra::Events< N, BACKEND >::GetNEvents(), and hydra::Events< N, BACKEND >::WeightsBegin().
Referenced by hydra::PhaseSpace< N, GRND >::Generate().
template<size_t N, unsigned int BACKEND, typename GRND > __host__ void hydra::detail::launch_decayer (DecayMothers< N, BACKEND, GRND > const & decayer, typename Events< N, BACKEND >::vector_particles_iterator mothers_begin, Events< N, BACKEND > & events) inline
Definition at line 88 of file launch_decayers.inl.
References hydra::Events< N, BACKEND >::DaughtersBegin(), get_zip_iterator(), hydra::Events< N, BACKEND >::GetNEvents(), and hydra::Events< N, BACKEND >::WeightsBegin().
template<typename T , size_t N> auto hydra::detail::make_tuple (T value) -> decltype(make_tuple_helper(std::array<T,N>(), make_index_sequence<N>
Definition at line 120 of file Utility_Tuple.h.
References make_tuple_helper().
Referenced by addTuples(), arrayToTupleHelper(), hydra::Eval(), get_zip_iterator_helper(), invoke_helper(), make_tuple_helper(), and hydra::Point< T, N, HasValueError, HasPointError >::operator=().
template<typename T , size_t... Is> auto hydra::detail::make_tuple_helper (std::array< T, sizeof...(Is)> & Array, index_sequence< Is... >) -> decltype(thrust::make_tuple(Array[Is]...))
Definition at line 112 of file Utility_Tuple.h.
References make_tuple().
Referenced by make_tuple().
return hydra::detail::make_tuple_helper (Array , make_index_sequence< N >{})
template<size_t I = 0, typename... Tp> __host__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::print_parameters_in_tuple (thrust::tuple< Tp... > &) inline
Definition at line 482 of file Utility_Tuple.h.
Referenced by print_parameters_in_tuple(), hydra::Minus< F1, F2 >::PrintRegisteredParameters(), hydra::Divide< F1, F2 >::PrintRegisteredParameters(), hydra::Sum< F1, F2, Fs >::PrintRegisteredParameters(), hydra::Multiply< F1, F2, Fs >::PrintRegisteredParameters(), and hydra::AddPdf< PDF1, PDF2, PDFs >::PrintRegisteredParameters().
template<size_t I = 0, typename... Tp> __host__ thrust::detail::enable_if<(I < sizeof...(Tp)),void >::type hydra::detail::print_parameters_in_tuple (thrust::tuple< Tp... > & t) inline
Definition at line 488 of file Utility_Tuple.h.
References print_parameters_in_tuple().
template<typename Return_Type , typename ArgType , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value >::type> __host__ __device__ Return_Type hydra::detail::product (ArgType const & x, thrust::tuple< Tp... > const & t) inline
Definition at line 531 of file Utility_Tuple.h.
References hydra::detail::TypeTraits< T >::one(), and product_tuple().
Referenced by hydra::Multiply< F1, F2, Fs >::operator()().
template<typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp, typename = typename thrust::detail::enable_if<std::is_convertible<Return_Type, double>::value || std::is_constructible<thrust::complex<double>,Return_Type>::value >::type> __host__ __device__ Return_Type hydra::detail::product2 (ArgType1 & x, ArgType2 & y, thrust::tuple< Tp... > & t) inline
Definition at line 541 of file Utility_Tuple.h.
References hydra::detail::TypeTraits< T >::one(), and product_tuple3().
Referenced by hydra::Multiply< F1, F2, Fs >::operator()().
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::product_tuple (Return_Type & , thrust::tuple< Tp... > & , ArgType &) inline
Definition at line 382 of file Utility_Tuple.h.
Referenced by product(), and product_tuple().
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)),void >::type hydra::detail::product_tuple (Return_Type & r, thrust::tuple< Tp... > & t, ArgType & arg) inline
Definition at line 388 of file Utility_Tuple.h.
References product_tuple().
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::product_tuple2 (Return_Type & , thrust::tuple< Tp... > const & , ArgType1 const & , ArgType2 const &) inline
Definition at line 397 of file Utility_Tuple.h.
Referenced by product_tuple2().
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < (sizeof...(Tp))),void >::type hydra::detail::product_tuple2 (Return_Type & r, thrust::tuple< Tp... > const & t, ArgType1 const & arg1, ArgType2 const & arg2) inline
Definition at line 403 of file Utility_Tuple.h.
References product_tuple2().
template<size_t I = 0, size_t N, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == N, void>::type hydra::detail::product_tuple3 (Return_Type & , thrust::tuple< Tp... > & , ArgType1 & , ArgType2 &) inline
Definition at line 412 of file Utility_Tuple.h.
Referenced by product2(), and product_tuple3().
template<size_t I = 0, size_t N, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < N),void >::type hydra::detail::product_tuple3 (Return_Type & r, thrust::tuple< Tp... > & t, ArgType1 & arg1, ArgType2 & arg2) inline
Definition at line 418 of file Utility_Tuple.h.
References product_tuple3().
template<typename T1 , typename T2 > void hydra::detail::ptr_setter (T1 *& ptr, typename thrust::detail::enable_if< thrust::detail::is_same< T1, T2 >::value, T2 >::type * el)
Definition at line 240 of file Utility_Tuple.h.
Referenced by set_ptr_to_tuple_element().
template<typename T1 , typename T2 > void hydra::detail::ptr_setter (T1 *& ptr, typename thrust::detail::enable_if<!thrust::detail::is_same< T1, T2 >::value, T2 >::type * el)
Definition at line 243 of file Utility_Tuple.h.
template<size_t I = 0, typename... Tp> __host__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::set_functors_in_tuple (thrust::tuple< Tp... > & , const std::vector< double > & parameters) inline
Definition at line 466 of file Utility_Tuple.h.
Referenced by set_functors_in_tuple(), hydra::Minus< F1, F2 >::SetParameters(), hydra::Divide< F1, F2 >::SetParameters(), hydra::Sum< F1, F2, Fs >::SetParameters(), hydra::Compose< F0, F1, Fs >::SetParameters(), hydra::Multiply< F1, F2, Fs >::SetParameters(), and hydra::AddPdf< PDF1, PDF2, PDFs >::SetParameters().
template<size_t I = 0, typename... Tp> __host__ thrust::detail::enable_if<(I < sizeof...(Tp)),void >::type hydra::detail::set_functors_in_tuple (thrust::tuple< Tp... > & t, const std::vector< double > & parameters) inline
Definition at line 472 of file Utility_Tuple.h.
References set_functors_in_tuple().
template<unsigned int I, typename Ptr , typename... Tp> thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::set_ptr_to_tuple_element (const int , std::tuple< Tp... > & , Ptr *&) inline
Definition at line 248 of file Utility_Tuple.h.
Referenced by set_ptr_to_tuple_element().
template<unsigned int I = 0, typename Ptr , typename... Tp> thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::set_ptr_to_tuple_element (const int index, std::tuple< Tp... > & t, Ptr *& ptr) inline
Definition at line 253 of file Utility_Tuple.h.
References ptr_setter(), and set_ptr_to_tuple_element().
template<size_t I = 0, typename Array_Type , typename T > __host__ __device__ thrust::detail::enable_if<(I == thrust::tuple_size<T>::value) && is_homogeneous<Array_Type, T>::value, void>::type hydra::detail::set_ptrs_to_tuple (T & t, Array_Type **) inline
Definition at line 223 of file Utility_Tuple.h.
Referenced by hydra::HyRndTrial< GRND, FUNCTOR, N >::operator()(), hydra::DecayMothers< N, BACKEND, GRND >::operator()(), and hydra::DecayMother< N, BACKEND, GRND >::operator()().
template<size_t I = 0, typename Array_Type , typename T > __host__ __device__ thrust::detail::enable_if<(I < thrust::tuple_size<T>::value) && is_homogeneous<Array_Type, T>::value, void>::type hydra::detail::set_ptrs_to_tuple (T & t, Array_Type ** Array) inline
Definition at line 229 of file Utility_Tuple.h.
template<unsigned int I = 0, typename T , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::set_tuple_element (const int , thrust::tuple< Tp... > const & , T & x) inline
Definition at line 284 of file Utility_Tuple.h.
template<unsigned int I = 0, typename T , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::set_tuple_element (const int index, thrust::tuple< Tp... > & t, const T & x) inline
Definition at line 290 of file Utility_Tuple.h.
References get_tuple_element().
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::sum_tuple (Return_Type & , thrust::tuple< Tp... > const & , ArgType const &) inline
Definition at line 346 of file Utility_Tuple.h.
Referenced by accumulate(), and sum_tuple().
template<size_t I = 0, typename Return_Type , typename ArgType , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::sum_tuple (Return_Type & r, thrust::tuple< Tp... > & t, ArgType & arg) inline
Definition at line 352 of file Utility_Tuple.h.
References sum_tuple().
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp> __host__ __device__ thrust::detail::enable_if<I == sizeof...(Tp), void>::type hydra::detail::sum_tuple2 (Return_Type & , thrust::tuple< Tp... > & , ArgType1 & , ArgType2 &) inline
Definition at line 361 of file Utility_Tuple.h.
Referenced by accumulate2(), and sum_tuple2().
template<size_t I = 0, typename Return_Type , typename ArgType1 , typename ArgType2 , typename... Tp> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(Tp)), void >::type hydra::detail::sum_tuple2 (Return_Type & r, thrust::tuple< Tp... > & t, ArgType1 & arg1, ArgType2 & arg2) inline
Definition at line 367 of file Utility_Tuple.h.
References sum_tuple2().
template<size_t I = 0, typename FistType , typename... OtherTypes> thrust::detail::enable_if<I == (sizeof...(OtherTypes) + 1) && are_all_same<FistType,OtherTypes...>::value, void>::type hydra::detail::tupleToArray (thrust::tuple< FistType, OtherTypes... > const & , std::array< FistType, sizeof...(OtherTypes)+1 > & Array) inline
Definition at line 171 of file Utility_Tuple.h.
Referenced by hydra::BaseFunctor< LambdaWrapper< ReturnType(ArgType), L >, ReturnType, 0 >::interface(), hydra::AddPdf< PDF1, PDF2, PDFs >::operator()(), and tupleToArray().
template<size_t I = 0, typename FistType , typename... OtherTypes> thrust::detail::enable_if<(I < sizeof...(OtherTypes)+1) && are_all_same<FistType,OtherTypes...>::value, void >::type hydra::detail::tupleToArray (thrust::tuple< FistType, OtherTypes... > const & t, std::array< FistType, sizeof...(OtherTypes)+1 > & Array) inline
Definition at line 177 of file Utility_Tuple.h.
References tupleToArray().
template<size_t I = 0, typename FistType , typename... OtherTypes> __host__ __device__ thrust::detail::enable_if<I == (sizeof...(OtherTypes) + 1) && are_all_same<FistType,OtherTypes...>::value, void>::type hydra::detail::tupleToArray (thrust::tuple< FistType, OtherTypes... > & , typename std::remove_reference< FistType >::type * Array) inline
Definition at line 190 of file Utility_Tuple.h.
template<size_t I = 0, typename FistType , typename... OtherTypes> __host__ __device__ thrust::detail::enable_if<(I < sizeof...(OtherTypes)+1) && are_all_same<FistType,OtherTypes...>::value, void >::type hydra::detail::tupleToArray (thrust::tuple< FistType, OtherTypes... > & t, typename std::remove_reference< FistType >::type * Array) inline
Definition at line 197 of file Utility_Tuple.h.
References tupleToArray().
template<typename L , typename ReturnType , typename... Args> auto hydra::detail::wrap_lambda_helper (L const & f, ReturnType r, thrust::tuple< Args... > t) -> LambdaWrapper<ReturnType(Args...), L>
Definition at line 75 of file FunctionWrapper.h.
Referenced by hydra::wrap_lambda().