Hydra: hydra::Sum< F1, F2, Fs > Struct Template Reference
hydra::Sum< F1, F2, Fs > Struct Template Reference
Public Types
typedef void hydra_functor_tag
typedef std::true_type is_functor
typedef detail::sum_result< typename F1::return_type,typename F2::return_type, typename Fs::return_type... >::type return_type
typedef thrust::tuple< F1, F2, Fs... > functors_type
Public Member Functions
__host__ Sum ()
__host__ Sum (F1 const &f1, F2 const &f2, Fs const &...functors)
__host__ __device__ Sum (const Sum< F1, F2, Fs... > &other)
__host__ __device__ Sum< F1, F2, Fs... > & operator= (Sum< F1, F2, Fs... > const &other)
__host__ void SetParameters (const std::vector< double > &parameters)
__host__ void PrintRegisteredParameters ()
__host__ __device__ functors_type GetFunctors () const
__host__ __device__ int GetIndex () const
__host__ __device__ void SetIndex (int index)
__host__ __device__ bool IsCached () const
__host__ __device__ void SetCached (bool cached=1)
template<typename T1 >
__host__ __device__ return_type operator() (T1 &&t)
template<typename T1 , typename T2 >
__host__ __device__ return_type operator() (T1 &&t, T2 &&cache)
template<typename T >
__host__ __device__ return_type operator() (T *x, T *p)
Detailed Description
template<typename F1, typename F2, typename... Fs>
struct hydra::Sum< F1, F2, Fs >
Definition at line 47 of file Sum.h.
Member Typedef Documentation
template<typename F1, typename F2, typename... Fs> typedef thrust::tuple<F1, F2, Fs...> hydra::Sum< F1, F2, Fs >::functors_type
Definition at line 55 of file Sum.h.
template<typename F1, typename F2, typename... Fs> typedef void hydra::Sum< F1, F2, Fs >::hydra_functor_tag
Definition at line 51 of file Sum.h.
template<typename F1, typename F2, typename... Fs> typedef std::true_type hydra::Sum< F1, F2, Fs >::is_functor
Definition at line 53 of file Sum.h.
template<typename F1, typename F2, typename... Fs> typedef detail::sum_result<typename F1::return_type ,typename F2::return_type,typename Fs::return_type...>::type hydra::Sum< F1, F2, Fs >::return_type
Definition at line 54 of file Sum.h.
Constructor & Destructor Documentation
template<typename F1, typename F2, typename... Fs> __host__ hydra::Sum< F1, F2, Fs >::Sum () inline
Definition at line 58 of file Sum.h.
template<typename F1, typename F2, typename... Fs> __host__ hydra::Sum< F1, F2, Fs >::Sum (F1 const & f1, F2 const & f2, Fs const &... functors) inline
Definition at line 64 of file Sum.h.
template<typename F1, typename F2, typename... Fs> __host__ __device__ hydra::Sum< F1, F2, Fs >::Sum (const Sum< F1, F2, Fs... > & other) inline
Definition at line 70 of file Sum.h.
Member Function Documentation
template<typename F1, typename F2, typename... Fs> __host__ __device__ functors_type hydra::Sum< F1, F2, Fs >::GetFunctors () const inline
Definition at line 104 of file Sum.h.
Referenced by hydra::Sum< F1, F2, Fs >::operator=().
template<typename F1, typename F2, typename... Fs> __host__ __device__ int hydra::Sum< F1, F2, Fs >::GetIndex () const inline
Definition at line 107 of file Sum.h.
Referenced by hydra::Sum< F1, F2, Fs >::operator=().
template<typename F1, typename F2, typename... Fs> __host__ __device__ bool hydra::Sum< F1, F2, Fs >::IsCached () const inline
Definition at line 113 of file Sum.h.
Referenced by hydra::Sum< F1, F2, Fs >::operator=().
template<typename F1, typename F2, typename... Fs> template<typename T1 > __host__ __device__ return_type hydra::Sum< F1, F2, Fs >::operator() (T1 && t) inline
Definition at line 124 of file Sum.h.
References hydra::detail::accumulate().
template<typename F1, typename F2, typename... Fs> template<typename T1 , typename T2 > __host__ __device__ return_type hydra::Sum< F1, F2, Fs >::operator() (T1 && t, T2 && cache) inline
Definition at line 132 of file Sum.h.
References hydra::detail::accumulate2().
template<typename F1, typename F2, typename... Fs> template<typename T > __host__ __device__ return_type hydra::Sum< F1, F2, Fs >::operator() (T * x, T * p) inline
Definition at line 141 of file Sum.h.
References hydra::detail::accumulate2().
template<typename F1, typename F2, typename... Fs> __host__ __device__ Sum<F1,F2, Fs...>& hydra::Sum< F1, F2, Fs >::operator= (Sum< F1, F2, Fs... > const & other) inline
Definition at line 77 of file Sum.h.
References hydra::Sum< F1, F2, Fs >::GetFunctors(), hydra::Sum< F1, F2, Fs >::GetIndex(), and hydra::Sum< F1, F2, Fs >::IsCached().
template<typename F1, typename F2, typename... Fs> __host__ void hydra::Sum< F1, F2, Fs >::PrintRegisteredParameters () inline
Definition at line 93 of file Sum.h.
References HYDRA_CALLER, HYDRA_ENDL, HYDRA_MSG, and hydra::detail::print_parameters_in_tuple().
template<typename F1, typename F2, typename... Fs> __host__ __device__ void hydra::Sum< F1, F2, Fs >::SetCached (bool cached = 1) inline
Definition at line 117 of file Sum.h.
template<typename F1, typename F2, typename... Fs> __host__ __device__ void hydra::Sum< F1, F2, Fs >::SetIndex (int index) inline
Definition at line 110 of file Sum.h.
template<typename F1, typename F2, typename... Fs> __host__ void hydra::Sum< F1, F2, Fs >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 87 of file Sum.h.
References hydra::detail::set_functors_in_tuple().
The documentation for this struct was generated from the following file:
Sum.h