Hydra: hydra::Random< GRND > Class Template Reference
hydra::Random< GRND > Class Template Reference
Public Member Functions
Random (GUInt_t seed)
Random (Random const &other)
~Random ()
GUInt_t GetSeed () const
void SetSeed (GUInt_t seed)
template<typename Iterator >
void Gauss (GReal_t mean, GReal_t sigma, Iterator begin, Iterator end)
template<typename Iterator >
void Exp (GReal_t tau, Iterator begin, Iterator end)
Fill the range (begin, end) with an exponential distribution.
template<typename Iterator >
void BreitWigner (GReal_t mean, GReal_t gamma, Iterator begin, Iterator end)
Fill the range (begin, end) with an exponential distribution.
template<typename Iterator >
void Uniform (GReal_t min, GReal_t max, Iterator begin, Iterator end)
Fill the range (begin, end) with a uniform distribution between [min, max].
template<typename FUNCTOR , typename Iterator >
void InverseCDF (FUNCTOR const &invcdf, Iterator begin, Iterator end)
template<unsigned int BACKEND, typename FUNCTOR , size_t N>
auto Sample (FUNCTOR const &functor, std::array< GReal_t, N > min, std::array< GReal_t, N > max, size_t trials) -> typename detail::if_then_else< BACKEND, mc_device_vector< typename detail::tuple_type< N, GReal_t >::type >, mc_host_vector< typename detail::tuple_type< N, GReal_t >::type > >::type
template<unsigned int BACKEND = device, typename FUNCTOR , size_t N>
void Sample (FUNCTOR const &functor, std::array< GReal_t, N > min, std::array< GReal_t, N > max, PointVector< BACKEND, GReal_t, N, false, false > &result, size_t trials)
Detailed Description
template<typename GRND = thrust::random::default_random_engine>
class hydra::Random< GRND >
Definition at line 54 of file Random.h.
Constructor & Destructor Documentation
template<typename GRND = thrust::random::default_random_engine> hydra::Random< GRND >::Random (GUInt_t seed) inline
Definition at line 57 of file Random.h.
template<typename GRND = thrust::random::default_random_engine> hydra::Random< GRND >::Random (Random< GRND > const & other) inline
Definition at line 61 of file Random.h.
template<typename GRND = thrust::random::default_random_engine> hydra::Random< GRND >::~Random () inline
Definition at line 65 of file Random.h.
Member Function Documentation
template<typename GRND > template<typename Iterator > void hydra::Random< GRND >::BreitWigner (GReal_t mean, GReal_t gamma, Iterator begin, Iterator end)
Definition at line 126 of file Random.inl.
Referenced by hydra::Random< GRND >::SetSeed().
template<typename GRND > template<typename Iterator > void hydra::Random< GRND >::Exp (GReal_t tau, Iterator begin, Iterator end)
Definition at line 104 of file Random.inl.
Referenced by hydra::Random< GRND >::SetSeed().
template<typename GRND > template<typename Iterator > void hydra::Random< GRND >::Gauss (GReal_t mean, GReal_t sigma, Iterator begin, Iterator end)
Definition at line 58 of file Random.inl.
Referenced by hydra::Random< GRND >::SetSeed().
template<typename GRND = thrust::random::default_random_engine> GUInt_t hydra::Random< GRND >::GetSeed () const inline
Definition at line 67 of file Random.h.
template<typename GRND > template<typename FUNCTOR , typename Iterator > void hydra::Random< GRND >::InverseCDF (FUNCTOR const & invcdf, Iterator begin, Iterator end)
Definition at line 36 of file Random.inl.
Referenced by hydra::Random< GRND >::SetSeed().
template<typename GRND > template<unsigned int BACKEND, typename FUNCTOR , size_t N> auto hydra::Random< GRND >::Sample (FUNCTOR const & functor, std::array< GReal_t, N > min, std::array< GReal_t, N > max, size_t trials) -> typename detail::if_then_else<BACKEND, mc_device_vector< typename detail::tuple_type<N,GReal_t>::type >, mc_host_vector< typename detail::tuple_type<N,GReal_t>::type> >::type
Definition at line 145 of file Random.inl.
References hydra::kTrue.
Referenced by hydra::Random< GRND >::SetSeed().
template<typename GRND > template<unsigned int BACKEND, typename FUNCTOR , size_t N> void hydra::Random< GRND >::Sample (FUNCTOR const & functor, std::array< GReal_t, N > min, std::array< GReal_t, N > max, PointVector< BACKEND, GReal_t, N, false, false > & result, size_t trials)
Definition at line 187 of file Random.inl.
References hydra::PointVector< BACKEND, T, N, V_ERROR, C_ERROR >::begin(), hydra::PointVector< BACKEND, T, N, V_ERROR, C_ERROR >::GetPoints(), and hydra::kTrue.
template<typename GRND = thrust::random::default_random_engine> void hydra::Random< GRND >::SetSeed (GUInt_t seed) inline
Definition at line 71 of file Random.h.
References hydra::Random< GRND >::BreitWigner(), hydra::Random< GRND >::Exp(), hydra::Random< GRND >::Gauss(), hydra::Random< GRND >::InverseCDF(), hydra::Random< GRND >::Sample(), and hydra::Random< GRND >::Uniform().
template<typename GRND > template<typename Iterator > void hydra::Random< GRND >::Uniform (GReal_t min, GReal_t max, Iterator begin, Iterator end)
Definition at line 82 of file Random.inl.
Referenced by hydra::Random< GRND >::SetSeed().
The documentation for this class was generated from the following files:
Random.h
Random.inl