var examples =
[
    [ "adaptive_gauss_kronrod.inl", "adaptive_gauss_kronrod_8inl-example.html", null ],
    [ "async.inl", "async_8inl-example.html", null ],
    [ "basic_distributions.inl", "basic_distributions_8inl-example.html", null ],
    [ "basic_fit.inl", "basic_fit_8inl-example.html", null ],
    [ "basic_fit_range_semantics.inl", "basic_fit_range_semantics_8inl-example.html", null ],
    [ "binned_extended_logLL_fit.inl", "binned_extended_logLL_fit_8inl-example.html", null ],
    [ "breit_wigner_plus_polynomial.inl", "breit_wigner_plus_polynomial_8inl-example.html", null ],
    [ "crystal_ball_plus_exponential.inl", "crystal_ball_plus_exponential_8inl-example.html", null ],
    [ "dalitz_plot.C", "dalitz_plot_8C-example.html", null ],
    [ "dalitz_plot.inl", "dalitz_plot_8inl-example.html", null ],
    [ "dense_histogram.inl", "dense_histogram_8inl-example.html", null ],
    [ "double_gaussian_plus_exponential.inl", "double_gaussian_plus_exponential_8inl-example.html", null ],
    [ "extended_logLL_fit.inl", "extended_logLL_fit_8inl-example.html", null ],
    [ "fit_gaussian.C", "fit_gaussian_8C-example.html", null ],
    [ "fit_johnson.C", "fit_johnson_8C-example.html", null ],
    [ "fractional_logLL_fit.inl", "fractional_logLL_fit_8inl-example.html", null ],
    [ "gauss_kronrod.inl", "gauss_kronrod_8inl-example.html", null ],
    [ "gaussian_plus_argus.inl", "gaussian_plus_argus_8inl-example.html", null ],
    [ "multiarray_container.inl", "multiarray_container_8inl-example.html", null ],
    [ "multidimensional_fit.inl", "multidimensional_fit_8inl-example.html", null ],
    [ "multivector_container.inl", "multivector_container_8inl-example.html", null ],
    [ "phsp_averaging_functor.inl", "phsp_averaging_functor_8inl-example.html", null ],
    [ "phsp_basic.inl", "phsp_basic_8inl-example.html", null ],
    [ "phsp_chain.inl", "phsp_chain_8inl-example.html", null ],
    [ "phsp_reweighting.inl", "phsp_reweighting_8inl-example.html", null ],
    [ "phsp_unweighting.inl", "phsp_unweighting_8inl-example.html", null ],
    [ "phsp_unweighting_functor.inl", "phsp_unweighting_functor_8inl-example.html", null ],
    [ "plain_mc.inl", "plain_mc_8inl-example.html", null ],
    [ "range_semantics.inl", "range_semantics_8inl-example.html", null ],
    [ "sample_distribution.inl", "sample_distribution_8inl-example.html", null ],
    [ "sparse_histogram.inl", "sparse_histogram_8inl-example.html", null ],
    [ "splot.inl", "splot_8inl-example.html", null ],
    [ "vegas.inl", "vegas_8inl-example.html", null ]
];