var files =
[
    [ "adaptive_gauss_kronrod.cpp", "adaptive__gauss__kronrod_8cpp.html", null ],
    [ "adaptive_gauss_kronrod.cu", "adaptive__gauss__kronrod_8cu.html", null ],
    [ "adaptive_gauss_kronrod.inl", "adaptive__gauss__kronrod_8inl.html", "adaptive__gauss__kronrod_8inl" ],
    [ "AddPdf.h", "AddPdf_8h.html", null ],
    [ "AddPdfBase.h", "AddPdfBase_8h.html", null ],
    [ "AddPdfFunctor.h", "AddPdfFunctor_8h.html", null ],
    [ "Argument.h", "Argument_8h.html", [
      [ "Argument", "structhydra_1_1Argument.html", "structhydra_1_1Argument" ]
    ] ],
    [ "Arithmetic_Tuple.h", "Arithmetic__Tuple_8h.html", "Arithmetic__Tuple_8h" ],
    [ "async_mc.cu", "async__mc_8cu.html", null ],
    [ "async_mc.inl", "async__mc_8inl.html", "async__mc_8inl" ],
    [ "AverageMother.h", "AverageMother_8h.html", null ],
    [ "AverageMothers.h", "AverageMothers_8h.html", null ],
    [ "BackendPolicy.h", "BackendPolicy_8h.html", null ],
    [ "base_functor.h", "base__functor_8h.html", null ],
    [ "basic_distributions.cpp", "basic__distributions_8cpp.html", null ],
    [ "basic_distributions.cu", "basic__distributions_8cu.html", null ],
    [ "basic_distributions.inl", "basic__distributions_8inl.html", "basic__distributions_8inl" ],
    [ "basic_fit.cpp", "basic__fit_8cpp.html", null ],
    [ "basic_fit.cu", "basic__fit_8cu.html", null ],
    [ "basic_fit.inl", "basic__fit_8inl.html", "basic__fit_8inl" ],
    [ "Cache.h", "Cache_8h.html", [
      [ "Cache", "namespacehydra.html#classhydra_1_1Cache", null ]
    ] ],
    [ "Caster.h", "Caster_8h.html", null ],
    [ "Chain.inl", "Chain_8inl.html", "Chain_8inl" ],
    [ "Chains.h", "Chains_8h.html", "Chains_8h" ],
    [ "Chains.inl", "Chains_8inl.html", "Chains_8inl" ],
    [ "CheckEnergy.h", "CheckEnergy_8h.html", null ],
    [ "Collection.h", "Collection_8h.html", "Collection_8h" ],
    [ "Complex.h", "Complex_8h.html", "Complex_8h" ],
    [ "Compose.h", "Compose_8h.html", "Compose_8h" ],
    [ "Config.h", "Config_8h.html", "Config_8h" ],
    [ "Constant.h", "Constant_8h.html", [
      [ "Constant", "structhydra_1_1Constant.html", "structhydra_1_1Constant" ]
    ] ],
    [ "Containers.h", "Containers_8h.html", "Containers_8h" ],
    [ "Containers.inl", "Containers_8inl.html", "Containers_8inl" ],
    [ "Copy.h", "Copy_8h.html", "Copy_8h" ],
    [ "CPP.h", "CPP_8h.html", "CPP_8h" ],
    [ "CUDA.h", "CUDA_8h.html", "CUDA_8h" ],
    [ "DecayMother.h", "DecayMother_8h.html", null ],
    [ "DecayMothers.h", "DecayMothers_8h.html", null ],
    [ "Decays.h", "Decays_8h.html", "Decays_8h" ],
    [ "Decays.inl", "Decays_8inl.html", "Decays_8inl" ],
    [ "dense_histogram.cpp", "dense__histogram_8cpp.html", null ],
    [ "dense_histogram.cu", "dense__histogram_8cu.html", null ],
    [ "dense_histogram.inl", "dense__histogram_8inl.html", "dense__histogram_8inl" ],
    [ "DenseHistogram.h", "DenseHistogram_8h.html", [
      [ "DenseHistogram", "namespacehydra.html#classhydra_1_1DenseHistogram", null ]
    ] ],
    [ "DenseHistogram.inl", "DenseHistogram_8inl.html", null ],
    [ "DEVICE.h", "DEVICE_8h.html", "DEVICE_8h" ],
    [ "Dimensionality.h", "Dimensionality_8h.html", null ],
    [ "Distance.h", "Distance_8h.html", "Distance_8h" ],
    [ "Divide.h", "Divide_8h.html", "Divide_8h" ],
    [ "EvalDaughters.h", "EvalDaughters_8h.html", null ],
    [ "EvalMother.h", "EvalMother_8h.html", null ],
    [ "EvalMothers.h", "EvalMothers_8h.html", null ],
    [ "Evaluate.h", "Evaluate_8h.html", "Evaluate_8h" ],
    [ "Evaluate.inc", "Evaluate_8inc.html", null ],
    [ "Evaluate.inl", "Evaluate_8inl.html", "Evaluate_8inl" ],
    [ "Events.h", "Events_8h.html", [
      [ "Events", "structhydra_1_1Events.html", "structhydra_1_1Events" ]
    ] ],
    [ "Events.inl", "Events_8inl.html", "Events_8inl" ],
    [ "extended_logLL_fit.cpp", "extended__logLL__fit_8cpp.html", null ],
    [ "extended_logLL_fit.cu", "extended__logLL__fit_8cu.html", null ],
    [ "extended_logLL_fit.inl", "extended__logLL__fit_8inl.html", "extended__logLL__fit_8inl" ],
    [ "FCN.h", "FCN_8h.html", [
      [ "FCN", "namespacehydra.html#classhydra_1_1FCN", null ],
      [ "FCN< Estimator< PDF, Iterator, Visitors... > >", "classhydra_1_1FCN_3_01Estimator_3_01PDF_00_01Iterator_00_01Visitors_8_8_8_01_4_01_4.html", "classhydra_1_1FCN_3_01Estimator_3_01PDF_00_01Iterator_00_01Visitors_8_8_8_01_4_01_4" ]
    ] ],
    [ "Filter.h", "Filter_8h.html", "Filter_8h" ],
    [ "Filter.inl", "Filter_8inl.html", "Filter_8inl" ],
    [ "FlagAcceptReject.h", "FlagAcceptReject_8h.html", null ],
    [ "fractional_logLL_fit.cpp", "fractional__logLL__fit_8cpp.html", null ],
    [ "fractional_logLL_fit.cu", "fractional__logLL__fit_8cu.html", null ],
    [ "fractional_logLL_fit.inl", "fractional__logLL__fit_8inl.html", "fractional__logLL__fit_8inl" ],
    [ "Function.h", "Function_8h.html", null ],
    [ "FunctionWrapper.h", "FunctionWrapper_8h.html", "FunctionWrapper_8h" ],
    [ "FunctorArithmetic.h", "FunctorArithmetic_8h.html", null ],
    [ "FunctorTraits.h", "FunctorTraits_8h.html", null ],
    [ "gauss_kronrod.cpp", "gauss__kronrod_8cpp.html", null ],
    [ "gauss_kronrod.cu", "gauss__kronrod_8cu.html", null ],
    [ "gauss_kronrod.inl", "gauss__kronrod_8inl.html", "gauss__kronrod_8inl" ],
    [ "GaussKronrodAdaptiveQuadrature.h", "GaussKronrodAdaptiveQuadrature_8h.html", [
      [ "GaussKronrodAdaptiveQuadrature", "namespacehydra.html#classhydra_1_1GaussKronrodAdaptiveQuadrature", null ]
    ] ],
    [ "GaussKronrodAdaptiveQuadrature.inl", "GaussKronrodAdaptiveQuadrature_8inl.html", "GaussKronrodAdaptiveQuadrature_8inl" ],
    [ "GaussKronrodQuadrature.h", "GaussKronrodQuadrature_8h.html", [
      [ "GaussKronrodQuadrature", "namespacehydra.html#classhydra_1_1GaussKronrodQuadrature", null ]
    ] ],
    [ "GaussKronrodQuadrature.inl", "GaussKronrodQuadrature_8inl.html", "GaussKronrodQuadrature_8inl" ],
    [ "GaussKronrodRule.h", "GaussKronrodRule_8h.html", [
      [ "GaussKronrodRule", "structhydra_1_1GaussKronrodRule.html", "structhydra_1_1GaussKronrodRule" ]
    ] ],
    [ "GaussKronrodRules.h", "GaussKronrodRules_8h.html", [
      [ "GaussKronrodRuleSelector", "namespacehydra.html#structhydra_1_1GaussKronrodRuleSelector", null ],
      [ "GaussKronrodRuleSelector< 15 >", "structhydra_1_1GaussKronrodRuleSelector_3_0115_01_4.html", "structhydra_1_1GaussKronrodRuleSelector_3_0115_01_4" ],
      [ "GaussKronrodRuleSelector< 21 >", "structhydra_1_1GaussKronrodRuleSelector_3_0121_01_4.html", "structhydra_1_1GaussKronrodRuleSelector_3_0121_01_4" ],
      [ "GaussKronrodRuleSelector< 31 >", "structhydra_1_1GaussKronrodRuleSelector_3_0131_01_4.html", "structhydra_1_1GaussKronrodRuleSelector_3_0131_01_4" ],
      [ "GaussKronrodRuleSelector< 41 >", "structhydra_1_1GaussKronrodRuleSelector_3_0141_01_4.html", "structhydra_1_1GaussKronrodRuleSelector_3_0141_01_4" ],
      [ "GaussKronrodRuleSelector< 51 >", "structhydra_1_1GaussKronrodRuleSelector_3_0151_01_4.html", "structhydra_1_1GaussKronrodRuleSelector_3_0151_01_4" ],
      [ "GaussKronrodRuleSelector< 61 >", "structhydra_1_1GaussKronrodRuleSelector_3_0161_01_4.html", "structhydra_1_1GaussKronrodRuleSelector_3_0161_01_4" ]
    ] ],
    [ "Generic.h", "Generic_8h.html", null ],
    [ "GenericRange.h", "GenericRange_8h.html", "GenericRange_8h" ],
    [ "GenzMalikBox.h", "GenzMalikBox_8h.html", null ],
    [ "GenzMalikQuadrature.h", "GenzMalikQuadrature_8h.html", [
      [ "GenzMalikQuadrature", "namespacehydra.html#classhydra_1_1GenzMalikQuadrature", null ]
    ] ],
    [ "GenzMalikQuadrature.inl", "GenzMalikQuadrature_8inl.html", "GenzMalikQuadrature_8inl" ],
    [ "GenzMalikRule.h", "GenzMalikRule_8h.html", [
      [ "GenzMalikRule", "namespacehydra.html#classhydra_1_1GenzMalikRule", null ],
      [ "GenzMalikRuleBase", "classhydra_1_1GenzMalikRuleBase.html", null ]
    ] ],
    [ "GetGlobalBin.h", "GetGlobalBin_8h.html", null ],
    [ "hydra/Groups.h", "hydra_2Groups_8h.html", null ],
    [ "doxydefs/Groups.h", "doxydefs_2Groups_8h.html", null ],
    [ "Hash.h", "Hash_8h.html", null ],
    [ "HOST.h", "HOST_8h.html", "HOST_8h" ],
    [ "Hydra.h", "Hydra_8h.html", "Hydra_8h" ],
    [ "Integrator.h", "Integrator_8h.html", [
      [ "Integrator", "structhydra_1_1Integrator.html", "structhydra_1_1Integrator" ]
    ] ],
    [ "IsAccepted.h", "IsAccepted_8h.html", null ],
    [ "IteratorTraits.h", "IteratorTraits_8h.html", null ],
    [ "launch_decayers.inl", "launch__decayers_8inl.html", "launch__decayers_8inl" ],
    [ "LogLikelihood.h", "LogLikelihood_8h.html", null ],
    [ "LogLikelihood1.h", "LogLikelihood1_8h.html", null ],
    [ "LogLikelihoodFCN.h", "LogLikelihoodFCN_8h.html", [
      [ "LogLikelihoodFCN", "namespacehydra.html#classhydra_1_1LogLikelihoodFCN", null ]
    ] ],
    [ "LogLikelihoodFCN1.inl", "LogLikelihoodFCN1_8inl.html", "LogLikelihoodFCN1_8inl" ],
    [ "LogLikelihoodFCN2.inl", "LogLikelihoodFCN2_8inl.html", "LogLikelihoodFCN2_8inl" ],
    [ "LogLikelihoodFCN3.inl", "LogLikelihoodFCN3_8inl.html", "LogLikelihoodFCN3_8inl" ],
    [ "Minus.h", "Minus_8h.html", "Minus_8h" ],
    [ "multiarray.h", "multiarray_8h.html", "multiarray_8h" ],
    [ "multiarray_container.cpp", "multiarray__container_8cpp.html", null ],
    [ "multiarray_container.cu", "multiarray__container_8cu.html", null ],
    [ "multiarray_container.inl", "multiarray__container_8inl.html", "multiarray__container_8inl" ],
    [ "multidimensional_fit.cpp", "multidimensional__fit_8cpp.html", null ],
    [ "multidimensional_fit.cu", "multidimensional__fit_8cu.html", null ],
    [ "multidimensional_fit.inl", "multidimensional__fit_8inl.html", "multidimensional__fit_8inl" ],
    [ "Multiply.h", "Multiply_8h.html", "Multiply_8h" ],
    [ "multivector.h", "multivector_8h.html", "multivector_8h" ],
    [ "multivector_container.cpp", "multivector__container_8cpp.html", null ],
    [ "multivector_container.cu", "multivector__container_8cu.html", null ],
    [ "multivector_container.inl", "multivector__container_8inl.html", "multivector__container_8inl" ],
    [ "OMP.h", "OMP_8h.html", "OMP_8h" ],
    [ "Parameter.h", "Parameter_8h.html", "Parameter_8h" ],
    [ "Parameters.h", "Parameters_8h.html", null ],
    [ "Pdf.h", "Pdf_8h.html", "Pdf_8h" ],
    [ "PDFSumExtendable.h", "PDFSumExtendable_8h.html", "PDFSumExtendable_8h" ],
    [ "PDFSumNonExtendable.h", "PDFSumNonExtendable_8h.html", "PDFSumNonExtendable_8h" ],
    [ "Permutation.h", "Permutation_8h.html", null ],
    [ "Permute.h", "Permute_8h.html", null ],
    [ "PhaseSpace.h", "PhaseSpace_8h.html", null ],
    [ "PhaseSpace.inl", "PhaseSpace_8inl.html", "PhaseSpace_8inl" ],
    [ "PhaseSpaceIntegrator.h", "PhaseSpaceIntegrator_8h.html", [
      [ "PhaseSpaceIntegrator", "namespacehydra.html#classhydra_1_1PhaseSpaceIntegrator", null ]
    ] ],
    [ "PhaseSpaceIntegrator.inl", "PhaseSpaceIntegrator_8inl.html", "PhaseSpaceIntegrator_8inl" ],
    [ "phsp_averaging_functor.cpp", "phsp__averaging__functor_8cpp.html", null ],
    [ "phsp_averaging_functor.cu", "phsp__averaging__functor_8cu.html", null ],
    [ "phsp_averaging_functor.inl", "phsp__averaging__functor_8inl.html", "phsp__averaging__functor_8inl" ],
    [ "phsp_basic.cpp", "phsp__basic_8cpp.html", null ],
    [ "phsp_basic.cu", "phsp__basic_8cu.html", null ],
    [ "phsp_basic.inl", "phsp__basic_8inl.html", "phsp__basic_8inl" ],
    [ "phsp_chain.cpp", "phsp__chain_8cpp.html", null ],
    [ "phsp_chain.cu", "phsp__chain_8cu.html", null ],
    [ "phsp_chain.inl", "phsp__chain_8inl.html", "phsp__chain_8inl" ],
    [ "phsp_evaluating_functor.cpp", "phsp__evaluating__functor_8cpp.html", null ],
    [ "phsp_evaluating_functor.cu", "phsp__evaluating__functor_8cu.html", null ],
    [ "phsp_evaluating_functor.inl", "phsp__evaluating__functor_8inl.html", "phsp__evaluating__functor_8inl" ],
    [ "phsp_reweighting.cpp", "phsp__reweighting_8cpp.html", null ],
    [ "phsp_reweighting.cu", "phsp__reweighting_8cu.html", null ],
    [ "phsp_reweighting.inl", "phsp__reweighting_8inl.html", "phsp__reweighting_8inl" ],
    [ "phsp_unweighting.cpp", "phsp__unweighting_8cpp.html", null ],
    [ "phsp_unweighting.cu", "phsp__unweighting_8cu.html", null ],
    [ "phsp_unweighting.inl", "phsp__unweighting_8inl.html", "phsp__unweighting_8inl" ],
    [ "phsp_unweighting_functor.cpp", "phsp__unweighting__functor_8cpp.html", null ],
    [ "phsp_unweighting_functor.cu", "phsp__unweighting__functor_8cu.html", null ],
    [ "phsp_unweighting_functor.inl", "phsp__unweighting__functor_8inl.html", "phsp__unweighting__functor_8inl" ],
    [ "phsp_unweighting_functor_and_fit.cpp", "phsp__unweighting__functor__and__fit_8cpp.html", null ],
    [ "phsp_unweighting_functor_and_fit.cu", "phsp__unweighting__functor__and__fit_8cu.html", null ],
    [ "phsp_unweighting_functor_and_fit.inl", "phsp__unweighting__functor__and__fit_8inl.html", "phsp__unweighting__functor__and__fit_8inl" ],
    [ "Placeholders.h", "Placeholders_8h.html", [
      [ "is_placeholder", "structhydra_1_1placeholders_1_1is__placeholder.html", null ],
      [ "is_placeholder< placeholder< I > >", "structhydra_1_1placeholders_1_1is__placeholder_3_01placeholder_3_01I_01_4_01_4.html", null ],
      [ "placeholder", "structhydra_1_1placeholders_1_1placeholder.html", "structhydra_1_1placeholders_1_1placeholder" ]
    ] ],
    [ "Placeholders.inl", "Placeholders_8inl.html", "Placeholders_8inl" ],
    [ "Plain.h", "Plain_8h.html", [
      [ "Plain", "namespacehydra.html#structhydra_1_1Plain", null ]
    ] ],
    [ "Plain.inl", "Plain_8inl.html", null ],
    [ "plain_mc.cpp", "plain__mc_8cpp.html", null ],
    [ "plain_mc.cu", "plain__mc_8cu.html", null ],
    [ "plain_mc.inl", "plain__mc_8inl.html", "plain__mc_8inl" ],
    [ "PlainState.h", "PlainState_8h.html", null ],
    [ "PredicatesVegas.h", "PredicatesVegas_8h.html", null ],
    [ "Print.h", "Print_8h.html", "Print_8h" ],
    [ "ProcessCallsPlain.h", "ProcessCallsPlain_8h.html", null ],
    [ "ProcessCallsVegas.h", "ProcessCallsVegas_8h.html", null ],
    [ "ProcessGaussKronrodAdaptiveQuadrature.h", "ProcessGaussKronrodAdaptiveQuadrature_8h.html", [
      [ "ProcessGaussKronrodAdaptiveQuadrature", "structhydra_1_1ProcessGaussKronrodAdaptiveQuadrature.html", "structhydra_1_1ProcessGaussKronrodAdaptiveQuadrature" ]
    ] ],
    [ "ProcessGaussKronrodQuadrature.h", "ProcessGaussKronrodQuadrature_8h.html", [
      [ "GaussKronrodBinary", "structhydra_1_1GaussKronrodBinary.html", "structhydra_1_1GaussKronrodBinary" ],
      [ "GaussKronrodCall", "structhydra_1_1GaussKronrodCall.html", "structhydra_1_1GaussKronrodCall" ],
      [ "GaussKronrodUnary", "structhydra_1_1GaussKronrodUnary.html", "structhydra_1_1GaussKronrodUnary" ]
    ] ],
    [ "ProcessGenzMalikQuadrature.h", "ProcessGenzMalikQuadrature_8h.html", null ],
    [ "ProcessSPlot.h", "ProcessSPlot_8h.html", null ],
    [ "Random.h", "Random_8h.html", null ],
    [ "Random.inl", "Random_8inl.html", "Random_8inl" ],
    [ "RandomUtils.h", "RandomUtils_8h.html", null ],
    [ "sample_distribution.cpp", "sample__distribution_8cpp.html", null ],
    [ "sample_distribution.cu", "sample__distribution_8cu.html", null ],
    [ "sample_distribution.inl", "sample__distribution_8inl.html", "sample__distribution_8inl" ],
    [ "sparse_histogram.cpp", "sparse__histogram_8cpp.html", null ],
    [ "sparse_histogram.cu", "sparse__histogram_8cu.html", null ],
    [ "sparse_histogram.inl", "sparse__histogram_8inl.html", "sparse__histogram_8inl" ],
    [ "SparseHistogram.h", "SparseHistogram_8h.html", [
      [ "SparseHistogram", "namespacehydra.html#classhydra_1_1SparseHistogram", null ]
    ] ],
    [ "SparseHistogram.inl", "SparseHistogram_8inl.html", "SparseHistogram_8inl" ],
    [ "splot.cpp", "splot_8cpp.html", null ],
    [ "splot.cu", "splot_8cu.html", null ],
    [ "SPlot.h", "SPlot_8h.html", "SPlot_8h" ],
    [ "splot.inl", "splot_8inl.html", "splot_8inl" ],
    [ "SPlot.inl", "SPlot_8inl.html", null ],
    [ "StatsPHSP.h", "StatsPHSP_8h.html", null ],
    [ "StreamSTL.h", "StreamSTL_8h.html", "StreamSTL_8h" ],
    [ "strided_iterator.h", "strided__iterator_8h.html", null ],
    [ "Sum.h", "Sum_8h.html", "Sum_8h" ],
    [ "cpp/System.h", "cpp_2System_8h.html", null ],
    [ "cuda/System.h", "cuda_2System_8h.html", null ],
    [ "device/System.h", "device_2System_8h.html", null ],
    [ "host/System.h", "host_2System_8h.html", null ],
    [ "omp/System.h", "omp_2System_8h.html", null ],
    [ "tbb/System.h", "tbb_2System_8h.html", null ],
    [ "TBB.h", "TBB_8h.html", "TBB_8h" ],
    [ "Tuple.h", "Tuple_8h.html", "Tuple_8h" ],
    [ "Types.h", "Types_8h.html", "Types_8h" ],
    [ "TypeTraits.h", "TypeTraits_8h.html", [
      [ "common_type< HYDRA_EXTERNAL_NS::thrust::complex< T >, HYDRA_EXTERNAL_NS::thrust::complex< U > >", "structstd_1_1common__type_3_01HYDRA__EXTERNAL__NS_1_1thrust_1_1complex_3_01T_01_4_00_01HYDRA__EX2b76386747226f7737885e2d05401eb5.html", "structstd_1_1common__type_3_01HYDRA__EXTERNAL__NS_1_1thrust_1_1complex_3_01T_01_4_00_01HYDRA__EX2b76386747226f7737885e2d05401eb5" ],
      [ "common_type< HYDRA_EXTERNAL_NS::thrust::complex< U >, T >", "structstd_1_1common__type_3_01HYDRA__EXTERNAL__NS_1_1thrust_1_1complex_3_01U_01_4_00_01T_01_4.html", "structstd_1_1common__type_3_01HYDRA__EXTERNAL__NS_1_1thrust_1_1complex_3_01U_01_4_00_01T_01_4" ],
      [ "common_type< T, HYDRA_EXTERNAL_NS::thrust::complex< U > >", "structstd_1_1common__type_3_01T_00_01HYDRA__EXTERNAL__NS_1_1thrust_1_1complex_3_01U_01_4_01_4.html", "structstd_1_1common__type_3_01T_00_01HYDRA__EXTERNAL__NS_1_1thrust_1_1complex_3_01U_01_4_01_4" ]
    ] ],
    [ "UserParameters.h", "UserParameters_8h.html", [
      [ "UserParameters", "classhydra_1_1UserParameters.html", "classhydra_1_1UserParameters" ]
    ] ],
    [ "Utility_Tuple.h", "Utility__Tuple_8h.html", null ],
    [ "Variant.h", "Variant_8h.html", null ],
    [ "variant_types.cpp", "variant__types_8cpp.html", null ],
    [ "variant_types.cu", "variant__types_8cu.html", null ],
    [ "variant_types.inl", "variant__types_8inl.html", "variant__types_8inl" ],
    [ "Vector3R.h", "Vector3R_8h.html", "Vector3R_8h" ],
    [ "Vector3R.inl", "Vector3R_8inl.html", "Vector3R_8inl" ],
    [ "Vector4R.h", "Vector4R_8h.html", "Vector4R_8h" ],
    [ "Vector4R.inl", "Vector4R_8inl.html", "Vector4R_8inl" ],
    [ "vegas.cpp", "vegas_8cpp.html", null ],
    [ "vegas.cu", "vegas_8cu.html", null ],
    [ "Vegas.h", "Vegas_8h.html", [
      [ "Vegas", "namespacehydra.html#classhydra_1_1Vegas", null ]
    ] ],
    [ "vegas.inl", "vegas_8inl.html", "vegas_8inl" ],
    [ "Vegas.inl", "Vegas_8inl.html", "Vegas_8inl" ],
    [ "VegasState.h", "VegasState_8h.html", "VegasState_8h" ],
    [ "VegasState.inl", "VegasState_8inl.html", "VegasState_8inl" ],
    [ "Weights.h", "Weights_8h.html", [
      [ "Weights", "namespacehydra.html#classhydra_1_1Weights", null ]
    ] ]
];