Hydra: hydra::strided_range< Iterator > Class Template Reference
hydra::strided_range< Iterator > Class Template Reference
Strided range iterator original code: https://github.com/thrust/thrust/blob/master/examples/strided_range.cu.
Classes
struct stride_functor
Public Types
typedef thrust::counting_iterator< difference_type > CountingIterator
typedef thrust::iterator_difference< Iterator >::type difference_type
typedef PermutationIterator iterator
type of the strided_range iterator
typedef thrust::permutation_iterator< Iterator, TransformIterator > PermutationIterator
typedef thrust::transform_iterator< stride_functor, CountingIterator > TransformIterator
Public Member Functions
strided_range (Iterator first, Iterator last, difference_type stride)
construct strided_range for the range [first,last)
iterator begin (void) const
iterator end (void) const
Protected Attributes
Iterator first
Iterator last
difference_type stride
Detailed Description
template<typename Iterator>
class hydra::strided_range< Iterator >
Definition at line 52 of file strided_iterator.h.
Member Typedef Documentation
template<typename Iterator > typedef thrust::counting_iterator<difference_type> hydra::strided_range< Iterator >::CountingIterator
Definition at line 75 of file strided_iterator.h.
template<typename Iterator > typedef thrust::iterator_difference<Iterator>::type hydra::strided_range< Iterator >::difference_type
Definition at line 56 of file strided_iterator.h.
template<typename Iterator > typedef PermutationIterator hydra::strided_range< Iterator >::iterator
Definition at line 80 of file strided_iterator.h.
template<typename Iterator > typedef thrust::permutation_iterator<Iterator, TransformIterator> hydra::strided_range< Iterator >::PermutationIterator
Definition at line 77 of file strided_iterator.h.
template<typename Iterator > typedef thrust::transform_iterator<stride_functor, CountingIterator> hydra::strided_range< Iterator >::TransformIterator
Definition at line 76 of file strided_iterator.h.
Constructor & Destructor Documentation
template<typename Iterator > hydra::strided_range< Iterator >::strided_range (Iterator first, Iterator last, difference_type stride) inline
Definition at line 83 of file strided_iterator.h.
Member Function Documentation
template<typename Iterator > iterator hydra::strided_range< Iterator >::begin (void) const inline
Definition at line 88 of file strided_iterator.h.
References hydra::strided_range< Iterator >::first, hydra::strided_range< Iterator >::stride_functor::stride, and hydra::strided_range< Iterator >::stride_functor::stride_functor().
Referenced by hydra::strided_range< Iterator >::end().
template<typename Iterator > iterator hydra::strided_range< Iterator >::end (void) const inline
Definition at line 94 of file strided_iterator.h.
References hydra::strided_range< Iterator >::begin(), hydra::strided_range< Iterator >::first, hydra::strided_range< Iterator >::last, and hydra::strided_range< Iterator >::stride_functor::stride.
Member Data Documentation
template<typename Iterator > Iterator hydra::strided_range< Iterator >::first protected
Definition at line 100 of file strided_iterator.h.
Referenced by hydra::strided_range< Iterator >::begin(), and hydra::strided_range< Iterator >::end().
template<typename Iterator > Iterator hydra::strided_range< Iterator >::last protected
Definition at line 101 of file strided_iterator.h.
Referenced by hydra::strided_range< Iterator >::end().
template<typename Iterator > difference_type hydra::strided_range< Iterator >::stride protected
Definition at line 102 of file strided_iterator.h.
The documentation for this class was generated from the following file:
strided_iterator.h