Hydra: hydra::Vegas< N, GRND > Class Template Reference
hydra::Vegas< N, GRND > Class Template Reference
Public Member Functions
Vegas ()=delete
Vegas (std::array< GReal_t, N > const &xlower, std::array< GReal_t, N > const &xupper, size_t calls)
Vegas ctor taking the region of integration and the number of calls Look the documentation of VegasState to see the state parameters initialization.
Vegas (VegasState< N > const &state, size_t calls)
Vegas ctor taking a VegasState object and the number of calls Look the documentation of VegasState to see how to set the state parameters.
template<typename GRND2 >
Vegas (Vegas< N, GRND2 > const &other)
Vegas copy-ctor.
GReal_t GetAbsError () const
__host__ const GReal_t * GetLowerLimit () const
size_t GetNCalls () const
GReal_t GetResult () const
VegasState< N > & GetState ()
__host__ const GReal_t * GetUpperLimit () const
template<typename FUNCTOR >
GInt_t Integrate (FUNCTOR const &functor, GBool_t reset=kTrue)
Integrate the functor in the volume defined in construction time.
void PrintDistribution () const
void PrintGrid () const
void PrintHead () const
void PrintLimits () const
void PrintResults (GReal_t integral, GReal_t sigma, GReal_t cumulated_integral, GReal_t cumulated_sigma, GReal_t time) const
void SetAbsError (GReal_t absError)
void SetNCalls (size_t nCalls)
void SetResult (GReal_t result)
void SetState (const VegasState< N > *state)
Public Member Functions inherited from hydra::Integrator< Vegas< N, GRND >, N >
Integrator ()
__host__ thrust::pair< GReal_t, GReal_t > GetIntegral (FUNCTOR const &fFunctor)
__host__ thrust::pair< const GReal_t *, const GReal_t * > GetLimits ()
Additional Inherited Members
Public Types inherited from hydra::Integrator< Vegas< N, GRND >, N >
typedef void hydra_integrator_tag
Static Public Attributes inherited from hydra::Integrator< Vegas< N, GRND >, N >
static const size_t dimension
Detailed Description
template<size_t N, typename GRND = thrust::random::default_random_engine>
class hydra::Vegas< N, GRND >
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 54 of file Vegas.h.
Constructor & Destructor Documentation
template<size_t N, typename GRND = thrust::random::default_random_engine> hydra::Vegas< N, GRND >::Vegas () delete
template<size_t N, typename GRND = thrust::random::default_random_engine> hydra::Vegas< N, GRND >::Vegas (std::array< GReal_t, N > const & xlower, std::array< GReal_t, N > const & xupper, size_t calls)
template<size_t N, typename GRND = thrust::random::default_random_engine> hydra::Vegas< N, GRND >::Vegas (VegasState< N > const & state, size_t calls)
template<size_t N, typename GRND = thrust::random::default_random_engine> template<typename GRND2 > hydra::Vegas< N, GRND >::Vegas (Vegas< N, GRND2 > const & other) inline
Definition at line 76 of file Vegas.h.
References hydra::Vegas< N, GRND >::Integrate(), hydra::kTrue, hydra::Vegas< N, GRND >::PrintDistribution(), hydra::Vegas< N, GRND >::PrintGrid(), hydra::Vegas< N, GRND >::PrintHead(), hydra::Vegas< N, GRND >::PrintLimits(), and hydra::Vegas< N, GRND >::PrintResults().
Member Function Documentation
template<size_t N, typename GRND = thrust::random::default_random_engine> GReal_t hydra::Vegas< N, GRND >::GetAbsError () const inline
Definition at line 99 of file Vegas.h.
Referenced by main().
template<size_t N, typename GRND = thrust::random::default_random_engine> __host__ const GReal_t* hydra::Vegas< N, GRND >::GetLowerLimit () const inline
Definition at line 133 of file Vegas.h.
template<size_t N, typename GRND = thrust::random::default_random_engine> size_t hydra::Vegas< N, GRND >::GetNCalls () const inline
Definition at line 107 of file Vegas.h.
template<size_t N, typename GRND = thrust::random::default_random_engine> GReal_t hydra::Vegas< N, GRND >::GetResult () const inline
Definition at line 116 of file Vegas.h.
Referenced by main().
template<size_t N, typename GRND = thrust::random::default_random_engine> VegasState<N>& hydra::Vegas< N, GRND >::GetState () inline
Definition at line 124 of file Vegas.h.
Referenced by main().
template<size_t N, typename GRND = thrust::random::default_random_engine> __host__ const GReal_t* hydra::Vegas< N, GRND >::GetUpperLimit () const inline
Definition at line 138 of file Vegas.h.
template<size_t N, typename GRND = thrust::random::default_random_engine> template<typename FUNCTOR > GInt_t hydra::Vegas< N, GRND >::Integrate (FUNCTOR const & functor, GBool_t reset = kTrue)
Parameters
functor integrand.
reset reset the integrator state between calls, it is the desiderable behavior of the integrator in during fits.
Referenced by main(), and hydra::Vegas< N, GRND >::Vegas().
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::PrintDistribution () const
Referenced by hydra::Vegas< N, GRND >::Vegas().
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::PrintGrid () const
Referenced by hydra::Vegas< N, GRND >::Vegas().
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::PrintHead () const
Referenced by hydra::Vegas< N, GRND >::Vegas().
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::PrintLimits () const
Referenced by hydra::Vegas< N, GRND >::Vegas().
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::PrintResults (GReal_t integral, GReal_t sigma, GReal_t cumulated_integral, GReal_t cumulated_sigma, GReal_t time) const
Referenced by hydra::Vegas< N, GRND >::Vegas().
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::SetAbsError (GReal_t absError) inline
Definition at line 103 of file Vegas.h.
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::SetNCalls (size_t nCalls) inline
Definition at line 111 of file Vegas.h.
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::SetResult (GReal_t result) inline
Definition at line 120 of file Vegas.h.
template<size_t N, typename GRND = thrust::random::default_random_engine> void hydra::Vegas< N, GRND >::SetState (const VegasState< N > * state) inline
Definition at line 128 of file Vegas.h.
The documentation for this class was generated from the following file:
Vegas.h