Hydra: hydra::Compose< F0, F1, Fs > Struct Template Reference
hydra::Compose< F0, F1, Fs > Struct Template Reference
Public Types
typedef void hydra_functor_tag
typedef F0::return_type return_type
typedef thrust::tuple< typename F1::return_type, typename Fs::return_type... > argument_type
typedef thrust::tuple< F1, Fs... > functors_type
Public Member Functions
__host__ Compose ()
__host__ Compose (F0 const &f0, F1 const &f1, Fs const &...fs)
__host__ __device__ Compose (Compose< F0, F1, Fs... > const &other)
__host__ __device__ Compose< F0, F1, Fs... > & operator= (Compose< F0, F1, Fs... > const &other)
__host__ void SetParameters (const std::vector< double > &parameters)
__host__ __device__ functors_type GetFunctors () const
__host__ __device__ F0 GetF0 () const
__host__ __device__ int GetIndex () const
__host__ __device__ void SetIndex (int index)
__host__ __device__ bool IsCached () const
__host__ __device__ void SetCached (bool cached=true)
template<typename T1 >
__host__ __device__ return_type operator() (T1 &t)
template<typename T1 , typename T2 >
__host__ __device__ return_type operator() (T1 &t, T2 &cache)
Detailed Description
template<typename F0, typename F1, typename... Fs>
struct hydra::Compose< F0, F1, Fs >
Definition at line 46 of file Compose.h.
Member Typedef Documentation
template<typename F0, typename F1, typename... Fs> typedef thrust::tuple<typename F1::return_type, typename Fs::return_type...> hydra::Compose< F0, F1, Fs >::argument_type
Definition at line 52 of file Compose.h.
template<typename F0, typename F1, typename... Fs> typedef thrust::tuple<F1, Fs...> hydra::Compose< F0, F1, Fs >::functors_type
Definition at line 53 of file Compose.h.
template<typename F0, typename F1, typename... Fs> typedef void hydra::Compose< F0, F1, Fs >::hydra_functor_tag
Definition at line 49 of file Compose.h.
template<typename F0, typename F1, typename... Fs> typedef F0::return_type hydra::Compose< F0, F1, Fs >::return_type
Definition at line 51 of file Compose.h.
Constructor & Destructor Documentation
template<typename F0, typename F1, typename... Fs> __host__ hydra::Compose< F0, F1, Fs >::Compose () inline
Definition at line 56 of file Compose.h.
template<typename F0, typename F1, typename... Fs> __host__ hydra::Compose< F0, F1, Fs >::Compose (F0 const & f0, F1 const & f1, Fs const &... fs) inline
Definition at line 62 of file Compose.h.
template<typename F0, typename F1, typename... Fs> __host__ __device__ hydra::Compose< F0, F1, Fs >::Compose (Compose< F0, F1, Fs... > const & other) inline
Definition at line 70 of file Compose.h.
Member Function Documentation
template<typename F0, typename F1, typename... Fs> __host__ __device__ F0 hydra::Compose< F0, F1, Fs >::GetF0 () const inline
Definition at line 100 of file Compose.h.
Referenced by hydra::Compose< F0, F1, Fs >::operator=().
template<typename F0, typename F1, typename... Fs> __host__ __device__ functors_type hydra::Compose< F0, F1, Fs >::GetFunctors () const inline
Definition at line 97 of file Compose.h.
Referenced by hydra::Compose< F0, F1, Fs >::operator=().
template<typename F0, typename F1, typename... Fs> __host__ __device__ int hydra::Compose< F0, F1, Fs >::GetIndex () const inline
Definition at line 103 of file Compose.h.
Referenced by hydra::Compose< F0, F1, Fs >::operator=().
template<typename F0, typename F1, typename... Fs> __host__ __device__ bool hydra::Compose< F0, F1, Fs >::IsCached () const inline
Definition at line 109 of file Compose.h.
Referenced by hydra::Compose< F0, F1, Fs >::operator=().
template<typename F0, typename F1, typename... Fs> template<typename T1 > __host__ __device__ return_type hydra::Compose< F0, F1, Fs >::operator() (T1 & t) inline
Definition at line 119 of file Compose.h.
template<typename F0, typename F1, typename... Fs> template<typename T1 , typename T2 > __host__ __device__ return_type hydra::Compose< F0, F1, Fs >::operator() (T1 & t, T2 & cache) inline
Definition at line 126 of file Compose.h.
template<typename F0, typename F1, typename... Fs> __host__ __device__ Compose<F0,F1,Fs...>& hydra::Compose< F0, F1, Fs >::operator= (Compose< F0, F1, Fs... > const & other) inline
Definition at line 78 of file Compose.h.
References hydra::Compose< F0, F1, Fs >::GetF0(), hydra::Compose< F0, F1, Fs >::GetFunctors(), hydra::Compose< F0, F1, Fs >::GetIndex(), and hydra::Compose< F0, F1, Fs >::IsCached().
template<typename F0, typename F1, typename... Fs> __host__ __device__ void hydra::Compose< F0, F1, Fs >::SetCached (bool cached = true) inline
Definition at line 113 of file Compose.h.
template<typename F0, typename F1, typename... Fs> __host__ __device__ void hydra::Compose< F0, F1, Fs >::SetIndex (int index) inline
Definition at line 106 of file Compose.h.
template<typename F0, typename F1, typename... Fs> __host__ void hydra::Compose< F0, F1, Fs >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 90 of file Compose.h.
The documentation for this struct was generated from the following file:
Compose.h