Hydra: hydra::Vector3R Class Reference
hydra::Vector3R Class Reference
Public Member Functions
__host__ __device__ Vector3R ()
__host__ __device__ Vector3R (GReal_t x, GReal_t y, GReal_t z)
__host__ __device__ Vector3R (const Vector3R &other)
__host__ __device__ void applyRotateEuler (GReal_t phi, GReal_t theta, GReal_t ksi)
__host__ __device__ GReal_t d3mag () const
__host__ __device__ GReal_t dot (const Vector3R &v2)
__host__ __device__ GReal_t get (GInt_t i) const
__host__ __device__ Vector3R & operator*= (const GReal_t c)
__host__ __device__ Vector3R & operator+= (const Vector3R &v2)
__host__ __device__ Vector3R & operator-= (const Vector3R &v2)
__host__ __device__ Vector3R & operator/= (const GReal_t c)
__host__ __device__ void set (GInt_t i, GReal_t d)
__host__ __device__ void set (GReal_t x, GReal_t y, GReal_t z)
Friends
__host__ __device__ friend Vector3R cross (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator* (GReal_t c, const Vector3R &v2)
__host__ __device__ friend GReal_t operator* (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator* (const Vector3R &v1, GReal_t c)
__host__ __device__ friend Vector3R operator+ (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator- (const Vector3R &v1, const Vector3R &v2)
__host__ __device__ friend Vector3R operator/ (const Vector3R &v1, GReal_t c)
__host__ friend std::ostream & operator<< (std::ostream &s, const Vector3R &v)
__host__ __device__ friend Vector3R rotateEuler (const Vector3R &v, GReal_t phi, GReal_t theta, GReal_t ksi)
Detailed Description
Definition at line 52 of file Vector3R.h.
Constructor & Destructor Documentation
__host__ __device__ hydra::Vector3R::Vector3R () inline
Referenced by hydra::cross(), hydra::operator*(), hydra::operator+(), hydra::operator-(), and hydra::operator/().
__host__ __device__ hydra::Vector3R::Vector3R (GReal_t x, GReal_t y, GReal_t z) inline
__host__ __device__ hydra::Vector3R::Vector3R (const Vector3R & other) inline
Member Function Documentation
__host__ __device__ void hydra::Vector3R::applyRotateEuler (GReal_t phi, GReal_t theta, GReal_t ksi) inline
__host__ __device__ GReal_t hydra::Vector3R::d3mag () const inline
__host__ __device__ GReal_t hydra::Vector3R::dot (const Vector3R & v2) inline
__host__ __device__ GReal_t hydra::Vector3R::get (GInt_t i) const inline
__host__ __device__ Vector3R& hydra::Vector3R::operator*= (const GReal_t c) inline
__host__ __device__ Vector3R& hydra::Vector3R::operator+= (const Vector3R & v2) inline
__host__ __device__ Vector3R& hydra::Vector3R::operator-= (const Vector3R & v2) inline
__host__ __device__ Vector3R& hydra::Vector3R::operator/= (const GReal_t c) inline
__host__ __device__ void hydra::Vector3R::set (GInt_t i, GReal_t d) inline
__host__ __device__ void hydra::Vector3R::set (GReal_t x, GReal_t y, GReal_t z) inline
Friends And Related Function Documentation
__host__ __device__ friend Vector3R cross (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 147 of file Vector3R.h.
__host__ __device__ friend Vector3R operator* (GReal_t c, const Vector3R & v2) friend
Definition at line 100 of file Vector3R.h.
__host__ __device__ friend GReal_t operator* (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 118 of file Vector3R.h.
__host__ __device__ friend Vector3R operator* (const Vector3R & v1, GReal_t c) friend
Definition at line 106 of file Vector3R.h.
__host__ __device__ friend Vector3R operator+ (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 124 of file Vector3R.h.
__host__ __device__ friend Vector3R operator- (const Vector3R & v1, const Vector3R & v2) friend
Definition at line 130 of file Vector3R.h.
__host__ __device__ friend Vector3R operator/ (const Vector3R & v1, GReal_t c) friend
Definition at line 112 of file Vector3R.h.
__host__ friend std::ostream& operator<< (std::ostream & s, const Vector3R & v) friend
Definition at line 138 of file Vector3R.h.
__host__ __device__ friend Vector3R rotateEuler (const Vector3R & v, GReal_t phi, GReal_t theta, GReal_t ksi) friend
The documentation for this class was generated from the following file:
Vector3R.h