Hydra: hydra::Multiply< F1, F2, Fs > Struct Template Reference
hydra::Multiply< F1, F2, Fs > Struct Template Reference
Public Types
typedef thrust::tuple< F1, F2, Fs... > functors_type
typedef void hydra_functor_tag
typedef std::true_type is_functor
typedef detail::multiply_result< typename F1::return_type,typename F2::return_type, typename Fs::return_type... >::type return_type
Public Member Functions
__host__ Multiply ()
__host__ Multiply (F1 const &f1, F2 const &f2, Fs const &...functors)
__host__ __device__ Multiply (const Multiply< F1, F2, Fs... > &other)
__host__ __device__ functors_type GetFunctors () const
__host__ __device__ int GetIndex () const
__host__ __device__ bool IsCached () const
template<typename T1 >
__host__ __device__ return_type operator() (T1 &t)
template<typename T1 , typename T2 >
__host__ __device__ return_type operator() (T1 &t, T2 &cache)
__host__ __device__ Multiply< F1, F2, Fs... > & operator= (Multiply< F1, F2, Fs... > const &other)
__host__ void PrintRegisteredParameters ()
__host__ __device__ void SetCached (bool cached=1)
__host__ __device__ void SetIndex (int index)
__host__ void SetParameters (const std::vector< double > &parameters)
Detailed Description
template<typename F1, typename F2, typename... Fs>
struct hydra::Multiply< F1, F2, Fs >
Definition at line 57 of file Multiply.h.
Member Typedef Documentation
template<typename F1, typename F2, typename... Fs> typedef thrust::tuple<F1, F2, Fs...> hydra::Multiply< F1, F2, Fs >::functors_type
Definition at line 63 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> typedef void hydra::Multiply< F1, F2, Fs >::hydra_functor_tag
Definition at line 60 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> typedef std::true_type hydra::Multiply< F1, F2, Fs >::is_functor
Definition at line 61 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> typedef detail::multiply_result<typename F1::return_type ,typename F2::return_type,typename Fs::return_type...>::type hydra::Multiply< F1, F2, Fs >::return_type
Definition at line 62 of file Multiply.h.
Constructor & Destructor Documentation
template<typename F1, typename F2, typename... Fs> __host__ hydra::Multiply< F1, F2, Fs >::Multiply () inline
Definition at line 66 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> __host__ hydra::Multiply< F1, F2, Fs >::Multiply (F1 const & f1, F2 const & f2, Fs const &... functors) inline
Definition at line 72 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> __host__ __device__ hydra::Multiply< F1, F2, Fs >::Multiply (const Multiply< F1, F2, Fs... > & other) inline
Definition at line 79 of file Multiply.h.
Member Function Documentation
template<typename F1, typename F2, typename... Fs> __host__ __device__ functors_type hydra::Multiply< F1, F2, Fs >::GetFunctors () const inline
Definition at line 113 of file Multiply.h.
Referenced by hydra::Multiply< F1, F2, Fs >::operator=().
template<typename F1, typename F2, typename... Fs> __host__ __device__ int hydra::Multiply< F1, F2, Fs >::GetIndex () const inline
Definition at line 116 of file Multiply.h.
Referenced by hydra::Multiply< F1, F2, Fs >::operator=().
template<typename F1, typename F2, typename... Fs> __host__ __device__ bool hydra::Multiply< F1, F2, Fs >::IsCached () const inline
Definition at line 122 of file Multiply.h.
Referenced by hydra::Multiply< F1, F2, Fs >::operator=().
template<typename F1, typename F2, typename... Fs> template<typename T1 > __host__ __device__ return_type hydra::Multiply< F1, F2, Fs >::operator() (T1 & t) inline
Definition at line 132 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> template<typename T1 , typename T2 > __host__ __device__ return_type hydra::Multiply< F1, F2, Fs >::operator() (T1 & t, T2 & cache) inline
Definition at line 140 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> __host__ __device__ Multiply<F1,F2, Fs...>& hydra::Multiply< F1, F2, Fs >::operator= (Multiply< F1, F2, Fs... > const & other) inline
Definition at line 86 of file Multiply.h.
References hydra::Multiply< F1, F2, Fs >::GetFunctors(), hydra::Multiply< F1, F2, Fs >::GetIndex(), and hydra::Multiply< F1, F2, Fs >::IsCached().
template<typename F1, typename F2, typename... Fs> __host__ void hydra::Multiply< F1, F2, Fs >::PrintRegisteredParameters () inline
Definition at line 103 of file Multiply.h.
References HYDRA_CALLER, HYDRA_ENDL, and HYDRA_MSG.
template<typename F1, typename F2, typename... Fs> __host__ __device__ void hydra::Multiply< F1, F2, Fs >::SetCached (bool cached = 1) inline
Definition at line 126 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> __host__ __device__ void hydra::Multiply< F1, F2, Fs >::SetIndex (int index) inline
Definition at line 119 of file Multiply.h.
template<typename F1, typename F2, typename... Fs> __host__ void hydra::Multiply< F1, F2, Fs >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 97 of file Multiply.h.
The documentation for this struct was generated from the following file:
Multiply.h