Hydra: hydra Namespace Reference
hydra Namespace Reference
Classes
struct AddPdf
Build a pdf adding other pdfs.
struct Argument
struct BaseFunctor
struct Compose
struct Constant
struct Divide
struct EvalReturnType
struct Events
Events is a container struct to hold all the information corresponding the generated events.
class FCN
struct Integrator
struct LambdaWrapper
struct LambdaWrapper< ReturnType(ArgType), L >
class LogLikelihoodFCN
struct Minus
struct Multiply
struct null_type
struct Parameter
struct Pdf
class PhaseSpace
class Plain
struct PlainState
struct Point
struct PointError
PointError add symmetric error to data points, just in case someone comes to need of it PointError is base class for Point and provides conditional methods and members to save space in device memory.
struct PointError< T, N, true >
class PointVector
PointVector wraps a thrust::vector<Points<T,N>> and provide methods.
class Print
class Random
struct Range
Range helper class to use with hydra::Eval.
class strided_range
Strided range iterator original code: https://github.com/thrust/thrust/blob/master/examples/strided_range.cu.
struct Sum
class UserParameters
struct ValueError
Value error to be interpreted as error on bin content or point weight depending on the case.
struct ValueError< T, true >
class Vector3R
class Vector4R
class Vegas
class VegasState
Typedefs
typedef mc_device_vector< GBool_t > BoolVector_d
typedef mc_host_vector< GBool_t > BoolVector_h
Vector3R host vector.
typedef mc_device_vector< GComplex_t > ComplexVector_d
Typedef for a GReal_t device vector.
typedef mc_host_vector< GComplex_t > ComplexVector_h
Typedef for a GReal_t host vector.
typedef mc_host_vector< Vector4R > FourVectors_h
Typedef for complex number.
typedef bool GBool_t
Boolean (0=false, 1=true) (bool)
typedef unsigned char GByte_t
Byte (8 bits) (unsigned char)
typedef char GChar_t
Signed Character 1 byte (char)
typedef thrust::complex< GReal_t > GComplex_t
typedef double GDouble_t
Double 8 bytes.
typedef float GFloat_t
Float 4 bytes (float)
typedef int GInt_t
Signed integer 4 bytes (int)
typedef long long GLong64_t
Portable signed long integer 8 bytes.
typedef long GLong_t
Signed long integer 4 bytes (long)
typedef long double GLongDouble_t
Long Double.
typedef double GReal_t
Double 8 bytes or float 4 bytes.
typedef short GShort_t
Signed Short integer 2 bytes (short)
typedef char GText_t
General string (char)
typedef unsigned char GUChar_t
Unsigned Character 1 byte (unsigned char)
typedef unsigned int GUInt_t
Unsigned integer 4 bytes (unsigned int)
typedef unsigned long long GULong64_t
Portable unsigned long integer 8 bytes.
typedef unsigned long GULong_t
typedef unsigned short GUShort_t
Unsigned Short integer 2 bytes (unsigned short)
template<typename T >
using mc_device_vector = thrust::device_vector< T >
Generic template typedef for thrust::host_vector.
template<typename T >
using mc_host_vector = thrust::host_vector< T, thrust::system::cuda::experimental::pinned_allocator< T >>
Generic template typedef for thrust::host_vector.
typedef mc_device_vector< Vector4R > Particles_d
Typedef for a GComplex_t device vector.
typedef mc_host_vector< Vector4R > Particles_h
Typedef for a GComplex_t host vector.
template<size_t N>
using ParticlesSet_d = std::array< Particles_d *, N >
Typedef for a Vector4R device vector.
template<int N>
using ParticlesSet_h = std::array< Particles_h *, N >
Typedef for a Vector4R host vector.
typedef mc_device_vector< GReal_t > RealVector_d
Typedef for a GBool_t device vector.
typedef mc_host_vector< GReal_t > RealVector_h
Typedef for a GBool_t host vector.
typedef mc_host_vector< Vector3R > ThreeVectors_h
Vector4R host vector.
template<size_t N>
using VariableSet_d = std::array< RealVector_d *, N >
template<int N>
using VariableSet_h = std::array< RealVector_h *, N >
Enumerations
enum { INFO =0, WARNING =1, ERROR =2 }
enum { device =1, host =0 }
enum { MODE_IMPORTANCE = 1, MODE_IMPORTANCE_ONLY = 0, MODE_STRATIFIED = -1, BINS_MAX = 50 }
Functions
template<size_t N, typename PDF1 , typename PDF2 , typename... PDFs>
AddPdf< PDF1, PDF2, PDFs... > add_pdfs (std::array< Parameter *, N > var_list, PDF1 const &pdf1, PDF2 const &pdf2, PDFs const &...pdfs)
Convenience function to add pdfs without set template parameters explicitly.
__host__ __device__ Vector4R boostTo (const Vector4R &rs, const Vector4R &p4, bool inverse=false)
__host__ __device__ Vector4R boostTo (const Vector4R &rs, const Vector3R &boost, bool inverse=false)
template<typename T0 , typename T1 , typename... Ts, typename = typename std::enable_if< detail::all_true<T0::is_functor::value, T1::is_functor::value,Ts::is_functor::value...>::value >::type>
__host__ Compose< T0, T1, Ts... > compose (T0 const &F0, T1 const &F1, Ts const &...Fs)
__host__ __device__ Vector3R cross (const Vector3R &p1, const Vector3R &p2)
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>::type>
__host__ Divide< T1, T2 > divide (T1 const &F1, T1 const &F2)
template<typename Iterator , typename... Iterators, typename Functor , typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0>
auto Eval (Functor const &t, Range< Iterator >const &range, Range< Iterators >const &...ranges) -> typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, mc_device_vector< typename Functor::return_type >, mc_host_vector< typename Functor::return_type >>::type
template<typename Iterator , typename... Iterators, typename... Functors, typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0>
auto Eval (thrust::tuple< Functors... > const &t, Range< Iterator >const &range, Range< Iterators >const &...ranges) -> typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, typename EvalReturnType< mc_device_vector, typename Functors::return_type... >::type, typename EvalReturnType< mc_host_vector, typename Functors::return_type... >::type >::type
template<typename Tuple , typename Iterator , typename... Iterators, typename Functor , typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0>
auto Eval (Functor const &t, typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, mc_device_vector< Tuple >, mc_host_vector< Tuple >> const &Cache, Range< Iterator >const &range, Range< Iterators >const &...ranges) -> typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, typename EvalReturnType< mc_device_vector, typename Functor::return_type >::type, typename EvalReturnType< mc_host_vector, typename Functor::return_type >::type >::type
template<typename Tuple , typename Iterator , typename... Iterators, typename... Functors, typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0>
auto Eval (thrust::tuple< Functors... > const &t, typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, mc_device_vector< Tuple >, mc_host_vector< Tuple >> const &Cache, Range< Iterator >const &range, Range< Iterators >const &...ranges) -> typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, typename EvalReturnType< mc_device_vector, typename Functors::return_type... >::type, typename EvalReturnType< mc_host_vector, typename Functors::return_type... >::type >::type
template<unsigned int BACKEND, template< typename... > class CONTAINER, typename T , typename... Ts>
auto get_copy (CONTAINER< T, Ts... > &other) -> typename std::enable_if< detail::is_specialization< CONTAINER< T, Ts... >, thrust::host_vector >::value||detail::is_specialization< CONTAINER< T, Ts... >, thrust::device_vector >::value||detail::is_specialization< CONTAINER< T, Ts... >, std::vector >::value, typename detail::copy_type< CONTAINER, T, BACKEND >::type >::type
template<typename FUNCTOR , typename IteratorData >
LogLikelihoodFCN< FUNCTOR, IteratorData, thrust::constant_iterator< null_type > > make_loglikehood_fcn (FUNCTOR &functor, IteratorData begin, IteratorData end)
template<typename FUNCTOR , typename IteratorData , typename IteratorCache >
LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > make_loglikehood_fcn (FUNCTOR &functor, IteratorData begin, IteratorData end, IteratorCache cache)
template<typename FUNCTOR , typename INTEGRATOR >
Pdf< FUNCTOR, INTEGRATOR > make_pdf (FUNCTOR const &functor, INTEGRATOR *integrator)
template<typename Iterator >
Range< Iterator > make_range (Iterator begin, Iterator end)
template<typename Iterator >
Range< Iterator > make_range (Iterator begin, size_t n)
template<typename T >
Range< typename T::iterator > make_range (T const &container)
template<typename T >
Range< typename T::iterator > make_range (T const &container, size_t n)
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>::type>
__host__ __device__ Minus< T1, T2 > minus (T1 const &F1, T1 const &F2)
template<typename F1 , typename F2 , typename... Fs>
__host__ Multiply< F1, F2, Fs... > multiply (F1 const &f1, F2 const &f2, Fs const &...functors)
__host__ __device__ Vector3R operator* (GReal_t c, const Vector3R &v2)
__host__ __device__ Vector3R operator* (const Vector3R &v1, GReal_t c)
__host__ __device__ GReal_t operator* (const Vector3R &v1, const Vector3R &v2)
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>::type>
__host__ Multiply< T1, T2 > operator* (T1 const &F1, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Multiply< Constant< T1 >, T2 > operator* (T1 const cte, T2 const &F2)
__host__ __device__ Vector4R operator* (GReal_t c, const Vector4R &v2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Multiply< Constant< T1 >, T2 > operator* (T2 const &F2, T1 const cte)
__host__ __device__ Vector4R operator* (const Vector4R &v2, GReal_t c)
__host__ __device__ GReal_t operator* (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ Parameter operator* (Parameter par1, Parameter const &par2)
template<typename... T>
__host__ __device__ thrust::tuple< T... > operator+ (const thrust::tuple< T... > &a, const thrust::tuple< T... > &b)
__host__ __device__ Vector3R operator+ (const Vector3R &v1, const Vector3R &v2)
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>>
__host__ Sum< T1, T2 > operator+ (T1 const &F1, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Sum< Constant< T1 >, T2 > operator+ (T1 const cte, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Sum< Constant< T1 >, T2 > operator+ (T2 const &F2, T1 const cte)
__host__ __device__ Vector4R operator+ (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ Parameter operator+ (Parameter par1, Parameter const &par2)
template<typename T , size_t N>
__host__ __device__ Point< T, N, false, false > operator+ (Point< T, N, false, false > const &point1, Point< T, N, false, false > const &point2)
__host__ __device__ Vector3R operator- (const Vector3R &v1, const Vector3R &v2)
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>>
__host__ Minus< T1, T2 > operator- (T1 const &F1, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Minus< Constant< T1 >, T2 > operator- (T1 const cte, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Minus< T2, Constant< T1 > > operator- (T2 const &F2, T1 const cte)
__host__ __device__ Vector4R operator- (const Vector4R &v1, const Vector4R &v2)
__host__ __device__ Parameter operator- (Parameter par1, Parameter const &par2)
__host__ __device__ Vector3R operator/ (const Vector3R &v1, GReal_t c)
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>>
__host__ Divide< T1, T2 > operator/ (T1 const &F1, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Divide< Constant< T1 >, T2 > operator/ (T1 const cte, T2 const &F2)
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type>
__host__ Divide< T2, Constant< T1 > > operator/ (T2 const &F2, T1 const cte)
__host__ __device__ Vector4R operator/ (const Vector4R &v2, GReal_t c)
__host__ __device__ Parameter operator/ (Parameter par1, Parameter const &par2)
ostream & operator<< (ostream &s, const Vector3R &v)
__host__ std::ostream & operator<< (std::ostream &os, UserParameters const &par)
ostream & operator<< (ostream &s, const Vector4R &v)
__host__ std::ostream & operator<< (std::ostream &os, Parameter const &var)
template<typename T , size_t N>
__host__ std::ostream & operator<< (std::ostream &os, Point< T, N, false, false > const &point)
template<typename T , size_t N>
__host__ std::ostream & operator<< (std::ostream &os, Point< T, N, true, false > const &point)
template<typename T , size_t N>
__host__ std::ostream & operator<< (std::ostream &os, Point< T, N, true, true > const &point)
__host__ __device__ Vector4R rotateEuler (const Vector4R &rs, GReal_t alpha, GReal_t beta, GReal_t gamma)
template<typename F1 , typename F2 , typename... Fs>
__host__ Sum< F1, F2, Fs... > sum (F1 const &f1, F2 const &f2, Fs const &...functors)
template<typename L >
auto wrap_lambda (L const &f) -> decltype(detail::wrap_lambda_helper(f, typename detail::function_traits< L >::return_type(), typename detail::function_traits< L >::args_type()))
Variables
const GBool_t kFalse = false
const GBool_t kTrue = true
int PrintLevel = WARNING
Class Documentation
struct hydra::EvalReturnType
template<template< class, class... > class V = mc_device_vector, typename... T>
struct hydra::EvalReturnType< V, T >
Definition at line 55 of file Evaluate.h.
Class Members
type
struct hydra::LambdaWrapper
template<typename Sig, typename L, typename = typename std::enable_if<std::is_constructible<std::function<Sig>, L>::value>::type>
struct hydra::LambdaWrapper< Sig, L, typename >
Examples:
HydraRandomExample.cpp, and HydraRandomExample.cu.
Definition at line 50 of file FunctionWrapper.h.
struct hydra::null_type
Definition at line 76 of file Types.h.
struct hydra::PointError
template<typename T, size_t N, bool>
struct hydra::PointError< T, N, bool >
Definition at line 111 of file Point.h.
Class Members
typedef tuple_type< N, T >::type type
typedef T value_type
struct hydra::ValueError
template<typename T, bool>
struct hydra::ValueError< T, bool >
ValueError is base class for Point and provides conditional methods and members to save space in device memory
Definition at line 61 of file Point.h.
Class Members
typedef ValueError< T, true > type
typedef T value_type
Typedef Documentation
typedef mc_device_vector<GBool_t> hydra::BoolVector_d
Definition at line 120 of file Containers.h.
typedef mc_host_vector<GBool_t> hydra::BoolVector_h
Use it to store four-vectors at host.
Definition at line 107 of file Containers.h.
typedef mc_device_vector<GComplex_t> hydra::ComplexVector_d
Definition at line 122 of file Containers.h.
typedef mc_host_vector<GComplex_t> hydra::ComplexVector_h
Definition at line 109 of file Containers.h.
typedef mc_host_vector<Vector4R> hydra::FourVectors_h
Definition at line 101 of file Containers.h.
typedef bool hydra::GBool_t
Definition at line 53 of file Types.h.
typedef unsigned char hydra::GByte_t
Definition at line 54 of file Types.h.
typedef char hydra::GChar_t
Definition at line 41 of file Types.h.
typedef thrust::complex<GReal_t> hydra::GComplex_t
Definition at line 97 of file Containers.h.
typedef double hydra::GDouble_t
Definition at line 50 of file Types.h.
typedef float hydra::GFloat_t
Definition at line 49 of file Types.h.
typedef int hydra::GInt_t
Definition at line 45 of file Types.h.
typedef long long hydra::GLong64_t
Definition at line 55 of file Types.h.
typedef long hydra::GLong_t
Definition at line 47 of file Types.h.
typedef long double hydra::GLongDouble_t
Definition at line 51 of file Types.h.
typedef double hydra::GReal_t
Examples:
HydraRandomExample.cpp, and HydraRandomExample.cu.
Definition at line 60 of file Types.h.
typedef short hydra::GShort_t
Definition at line 43 of file Types.h.
typedef char hydra::GText_t
Definition at line 52 of file Types.h.
typedef unsigned char hydra::GUChar_t
Definition at line 42 of file Types.h.
typedef unsigned int hydra::GUInt_t
Definition at line 46 of file Types.h.
typedef unsigned long long hydra::GULong64_t
Definition at line 56 of file Types.h.
typedef unsigned long hydra::GULong_t
Definition at line 48 of file Types.h.
typedef unsigned short hydra::GUShort_t
Definition at line 44 of file Types.h.
template<typename T > using hydra::mc_device_vector = typedef thrust::device_vector<T>
Use it instead of Thrust implementation in order to avoid problems to compile OpenMP based applications using gcc and without a cuda runtime installation.
Definition at line 68 of file Containers.h.
template<typename T > using hydra::mc_host_vector = typedef thrust::host_vector<T, thrust::system::cuda::experimental::pinned_allocator<T>>
Use it instead of Thrust implementation in order to avoid problems to compile OpenMP based applications using gcc and without a cuda runtime installation. mc_host_vectot will always allocate page locked memory on CUDA backends in order to maximize speed in memory transfers to the device.
Definition at line 76 of file Containers.h.
typedef mc_device_vector<Vector4R> hydra::Particles_d
Definition at line 123 of file Containers.h.
typedef mc_host_vector<Vector4R> hydra::Particles_h
Definition at line 110 of file Containers.h.
template<size_t N> using hydra::ParticlesSet_d = typedef std::array<Particles_d*, N>
Definition at line 126 of file Containers.h.
template<int N> using hydra::ParticlesSet_h = typedef std::array<Particles_h*, N>
Definition at line 113 of file Containers.h.
typedef mc_device_vector<GReal_t> hydra::RealVector_d
Definition at line 121 of file Containers.h.
typedef mc_host_vector<GReal_t> hydra::RealVector_h
Definition at line 108 of file Containers.h.
typedef mc_host_vector<Vector3R> hydra::ThreeVectors_h
Use it to store four-vectors at host.
Definition at line 102 of file Containers.h.
template<size_t N> using hydra::VariableSet_d = typedef std::array<RealVector_d*, N>
Definition at line 129 of file Containers.h.
template<int N> using hydra::VariableSet_h = typedef std::array<RealVector_h*, N>
Definition at line 116 of file Containers.h.
Enumeration Type Documentation
anonymous enum
Enumerator
INFO
WARNING
ERROR
Definition at line 41 of file Print.h.
anonymous enum
Enumerator
device
host
Definition at line 80 of file Types.h.
anonymous enum
Enumerator
MODE_IMPORTANCE
MODE_IMPORTANCE_ONLY
MODE_STRATIFIED
BINS_MAX
Definition at line 52 of file VegasState.h.
Function Documentation
template<size_t N, typename PDF1 , typename PDF2 , typename... PDFs> AddPdf<PDF1, PDF2, PDFs...> hydra::add_pdfs (std::array< Parameter *, N > var_list, PDF1 const & pdf1, PDF2 const & pdf2, PDFs const &... pdfs)
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 321 of file AddPdf.h.
Referenced by main().
__host__ __device__ Vector4R hydra::boostTo (const Vector4R & rs, const Vector4R & p4, bool inverse = false) inline
Definition at line 319 of file Vector4R.h.
References hydra::Vector4R::applyBoostTo().
__host__ __device__ Vector4R hydra::boostTo (const Vector4R & rs, const Vector3R & boost, bool inverse = false) inline
Definition at line 328 of file Vector4R.h.
References hydra::Vector4R::applyBoostTo().
template<typename T0 , typename T1 , typename... Ts, typename = typename std::enable_if< detail::all_true<T0::is_functor::value, T1::is_functor::value,Ts::is_functor::value...>::value >::type> __host__ Compose<T0,T1,Ts...> hydra::compose (T0 const & F0, T1 const & F1, Ts const &... Fs) inline
Definition at line 148 of file Compose.h.
__host__ __device__ Vector3R hydra::cross (const Vector3R & p1, const Vector3R & p2) inline
Definition at line 147 of file Vector3R.h.
References hydra::Vector3R::Vector3R().
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>::type> __host__ Divide<T1,T2> hydra::divide (T1 const & F1, T1 const & F2) inline
Definition at line 173 of file Divide.h.
template<typename Iterator , typename... Iterators, typename Functor , typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0> auto hydra::Eval (Functor const & t, Range< Iterator >const & range, Range< Iterators >const &... ranges) -> typename detail::if_then_else<std::is_same<thrust::device_system_tag,typename Range<Iterator>::system>::value, mc_device_vector<typename Functor::return_type>, mc_host_vector<typename Functor::return_type>>::type
Examples:
HydraEvaluateExample.cpp, HydraEvaluateExample.cu, HydraPhaseSpaceExample.cpp, and HydraPhaseSpaceExample.cu.
Definition at line 68 of file Evaluate.h.
Referenced by hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetFcnCache(), and main().
template<typename Iterator , typename... Iterators, typename... Functors, typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0> auto hydra::Eval (thrust::tuple< Functors... > const & t, Range< Iterator >const & range, Range< Iterators >const &... ranges) -> typename detail::if_then_else<std::is_same<thrust::device_system_tag,typename Range<Iterator>::system>::value, typename EvalReturnType<mc_device_vector,typename Functors::return_type ...>::type, typename EvalReturnType<mc_host_vector,typename Functors::return_type ...>::type>::type
Definition at line 93 of file Evaluate.h.
template<typename Tuple , typename Iterator , typename... Iterators, typename Functor , typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0> auto hydra::Eval (Functor const & t, typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, mc_device_vector< Tuple >, mc_host_vector< Tuple >> const & Cache, Range< Iterator >const & range, Range< Iterators >const &... ranges) -> typename detail::if_then_else<std::is_same<thrust::device_system_tag,typename Range<Iterator>::system>::value, typename EvalReturnType<mc_device_vector,typename Functor::return_type >::type, typename EvalReturnType<mc_host_vector,typename Functor::return_type >::type>::type
Definition at line 122 of file Evaluate.h.
template<typename Tuple , typename Iterator , typename... Iterators, typename... Functors, typename thrust::detail::enable_if< hydra::detail::are_all_same< typename Range< Iterator >::system, typename Range< Iterators >::system... >::value, int >::type = 0> auto hydra::Eval (thrust::tuple< Functors... > const & t, typename detail::if_then_else< std::is_same< thrust::device_system_tag, typename Range< Iterator >::system >::value, mc_device_vector< Tuple >, mc_host_vector< Tuple >> const & Cache, Range< Iterator >const & range, Range< Iterators >const &... ranges) -> typename detail::if_then_else<std::is_same<thrust::device_system_tag,typename Range<Iterator>::system>::value, typename EvalReturnType<mc_device_vector,typename Functors::return_type ...>::type, typename EvalReturnType<mc_host_vector,typename Functors::return_type ...>::type>::type
Definition at line 150 of file Evaluate.h.
template<unsigned int BACKEND, template< typename... > class CONTAINER, typename T , typename... Ts> auto hydra::get_copy (CONTAINER< T, Ts... > & other) -> typename std::enable_if< detail::is_specialization< CONTAINER<T, Ts...>, thrust::host_vector>::value || detail::is_specialization<CONTAINER<T, Ts...>, thrust::device_vector >::value || detail::is_specialization<CONTAINER<T, Ts...>, std::vector >::value, typename detail::copy_type<CONTAINER, T, BACKEND>::type >::type
Definition at line 62 of file Copy.h.
template<typename FUNCTOR , typename IteratorData > LogLikelihoodFCN<FUNCTOR, IteratorData, thrust::constant_iterator<null_type> > hydra::make_loglikehood_fcn (FUNCTOR & functor, IteratorData begin, IteratorData end)
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 216 of file LogLikelihoodFCN.h.
Referenced by main().
template<typename FUNCTOR , typename IteratorData , typename IteratorCache > LogLikelihoodFCN<FUNCTOR, IteratorData, IteratorCache> hydra::make_loglikehood_fcn (FUNCTOR & functor, IteratorData begin, IteratorData end, IteratorCache cache)
Definition at line 223 of file LogLikelihoodFCN.h.
template<typename FUNCTOR , typename INTEGRATOR > Pdf<FUNCTOR, INTEGRATOR > hydra::make_pdf (FUNCTOR const & functor, INTEGRATOR * integrator)
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 281 of file Pdf.h.
Referenced by main().
template<typename Iterator > Range<Iterator> hydra::make_range (Iterator begin, Iterator end)
Examples:
HydraEvaluateExample.cpp, HydraEvaluateExample.cu, HydraPhaseSpaceExample.cpp, and HydraPhaseSpaceExample.cu.
Definition at line 117 of file Range.h.
References hydra::Range< Iterator >::begin(), and hydra::Range< Iterator >::end().
Referenced by main().
template<typename Iterator > Range<Iterator> hydra::make_range (Iterator begin, size_t n)
Definition at line 121 of file Range.h.
References hydra::Range< Iterator >::begin().
template<typename T > Range<typename T::iterator> hydra::make_range (T const & container)
Definition at line 125 of file Range.h.
template<typename T > Range<typename T::iterator> hydra::make_range (T const & container, size_t n)
Definition at line 129 of file Range.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>::type> __host__ __device__ Minus<T1,T2> hydra::minus (T1 const & F1, T1 const & F2) inline
Definition at line 169 of file Minus.h.
template<typename F1 , typename F2 , typename... Fs> __host__ Multiply<F1,F2,Fs...> hydra::multiply (F1 const & f1, F2 const & f2, Fs const &... functors) inline
Definition at line 181 of file Multiply.h.
__host__ __device__ Vector3R hydra::operator* (GReal_t c, const Vector3R & v2) inline
Definition at line 100 of file Vector3R.h.
References hydra::Vector3R::Vector3R().
__host__ __device__ Vector3R hydra::operator* (const Vector3R & v1, GReal_t c) inline
Definition at line 106 of file Vector3R.h.
References hydra::Vector3R::Vector3R().
__host__ __device__ GReal_t hydra::operator* (const Vector3R & v1, const Vector3R & v2) inline
Definition at line 118 of file Vector3R.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>::type> __host__ Multiply<T1,T2> hydra::operator* (T1 const & F1, T2 const & F2) inline
Definition at line 159 of file Multiply.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Multiply<Constant<T1>, T2> hydra::operator* (T1 const cte, T2 const & F2) inline
Definition at line 166 of file Multiply.h.
__host__ __device__ Vector4R hydra::operator* (GReal_t c, const Vector4R & v2) inline
Definition at line 171 of file Vector4R.h.
References hydra::Vector4R::Vector4R().
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Multiply<Constant<T1>, T2> hydra::operator* (T2 const & F2, T1 const cte) inline
Definition at line 174 of file Multiply.h.
__host__ __device__ Vector4R hydra::operator* (const Vector4R & v2, GReal_t c) inline
Definition at line 177 of file Vector4R.h.
References hydra::Vector4R::Vector4R().
__host__ __device__ GReal_t hydra::operator* (const Vector4R & v1, const Vector4R & v2) inline
Definition at line 214 of file Vector4R.h.
__host__ __device__ Parameter hydra::operator* (Parameter par1, Parameter const & par2) inline
Definition at line 379 of file Parameter.h.
template<typename... T> __host__ __device__ thrust::tuple<T...> hydra::operator+ (const thrust::tuple< T... > & a, const thrust::tuple< T... > & b) inline
Definition at line 76 of file Arithmetic_Tuple.h.
__host__ __device__ Vector3R hydra::operator+ (const Vector3R & v1, const Vector3R & v2) inline
Definition at line 124 of file Vector3R.h.
References hydra::Vector3R::Vector3R().
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>> __host__ Sum<T1, T2> hydra::operator+ (T1 const & F1, T2 const & F2) inline
Definition at line 166 of file Sum.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Sum<Constant<T1>, T2> hydra::operator+ (T1 const cte, T2 const & F2) inline
Definition at line 173 of file Sum.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Sum<Constant<T1>, T2> hydra::operator+ (T2 const & F2, T1 const cte) inline
Definition at line 181 of file Sum.h.
__host__ __device__ Vector4R hydra::operator+ (const Vector4R & v1, const Vector4R & v2) inline
Definition at line 236 of file Vector4R.h.
References hydra::Vector4R::Vector4R().
__host__ __device__ Parameter hydra::operator+ (Parameter par1, Parameter const & par2) inline
Definition at line 363 of file Parameter.h.
template<typename T , size_t N> __host__ __device__ Point<T,N,false,false> hydra::operator+ (Point< T, N, false, false > const & point1, Point< T, N, false, false > const & point2) inline
Definition at line 493 of file Point.h.
References hydra::Point< T, N, HasValueError, HasPointError >::GetCoordinates(), hydra::Point< T, N, HasValueError, HasPointError >::GetWeight(), hydra::Point< T, N, HasValueError, HasPointError >::GetWeight2(), hydra::Point< T, N, HasValueError, HasPointError >::SetCoordinates(), hydra::Point< T, N, HasValueError, HasPointError >::SetWeight(), and hydra::Point< T, N, HasValueError, HasPointError >::SetWeight2().
__host__ __device__ Vector3R hydra::operator- (const Vector3R & v1, const Vector3R & v2) inline
Definition at line 130 of file Vector3R.h.
References hydra::Vector3R::Vector3R().
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>> __host__ Minus<T1,T2> hydra::operator- (T1 const & F1, T2 const & F2) inline
Definition at line 148 of file Minus.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Minus<Constant<T1>, T2> hydra::operator- (T1 const cte, T2 const & F2) inline
Definition at line 155 of file Minus.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Minus<T2,Constant<T1> > hydra::operator- (T2 const & F2, T1 const cte) inline
Definition at line 163 of file Minus.h.
__host__ __device__ Vector4R hydra::operator- (const Vector4R & v1, const Vector4R & v2) inline
Definition at line 230 of file Vector4R.h.
References hydra::Vector4R::Vector4R().
__host__ __device__ Parameter hydra::operator- (Parameter par1, Parameter const & par2) inline
Definition at line 371 of file Parameter.h.
__host__ __device__ Vector3R hydra::operator/ (const Vector3R & v1, GReal_t c) inline
Definition at line 112 of file Vector3R.h.
References hydra::Vector3R::Vector3R().
template<typename T1 , typename T2 , typename = typename std::enable_if< T1::is_functor::value && T2::is_functor::value>> __host__ Divide<T1,T2> hydra::operator/ (T1 const & F1, T2 const & F2) inline
Definition at line 148 of file Divide.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Divide<Constant<T1>, T2> hydra::operator/ (T1 const cte, T2 const & F2) inline
Definition at line 158 of file Divide.h.
template<typename T1 , typename T2 , typename = typename std::enable_if< (std::is_convertible<T1, double>::value || std::is_constructible<thrust::complex<double>,T1>::value) && T2::is_functor::value>::type> __host__ Divide<T2,Constant<T1> > hydra::operator/ (T2 const & F2, T1 const cte) inline
Definition at line 166 of file Divide.h.
__host__ __device__ Vector4R hydra::operator/ (const Vector4R & v2, GReal_t c) inline
Definition at line 183 of file Vector4R.h.
References hydra::Vector4R::Vector4R().
__host__ __device__ Parameter hydra::operator/ (Parameter par1, Parameter const & par2) inline
Definition at line 387 of file Parameter.h.
ostream& hydra::operator<< (std::ostream & s, const Vector3R & v) inline
Definition at line 138 of file Vector3R.h.
__host__ std::ostream& hydra::operator<< (std::ostream & os, UserParameters const & par)
Definition at line 199 of file UserParameters.h.
References hydra::UserParameters::GetState().
ostream& hydra::operator<< (std::ostream & s, const Vector4R & v) inline
Definition at line 361 of file Vector4R.h.
__host__ std::ostream& hydra::operator<< (std::ostream & os, Parameter const & var)
Definition at line 397 of file Parameter.h.
References hydra::Parameter::GetError(), hydra::Parameter::GetIndex(), hydra::Parameter::GetLowerLim(), hydra::Parameter::GetName(), hydra::Parameter::GetUpperLim(), and hydra::Parameter::GetValue().
template<typename T , size_t N> __host__ std::ostream& hydra::operator<< (std::ostream & os, Point< T, N, false, false > const & point)
Definition at line 513 of file Point.h.
References hydra::Point< T, N, HasValueError, HasPointError >::Dimension.
template<typename T , size_t N> __host__ std::ostream& hydra::operator<< (std::ostream & os, Point< T, N, true, false > const & point)
Definition at line 522 of file Point.h.
template<typename T , size_t N> __host__ std::ostream& hydra::operator<< (std::ostream & os, Point< T, N, true, true > const & point)
Definition at line 532 of file Point.h.
__host__ __device__ Vector4R hydra::rotateEuler (const Vector4R & rs, GReal_t alpha, GReal_t beta, GReal_t gamma) inline
Definition at line 309 of file Vector4R.h.
References hydra::Vector4R::applyRotateEuler().
template<typename F1 , typename F2 , typename... Fs> __host__ Sum<F1, F2,Fs...> hydra::sum (F1 const & f1, F2 const & f2, Fs const &... functors) inline
Definition at line 187 of file Sum.h.
template<typename L > auto hydra::wrap_lambda (L const & f) -> decltype(detail::wrap_lambda_helper(f, typename detail::function_traits<L>::return_type() , typename detail::function_traits<L>::args_type()))
Examples:
HydraEvaluateExample.cpp, HydraEvaluateExample.cu, HydraPhaseSpaceExample.cpp, and HydraPhaseSpaceExample.cu.
Definition at line 91 of file FunctionWrapper.h.
Referenced by main().
Variable Documentation
const GBool_t hydra::kFalse = false
Definition at line 70 of file Types.h.
const GBool_t hydra::kTrue = true
Definition at line 69 of file Types.h.
Referenced by hydra::Events< N, BACKEND >::Unweight(), and hydra::Vegas< N, GRND >::Vegas().
int hydra::PrintLevel = WARNING
Definition at line 48 of file Print.h.
Referenced by hydra::Print::Level(), and hydra::Print::SetLevel().