Hydra: hydra::AddPdf< PDF1, PDF2, PDFs > Struct Template Reference
hydra::AddPdf< PDF1, PDF2, PDFs > Struct Template Reference
Public Types
typedef void hydra_sum_pdf_tag
typedef detail::AddPdfBase< PDF1, PDF2, PDFs... >::type base_type
typedef thrust::tuple< PDF1, PDF2, PDFs... > pdfs_tuple_type
Public Member Functions
AddPdf (PDF1 const &pdf1, PDF2 const &pdf2, PDFs const &...pdfs, std::array< Parameter *, npdfs >const &coef, GBool_t extend=kTrue)
AddPdf (PDF1 const &pdf1, PDF2 const &pdf2, PDFs const &...pdfs, std::array< Parameter *, npdfs-1 >const &coef)
__host__ __device__ AddPdf (AddPdf< PDF1, PDF2, PDFs... > const &other)
__host__ __device__ AddPdf< PDF1, PDF2, PDFs... > & operator= (AddPdf< PDF1, PDF2, PDFs... > const &other)
__host__ void SetParameters (const std::vector< double > &parameters)
__host__ void PrintRegisteredParameters ()
__host__ __device__ const Parameter & GetCoeficient (size_t i) const
__host__ __device__ GBool_t IsExtended () const
__host__ __device__ const thrust::tuple< PDF1, PDF2, PDFs... > & GetPdFs () const
__host__ __device__ GReal_t GetCoefSum () const
__host__ __device__ GBool_t IsFractioned () const
template<typename T1 >
__host__ __device__ GReal_t operator() (T1 &&t)
template<typename T1 , typename T2 >
__host__ __device__ GReal_t operator() (T1 &&t, T2 &&cache)
template<typename T >
__host__ __device__ GReal_t operator() (T *x, T *p)
Static Public Attributes
static constexpr size_t npdfs = sizeof...(PDFs)+2
Detailed Description
template<typename PDF1, typename PDF2, typename... PDFs>
struct hydra::AddPdf< PDF1, PDF2, PDFs >
Definition at line 62 of file AddPdf.h.
Member Typedef Documentation
template<typename PDF1, typename PDF2, typename... PDFs> typedef detail::AddPdfBase<PDF1,PDF2,PDFs...>::type hydra::AddPdf< PDF1, PDF2, PDFs >::base_type
Definition at line 70 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> typedef void hydra::AddPdf< PDF1, PDF2, PDFs >::hydra_sum_pdf_tag
Definition at line 65 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> typedef thrust::tuple<PDF1, PDF2, PDFs...> hydra::AddPdf< PDF1, PDF2, PDFs >::pdfs_tuple_type
Definition at line 73 of file AddPdf.h.
Constructor & Destructor Documentation
template<typename PDF1, typename PDF2, typename... PDFs> hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf (PDF1 const & pdf1, PDF2 const & pdf2, PDFs const &... pdfs, std::array< Parameter *, npdfs >const & coef, GBool_t extend = kTrue) inline
Definition at line 76 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf (PDF1 const & pdf1, PDF2 const & pdf2, PDFs const &... pdfs, std::array< Parameter *, npdfs-1 >const & coef) inline
Definition at line 93 of file AddPdf.h.
References HYDRA_ENDL, HYDRA_LOG, HYDRA_MSG, and hydra::WARNING.
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf (AddPdf< PDF1, PDF2, PDFs... > const & other) inline
Definition at line 121 of file AddPdf.h.
References hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoeficient().
Member Function Documentation
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ const Parameter& hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoeficient (size_t i) const inline
Definition at line 176 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::AddPdf(), and hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoefSum () const inline
Definition at line 194 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ const thrust::tuple<PDF1,PDF2,PDFs...>& hydra::AddPdf< PDF1, PDF2, PDFs >::GetPdFs () const inline
Definition at line 188 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ GBool_t hydra::AddPdf< PDF1, PDF2, PDFs >::IsExtended () const inline
Definition at line 182 of file AddPdf.h.
Referenced by hydra::AddPdf< PDF1, PDF2, PDFs >::operator=().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ GBool_t hydra::AddPdf< PDF1, PDF2, PDFs >::IsFractioned () const inline
Definition at line 200 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> template<typename T1 > __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::operator() (T1 && t) inline
Definition at line 207 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> template<typename T1 , typename T2 > __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::operator() (T1 && t, T2 && cache) inline
Definition at line 223 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> template<typename T > __host__ __device__ GReal_t hydra::AddPdf< PDF1, PDF2, PDFs >::operator() (T * x, T * p) inline
Definition at line 239 of file AddPdf.h.
template<typename PDF1, typename PDF2, typename... PDFs> __host__ __device__ AddPdf<PDF1, PDF2, PDFs...>& hydra::AddPdf< PDF1, PDF2, PDFs >::operator= (AddPdf< PDF1, PDF2, PDFs... > const & other) inline
Definition at line 134 of file AddPdf.h.
References hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoeficient(), hydra::AddPdf< PDF1, PDF2, PDFs >::GetCoefSum(), hydra::AddPdf< PDF1, PDF2, PDFs >::GetPdFs(), and hydra::AddPdf< PDF1, PDF2, PDFs >::IsExtended().
template<typename PDF1, typename PDF2, typename... PDFs> __host__ void hydra::AddPdf< PDF1, PDF2, PDFs >::PrintRegisteredParameters () inline
Definition at line 164 of file AddPdf.h.
References HYDRA_CALLER, HYDRA_ENDL, and HYDRA_MSG.
template<typename PDF1, typename PDF2, typename... PDFs> __host__ void hydra::AddPdf< PDF1, PDF2, PDFs >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 148 of file AddPdf.h.
Member Data Documentation
template<typename PDF1, typename PDF2, typename... PDFs> constexpr size_t hydra::AddPdf< PDF1, PDF2, PDFs >::npdfs = sizeof...(PDFs)+2 static
Definition at line 72 of file AddPdf.h.
The documentation for this struct was generated from the following file:
AddPdf.h