Hydra: hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > Class Template Reference
hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > Class Template Reference
Public Member Functions
LogLikelihoodFCN (FUNCTOR &functor, IteratorData begin, IteratorData end)
LogLikelihoodFCN (FUNCTOR &functor, IteratorData begin, IteratorData end, IteratorCache cend)
LogLikelihoodFCN (LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > const &other)
LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > & operator= (LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > const &other)
template<typename U = FUNCTOR>
thrust::detail::enable_if< detail::is_hydra_pdf< U >::value, GReal_t >::type Eval (const std::vector< double > &parameters) const
template<typename U = FUNCTOR>
thrust::detail::enable_if< detail::is_hydra_sum_pdf< U >::value, GReal_t >::type Eval (const std::vector< double > &parameters) const
FUNCTOR & GetFunctor () const
GReal_t GetMAxValue () const
Public Member Functions inherited from hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >
FCN (IteratorData begin, IteratorData end)
FCN (IteratorData begin, IteratorData end, IteratorCache cbegin)
FCN (FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache > const &other)
FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache > & operator= (FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache > const &other)
virtual GReal_t Up () const
Up function from Minuit2.
virtual GReal_t operator() (const std::vector< double > &parameters) const
GReal_t operator()(const std::vector<double>&) const.
GBool_t isCached () const
void SetCached (GBool_t cached)
const IteratorCache & GetCacheBegin () const
const IteratorCache & GetCacheEnd () const
const IteratorData & GetDataBegin () const
const IteratorData & GetDataEnd () const
GReal_t GetErrorDef () const
void SetErrorDef (GReal_t errorDef)
GBool_t isWeighted () const
void SetWeighted (GBool_t weighted)
GLong_t GetNEvents () const
GReal_t GetSumW () const
void SetSumW (GReal_t sumW)
GReal_t GetSumW2 () const
void SetSumW2 (GReal_t sumW2)
std::unordered_map< size_t, GReal_t > & GetFcnCache () const
Detailed Description
template<typename FUNCTOR, typename IteratorData, typename IteratorCache>
class hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >
Definition at line 59 of file LogLikelihoodFCN.h.
Constructor & Destructor Documentation
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::LogLikelihoodFCN (FUNCTOR & functor, IteratorData begin, IteratorData end) inline
Definition at line 65 of file LogLikelihoodFCN.h.
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::LogLikelihoodFCN (FUNCTOR & functor, IteratorData begin, IteratorData end, IteratorCache cend) inline
Definition at line 71 of file LogLikelihoodFCN.h.
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::LogLikelihoodFCN (LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > const & other) inline
Definition at line 77 of file LogLikelihoodFCN.h.
Member Function Documentation
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> template<typename U = FUNCTOR> thrust::detail::enable_if< detail::is_hydra_pdf<U>::value, GReal_t>::type hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::Eval (const std::vector< double > & parameters) const inline
Definition at line 98 of file LogLikelihoodFCN.h.
References hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetCacheBegin(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetDataBegin(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetNEvents(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetSumW(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetSumW2(), HYDRA_LOG, hydra::INFO, hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::isCached(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::isWeighted(), and hydra::Print::Level().
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> template<typename U = FUNCTOR> thrust::detail::enable_if< detail::is_hydra_sum_pdf<U>::value, GReal_t>::type hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::Eval (const std::vector< double > & parameters) const inline
Definition at line 140 of file LogLikelihoodFCN.h.
References hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetCacheBegin(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetDataBegin(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetNEvents(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetSumW(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::GetSumW2(), HYDRA_LOG, hydra::INFO, hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::isCached(), hydra::FCN< LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >, IteratorData, IteratorCache >::isWeighted(), and hydra::Print::Level().
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> FUNCTOR& hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::GetFunctor () const inline
Definition at line 192 of file LogLikelihoodFCN.h.
Referenced by hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::operator=().
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> GReal_t hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::GetMAxValue () const inline
Definition at line 196 of file LogLikelihoodFCN.h.
Referenced by hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::operator=().
template<typename FUNCTOR, typename IteratorData, typename IteratorCache> LogLikelihoodFCN<FUNCTOR,IteratorData, IteratorCache>& hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::operator= (LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache > const & other) inline
Definition at line 84 of file LogLikelihoodFCN.h.
References hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::GetFunctor(), and hydra::LogLikelihoodFCN< FUNCTOR, IteratorData, IteratorCache >::GetMAxValue().
The documentation for this class was generated from the following file:
LogLikelihoodFCN.h