Hydra: hydra::DecayMother< N, BACKEND, GRND > Struct Template Reference
hydra::DecayMother< N, BACKEND, GRND > Struct Template Reference
Public Types
typedef detail::BackendTraits< BACKEND > system_t
typedef system_t::template container< GReal_t > vector_real
Public Member Functions
DecayMother (Vector4R const &mother, vector_real const &_masses, const GInt_t _ndaughters, const GInt_t _seed)
__host__ __device__ DecayMother (DecayMother< N, BACKEND, GRND > const &other)
__host__ __device__ GReal_t pdk (const GReal_t a, const GReal_t b, const GReal_t c) const
__host__ __device__ void bbsort (GReal_t *array, GInt_t n)
__host__ __device__ size_t hash (size_t a, size_t b)
__host__ __device__ GReal_t process (const GInt_t evt, Vector4R **daugters)
template<typename Tuple >
__host__ __device__ GReal_t operator() (const GInt_t evt, Tuple &particles)
Public Attributes
const GInt_t fSeed
const GInt_t fNDaughters
GReal_t fTeCmTm
GReal_t fWtMax
GReal_t fBeta0
GReal_t fBeta1
GReal_t fBeta2
GReal_t fMasses [N]
Detailed Description
template<size_t N, unsigned int BACKEND, typename GRND>
struct hydra::DecayMother< N, BACKEND, GRND >
Definition at line 55 of file DecayMother.h.
Member Typedef Documentation
template<size_t N, unsigned int BACKEND, typename GRND> typedef detail::BackendTraits<BACKEND> hydra::DecayMother< N, BACKEND, GRND >::system_t
Definition at line 57 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> typedef system_t::template container<GReal_t> hydra::DecayMother< N, BACKEND, GRND >::vector_real
Definition at line 58 of file DecayMother.h.
Constructor & Destructor Documentation
template<size_t N, unsigned int BACKEND, typename GRND> hydra::DecayMother< N, BACKEND, GRND >::DecayMother (Vector4R const & mother, vector_real const & _masses, const GInt_t _ndaughters, const GInt_t _seed) inline
Definition at line 73 of file DecayMother.h.
References hydra::Vector4R::d3mag(), hydra::Vector4R::get(), and hydra::Vector4R::mass().
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ hydra::DecayMother< N, BACKEND, GRND >::DecayMother (DecayMother< N, BACKEND, GRND > const & other) inline
Definition at line 121 of file DecayMother.h.
References hydra::DecayMother< N, BACKEND, GRND >::fMasses.
Member Function Documentation
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ void hydra::DecayMother< N, BACKEND, GRND >::bbsort (GReal_t * array, GInt_t n) inline
Definition at line 144 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ size_t hydra::DecayMother< N, BACKEND, GRND >::hash (size_t a, size_t b) inline
Definition at line 170 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> template<typename Tuple > __host__ __device__ GReal_t hydra::DecayMother< N, BACKEND, GRND >::operator() (const GInt_t evt, Tuple & particles) inline
Definition at line 297 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ GReal_t hydra::DecayMother< N, BACKEND, GRND >::pdk (const GReal_t a, const GReal_t b, const GReal_t c) const inline
Definition at line 134 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> __host__ __device__ GReal_t hydra::DecayMother< N, BACKEND, GRND >::process (const GInt_t evt, Vector4R ** daugters) inline
Definition at line 182 of file DecayMother.h.
References hydra::Vector4R::applyBoostTo(), hydra::Vector4R::get(), kMAXP, PI, hydra::Vector4R::set(), and hydra::sum().
Member Data Documentation
template<size_t N, unsigned int BACKEND, typename GRND> GReal_t hydra::DecayMother< N, BACKEND, GRND >::fBeta0
Definition at line 64 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> GReal_t hydra::DecayMother< N, BACKEND, GRND >::fBeta1
Definition at line 65 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> GReal_t hydra::DecayMother< N, BACKEND, GRND >::fBeta2
Definition at line 66 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> GReal_t hydra::DecayMother< N, BACKEND, GRND >::fMasses[N]
Definition at line 70 of file DecayMother.h.
Referenced by hydra::DecayMother< N, BACKEND, GRND >::DecayMother().
template<size_t N, unsigned int BACKEND, typename GRND> const GInt_t hydra::DecayMother< N, BACKEND, GRND >::fNDaughters
Definition at line 61 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> const GInt_t hydra::DecayMother< N, BACKEND, GRND >::fSeed
Definition at line 60 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> GReal_t hydra::DecayMother< N, BACKEND, GRND >::fTeCmTm
Definition at line 62 of file DecayMother.h.
template<size_t N, unsigned int BACKEND, typename GRND> GReal_t hydra::DecayMother< N, BACKEND, GRND >::fWtMax
Definition at line 63 of file DecayMother.h.
The documentation for this struct was generated from the following file:
DecayMother.h