Hydra: hydra::Point< T, N, HasValueError, HasPointError > Struct Template Reference
hydra::Point< T, N, HasValueError, HasPointError > Struct Template Reference
Public Types
typedef detail::tuple_type< N, T >::type type
typedef T value_type
Public Types inherited from hydra::ValueError< T, HasValueError >
typedef ValueError< T, true > type
typedef T value_type
Public Types inherited from hydra::PointError< T, N, HasPointError >
typedef detail::tuple_type< N, T >::type type
typedef T value_type
Public Member Functions
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (const typename std::enable_if< !U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ Point (std::array< value_type, N > coordinates, value_type weight, const typename std::enable_if< !U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ Point (std::initializer_list< value_type > coordinates, value_type weight, const typename std::enable_if< !U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (type coordinates, value_type weight=1.0, const typename std::enable_if< !U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (value_type *coordinates, value_type weight, const typename std::enable_if< !U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (const typename std::enable_if< U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ Point (std::array< value_type, N > coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ Point (std::initializer_list< value_type > coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (type coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (value_type *coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (const typename std::enable_if< U &&V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ Point (std::array< value_type, N > coordinates, std::array< value_type, N > coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ Point (std::initializer_list< value_type > coordinates, std::initializer_list< value_type > coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (type coordinates, type coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type *dummy=0)
template<bool U = HasValueError, bool V = HasPointError>
__host__ __device__ Point (value_type *coordinates, value_type *coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type *dummy=0)
__host__ __device__ Point (Point< value_type, N, HasValueError, HasPointError > const &other)
__host__ __device__ value_type GetCoordinate (const int i) const
__host__ __device__ type & GetCoordinates ()
__host__ __device__ type const & GetCoordinates () const
__host__ __device__ value_type GetWeight ()
__host__ __device__ const value_type GetWeight () const
__host__ __device__ value_type GetWeight2 ()
__host__ __device__ value_type GetWeight2 () const
__host__ __device__ Point< value_type, N, HasValueError, HasPointError > & operator= (type const &value)
__host__ __device__ Point< value_type, N, HasValueError, HasPointError > & operator= (value_type value)
__host__ __device__ void SetCoordinates (type coordinates)
__host__ __device__ void SetWeight (value_type weight)
__host__ __device__ void SetWeight2 (value_type weight2)
Static Public Attributes
static const size_t Dimension =N
Detailed Description
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false>
struct hydra::Point< T, N, HasValueError, HasPointError >
Definition at line 180 of file Point.h.
Member Typedef Documentation
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> typedef detail::tuple_type<N, T>::type hydra::Point< T, N, HasValueError, HasPointError >::type
Definition at line 183 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> typedef T hydra::Point< T, N, HasValueError, HasPointError >::value_type
Definition at line 184 of file Point.h.
Constructor & Destructor Documentation
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (const typename std::enable_if< !U &&!V, void >::type * dummy = 0) inline
Definition at line 193 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ hydra::Point< T, N, HasValueError, HasPointError >::Point (std::array< value_type, N > coordinates, value_type weight, const typename std::enable_if< !U &&!V, void >::type * dummy = 0) inline
Definition at line 212 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ hydra::Point< T, N, HasValueError, HasPointError >::Point (std::initializer_list< value_type > coordinates, value_type weight, const typename std::enable_if< !U &&!V, void >::type * dummy = 0) inline
Definition at line 221 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (type coordinates, value_type weight = 1.0, const typename std::enable_if< !U &&!V, void >::type * dummy = 0) inline
Definition at line 232 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (value_type * coordinates, value_type weight, const typename std::enable_if< !U &&!V, void >::type * dummy = 0) inline explicit
Definition at line 241 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (const typename std::enable_if< U &&!V, void >::type * dummy = 0) inline
Definition at line 256 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ hydra::Point< T, N, HasValueError, HasPointError >::Point (std::array< value_type, N > coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type * dummy = 0) inline
Definition at line 276 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ hydra::Point< T, N, HasValueError, HasPointError >::Point (std::initializer_list< value_type > coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type * dummy = 0) inline
Definition at line 286 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (type coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type * dummy = 0) inline
Definition at line 298 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (value_type * coordinates, const value_type weight, value_type error, const typename std::enable_if< U &&!V, void >::type * dummy = 0) inline explicit
Definition at line 308 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (const typename std::enable_if< U &&V, void >::type * dummy = 0) inline
Definition at line 322 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ hydra::Point< T, N, HasValueError, HasPointError >::Point (std::array< value_type, N > coordinates, std::array< value_type, N > coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type * dummy = 0) inline
Definition at line 344 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ hydra::Point< T, N, HasValueError, HasPointError >::Point (std::initializer_list< value_type > coordinates, std::initializer_list< value_type > coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type * dummy = 0) inline
Definition at line 355 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (type coordinates, type coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type * dummy = 0) inline
Definition at line 368 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> template<bool U = HasValueError, bool V = HasPointError> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (value_type * coordinates, value_type * coordinates_errors, value_type weight, value_type error, const typename std::enable_if< U &&V, void >::type * dummy = 0) inline explicit
Definition at line 379 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ hydra::Point< T, N, HasValueError, HasPointError >::Point (Point< value_type, N, HasValueError, HasPointError > const & other) inline
Definition at line 390 of file Point.h.
Member Function Documentation
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ value_type hydra::Point< T, N, HasValueError, HasPointError >::GetCoordinate (const int i) const inline
Definition at line 442 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ type& hydra::Point< T, N, HasValueError, HasPointError >::GetCoordinates () inline
Definition at line 432 of file Point.h.
Referenced by hydra::operator+().
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ type const& hydra::Point< T, N, HasValueError, HasPointError >::GetCoordinates () const inline
Definition at line 437 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ value_type hydra::Point< T, N, HasValueError, HasPointError >::GetWeight () inline
Definition at line 453 of file Point.h.
Referenced by hydra::operator+().
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ const value_type hydra::Point< T, N, HasValueError, HasPointError >::GetWeight () const inline
Definition at line 458 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ value_type hydra::Point< T, N, HasValueError, HasPointError >::GetWeight2 () inline
Definition at line 468 of file Point.h.
Referenced by hydra::operator+().
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ value_type hydra::Point< T, N, HasValueError, HasPointError >::GetWeight2 () const inline
Definition at line 473 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ Point<value_type,N,HasValueError,HasPointError>& hydra::Point< T, N, HasValueError, HasPointError >::operator= (type const & value) inline
Definition at line 399 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ Point<value_type,N,HasValueError,HasPointError>& hydra::Point< T, N, HasValueError, HasPointError >::operator= (value_type value) inline
Definition at line 415 of file Point.h.
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ void hydra::Point< T, N, HasValueError, HasPointError >::SetCoordinates (type coordinates) inline
Definition at line 447 of file Point.h.
Referenced by hydra::operator+().
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ void hydra::Point< T, N, HasValueError, HasPointError >::SetWeight (value_type weight) inline
Definition at line 463 of file Point.h.
Referenced by hydra::operator+().
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> __host__ __device__ void hydra::Point< T, N, HasValueError, HasPointError >::SetWeight2 (value_type weight2) inline
Definition at line 478 of file Point.h.
Referenced by hydra::operator+().
Member Data Documentation
template<typename T, size_t N = 1, bool HasValueError = false, bool HasPointError = false> const size_t hydra::Point< T, N, HasValueError, HasPointError >::Dimension =N static
Definition at line 185 of file Point.h.
Referenced by hydra::operator<<().
The documentation for this struct was generated from the following file:
Point.h