var namespacehydra =
[
    [ "detail", "d2/d1d/namespacehydra_1_1detail.html", "d2/d1d/namespacehydra_1_1detail" ],
    [ "AddPdf", "dd/d31/structhydra_1_1_add_pdf.html", "dd/d31/structhydra_1_1_add_pdf" ],
    [ "Argument", "df/d6b/structhydra_1_1_argument.html", "df/d6b/structhydra_1_1_argument" ],
    [ "BaseFunctor", "d6/d84/structhydra_1_1_base_functor.html", "d6/d84/structhydra_1_1_base_functor" ],
    [ "Compose", "d8/d22/structhydra_1_1_compose.html", "d8/d22/structhydra_1_1_compose" ],
    [ "Constant", "d0/df9/structhydra_1_1_constant.html", "d0/df9/structhydra_1_1_constant" ],
    [ "DecayMother", "df/d0c/structhydra_1_1_decay_mother.html", "df/d0c/structhydra_1_1_decay_mother" ],
    [ "DecayMothers", "d7/d5d/structhydra_1_1_decay_mothers.html", "d7/d5d/structhydra_1_1_decay_mothers" ],
    [ "Divide", "d1/dfa/structhydra_1_1_divide.html", "d1/dfa/structhydra_1_1_divide" ],
    [ "EvalReturnType", "d1/da0/structhydra_1_1_eval_return_type.html", "d1/da0/structhydra_1_1_eval_return_type" ],
    [ "Events", "d5/d79/structhydra_1_1_events.html", "d5/d79/structhydra_1_1_events" ],
    [ "FCN", "db/dd9/classhydra_1_1_f_c_n.html", "db/dd9/classhydra_1_1_f_c_n" ],
    [ "FlagAcceptReject", "d2/db9/structhydra_1_1_flag_accept_reject.html", "d2/db9/structhydra_1_1_flag_accept_reject" ],
    [ "HyRndBreitWigner", "d4/dc3/structhydra_1_1_hy_rnd_breit_wigner.html", "d4/dc3/structhydra_1_1_hy_rnd_breit_wigner" ],
    [ "HyRndCDF", "d1/dd0/structhydra_1_1_hy_rnd_c_d_f.html", "d1/dd0/structhydra_1_1_hy_rnd_c_d_f" ],
    [ "HyRndExp", "d1/dc7/structhydra_1_1_hy_rnd_exp.html", "d1/dc7/structhydra_1_1_hy_rnd_exp" ],
    [ "HyRndFlag", "d5/dab/structhydra_1_1_hy_rnd_flag.html", "d5/dab/structhydra_1_1_hy_rnd_flag" ],
    [ "HyRndGauss", "d9/d27/structhydra_1_1_hy_rnd_gauss.html", "d9/d27/structhydra_1_1_hy_rnd_gauss" ],
    [ "HyRndTrial", "d0/de3/structhydra_1_1_hy_rnd_trial.html", "d0/de3/structhydra_1_1_hy_rnd_trial" ],
    [ "HyRndUniform", "d4/d7b/structhydra_1_1_hy_rnd_uniform.html", "d4/d7b/structhydra_1_1_hy_rnd_uniform" ],
    [ "Integrator", "da/d6c/structhydra_1_1_integrator.html", "da/d6c/structhydra_1_1_integrator" ],
    [ "isAccepted", "d1/dc8/structhydra_1_1is_accepted.html", "d1/dc8/structhydra_1_1is_accepted" ],
    [ "LambdaWrapper", "d9/dfc/structhydra_1_1_lambda_wrapper.html", null ],
    [ "LambdaWrapper< ReturnType(ArgType), L >", "dd/d3b/structhydra_1_1_lambda_wrapper_3_01_return_type_07_arg_type_08_00_01_l_01_4.html", "dd/d3b/structhydra_1_1_lambda_wrapper_3_01_return_type_07_arg_type_08_00_01_l_01_4" ],
    [ "LogLikelihood", "d2/d23/structhydra_1_1_log_likelihood.html", "d2/d23/structhydra_1_1_log_likelihood" ],
    [ "LogLikelihoodFCN", "d3/dc2/classhydra_1_1_log_likelihood_f_c_n.html", "d3/dc2/classhydra_1_1_log_likelihood_f_c_n" ],
    [ "Minus", "d5/d2e/structhydra_1_1_minus.html", "d5/d2e/structhydra_1_1_minus" ],
    [ "Multiply", "d6/db9/structhydra_1_1_multiply.html", "d6/db9/structhydra_1_1_multiply" ],
    [ "null_type", "d3/d2d/structhydra_1_1null__type.html", null ],
    [ "Parameter", "db/d64/structhydra_1_1_parameter.html", "db/d64/structhydra_1_1_parameter" ],
    [ "Pdf", "db/d0a/structhydra_1_1_pdf.html", "db/d0a/structhydra_1_1_pdf" ],
    [ "PhaseSpace", "df/d7a/classhydra_1_1_phase_space.html", "df/d7a/classhydra_1_1_phase_space" ],
    [ "Plain", "d4/dbb/classhydra_1_1_plain.html", "d4/dbb/classhydra_1_1_plain" ],
    [ "PlainState", "d5/da8/structhydra_1_1_plain_state.html", "d5/da8/structhydra_1_1_plain_state" ],
    [ "Point", "db/dd4/structhydra_1_1_point.html", "db/dd4/structhydra_1_1_point" ],
    [ "PointError", "d7/d11/structhydra_1_1_point_error.html", "d7/d11/structhydra_1_1_point_error" ],
    [ "PointError< T, N, true >", "de/d31/structhydra_1_1_point_error_3_01_t_00_01_n_00_01true_01_4.html", "de/d31/structhydra_1_1_point_error_3_01_t_00_01_n_00_01true_01_4" ],
    [ "PointVector", "d7/d3b/classhydra_1_1_point_vector.html", "d7/d3b/classhydra_1_1_point_vector" ],
    [ "Print", "d5/d83/classhydra_1_1_print.html", null ],
    [ "ProcessBoxesVegas", "dc/d69/structhydra_1_1_process_boxes_vegas.html", "dc/d69/structhydra_1_1_process_boxes_vegas" ],
    [ "ProcessCallsPlainBinary", "de/de8/structhydra_1_1_process_calls_plain_binary.html", "de/de8/structhydra_1_1_process_calls_plain_binary" ],
    [ "ProcessCallsPlainUnary", "de/df5/structhydra_1_1_process_calls_plain_unary.html", "de/df5/structhydra_1_1_process_calls_plain_unary" ],
    [ "ProcessCallsVegas", "da/dfa/structhydra_1_1_process_calls_vegas.html", "da/dfa/structhydra_1_1_process_calls_vegas" ],
    [ "Random", "d2/d3f/classhydra_1_1_random.html", "d2/d3f/classhydra_1_1_random" ],
    [ "Range", "de/de3/structhydra_1_1_range.html", "de/de3/structhydra_1_1_range" ],
    [ "ResultVegas", "db/d74/structhydra_1_1_result_vegas.html", "db/d74/structhydra_1_1_result_vegas" ],
    [ "Sum", "d4/d03/structhydra_1_1_sum.html", "d4/d03/structhydra_1_1_sum" ],
    [ "UserParameters", "db/de3/classhydra_1_1_user_parameters.html", "db/de3/classhydra_1_1_user_parameters" ],
    [ "ValueError", "d1/dd8/structhydra_1_1_value_error.html", "d1/dd8/structhydra_1_1_value_error" ],
    [ "ValueError< T, true >", "d5/d1a/structhydra_1_1_value_error_3_01_t_00_01true_01_4.html", "d5/d1a/structhydra_1_1_value_error_3_01_t_00_01true_01_4" ],
    [ "Vector3R", "de/d99/classhydra_1_1_vector3_r.html", "de/d99/classhydra_1_1_vector3_r" ],
    [ "Vector4R", "da/d49/classhydra_1_1_vector4_r.html", "da/d49/classhydra_1_1_vector4_r" ],
    [ "Vegas", "df/d9b/classhydra_1_1_vegas.html", "df/d9b/classhydra_1_1_vegas" ],
    [ "VegasState", "d9/d4f/classhydra_1_1_vegas_state.html", "d9/d4f/classhydra_1_1_vegas_state" ]
];