Hydra: hydra::UserParameters Class Reference
hydra::UserParameters Class Reference
Public Member Functions
UserParameters ()
UserParameters (UserParameters const &other)
UserParameters & operator= (UserParameters const &other)
void AddParameter (hydra::Parameter *param)
void UpdateParameters (ROOT::Minuit2::FunctionMinimum const &minimum)
void UpdateParameterLimits (ROOT::Minuit2::MinosError const &minos_error)
void PrintParameters ()
void PrintMinuitParameters ()
const std::vector< hydra::Parameter * > & GetVariables () const
void SetVariables (const std::vector< hydra::Parameter * > &variables)
const ROOT::Minuit2::MnUserParameters & GetState () const
ROOT::Minuit2::MnUserParameters & GetState ()
const std::unique_ptr< ROOT::Minuit2::MnUserParameters > & GetStatePtr () const
void SetState (ROOT::Minuit2::MnUserParameters const &state)
Detailed Description
Definition at line 52 of file UserParameters.h.
Constructor & Destructor Documentation
hydra::UserParameters::UserParameters () inline
Definition at line 57 of file UserParameters.h.
hydra::UserParameters::UserParameters (UserParameters const & other) inline
Definition at line 62 of file UserParameters.h.
Member Function Documentation
void hydra::UserParameters::AddParameter (hydra::Parameter * param) inline
Definition at line 80 of file UserParameters.h.
References hydra::Parameter::GetError(), hydra::Parameter::GetLowerLim(), hydra::Parameter::GetName(), hydra::Parameter::GetUpperLim(), hydra::Parameter::GetValue(), hydra::Parameter::HasError(), hydra::Parameter::IsLimited(), and hydra::Parameter::SetIndex().
Referenced by main().
const ROOT::Minuit2::MnUserParameters& hydra::UserParameters::GetState () const inline
Definition at line 161 of file UserParameters.h.
Referenced by main(), hydra::operator<<(), and PrintMinuitParameters().
ROOT::Minuit2::MnUserParameters& hydra::UserParameters::GetState () inline
Definition at line 166 of file UserParameters.h.
const std::unique_ptr<ROOT::Minuit2::MnUserParameters>& hydra::UserParameters::GetStatePtr () const inline
Definition at line 171 of file UserParameters.h.
Referenced by operator=().
const std::vector<hydra::Parameter* >& hydra::UserParameters::GetVariables () const inline
Definition at line 153 of file UserParameters.h.
Referenced by operator=().
UserParameters& hydra::UserParameters::operator= (UserParameters const & other) inline
Definition at line 67 of file UserParameters.h.
References GetStatePtr(), and GetVariables().
void hydra::UserParameters::PrintMinuitParameters () inline
Definition at line 148 of file UserParameters.h.
References GetState().
void hydra::UserParameters::PrintParameters () inline
Definition at line 130 of file UserParameters.h.
References HYDRA_CALLER, HYDRA_ENDL, and HYDRA_MSG.
Referenced by main().
void hydra::UserParameters::SetState (ROOT::Minuit2::MnUserParameters const & state) inline
Definition at line 176 of file UserParameters.h.
void hydra::UserParameters::SetVariables (const std::vector< hydra::Parameter * > & variables) inline
Definition at line 157 of file UserParameters.h.
void hydra::UserParameters::UpdateParameterLimits (ROOT::Minuit2::MinosError const & minos_error) inline
Definition at line 113 of file UserParameters.h.
References HYDRA_LOG, and hydra::WARNING.
void hydra::UserParameters::UpdateParameters (ROOT::Minuit2::FunctionMinimum const & minimum) inline
Definition at line 102 of file UserParameters.h.
The documentation for this class was generated from the following file:
UserParameters.h