Hydra: HydraFitExample.cpp File Reference
HydraFitExample.cpp File Reference
HydraFitExample take parameters from the command line, fill a range with random numbers sampled from the model and perform a extended likelihood fit in parallel using the OpenMP backend.
Functions
GInt_t main (int argv, char **argc)
Detailed Description
Parameters
-c (–combined-minimizer) : Use Migrad + Simplex for minimization
-i=<double> (–max-iterations=<double>): Maximum number of iterations for migrad and minimize call.
-t=<double> (–tolerance=<double>): Tolerance parameter for migrad and minimize call.
-n=<long> (–number-of-events=<long>) (required): Number of events for each component.
Usage: ./Hydra_Example_GCC_DEVICE_OMP_HOST_CPP_Fit [-c] [-i=<double>] [-t=<double>] -n=<long> [–] [–version] [-h]
For example, the command below:
./Hydra_Example_GCC_DEVICE_OMP_HOST_CPP_Fit -n=1000000
will print some stuff to standard output and produce the plot:
Definition in file HydraFitExample.cpp.
Function Documentation
GInt_t main (int argv, char ** argc)
Examples:
HydraFitExample.cpp.
Definition at line 135 of file HydraFitExample.cpp.
References hydra::add_pdfs(), hydra::UserParameters::AddParameter(), hydra::PointVector< BACKEND, T, N, V_ERROR, C_ERROR >::begin(), hydra::PointVector< BACKEND, T, N, V_ERROR, C_ERROR >::end(), hydra::Parameter::Error(), hydra::Random< GRND >::Gauss(), hydra::Vegas< N, GRND >::GetAbsError(), hydra::VegasState< N >::GetChiSquare(), hydra::Vegas< N, GRND >::GetResult(), hydra::UserParameters::GetState(), hydra::Vegas< N, GRND >::Integrate(), hydra::Parameter::Limits(), hydra::make_loglikehood_fcn(), hydra::make_pdf(), hydra::Parameter::Name(), hydra::UserParameters::PrintParameters(), hydra::Random< GRND >::Sample(), hydra::VegasState< N >::SetAlpha(), hydra::VegasState< N >::SetIterations(), hydra::VegasState< N >::SetMaxError(), hydra::Random< GRND >::SetSeed(), hydra::VegasState< N >::SetUseRelativeError(), hydra::VegasState< N >::SetVerbose(), hydra::Random< GRND >::Uniform(), and hydra::Parameter::Value().