Hydra: hydra::Events< N, BACKEND > Struct Template Reference
hydra::Events< N, BACKEND > Struct Template Reference
Events is a container struct to hold all the information corresponding the generated events.
Public Types
typedef detail::BackendTraits< BACKEND > system_t
typedef iterator::value_type value_type
typedef system_t::template container< GBool_t > vector_bool
typedef system_t::template container< GBool_t >::const_iterator vector_bool_const_iterator
typedef system_t::template container< GBool_t >::iterator vector_bool_iterator
typedef system_t::template container< Vector4R > vector_particles
typedef system_t::template container< Vector4R >::const_iterator vector_particles_const_iterator
typedef system_t::template container< Vector4R >::iterator vector_particles_iterator
typedef system_t::template container< GReal_t > vector_real
typedef system_t::template container< GReal_t >::const_iterator vector_real_const_iterator
typedef system_t::template container< GReal_t >::iterator vector_real_iterator
Public Member Functions
Events ()
Constructor takes as parameters the number of particles and number of events.
Events (GLong_t nevents)
template<unsigned int BACKEND2>
Events (Events< N, BACKEND2 > const &other)
~Events ()
iterator begin ()
vector_particles_const_iterator DaughtersBegin (GInt_t i) const
vector_particles_iterator DaughtersBegin (GInt_t i)
vector_particles_const_iterator DaughtersEnd (GInt_t i) const
vector_particles_iterator DaughtersEnd (GInt_t i)
iterator end ()
vector_bool_const_iterator FlagsBegin () const
vector_bool_iterator FlagsBegin ()
vector_bool_const_iterator FlagsEnd () const
vector_bool_iterator FlagsEnd ()
GReal_t GetMaxWeight () const
GLong_t GetNEvents () const
template<unsigned int BACKEND2>
Events< N, BACKEND > & operator= (Events< N, BACKEND2 > const &other)
value_type operator[] (size_t i)
void SetMaxWeight (GReal_t maxWeight)
void SetNEvents (GLong_t nEvents)
GULong_t Unweight (size_t seed)
vector_real_const_iterator WeightsBegin () const
vector_real_iterator WeightsBegin ()
vector_real_const_iterator WeightsEnd () const
vector_real_iterator WeightsEnd ()
Public Attributes
decltype(detail::get_zip_iterator(vector_real_iterator(), std::array< vector_particles_iterator, N >())) typedef iterator
Detailed Description
template<size_t N, unsigned int BACKEND>
struct hydra::Events< N, BACKEND >
Mother four-vectors are not stored.
Examples:
HydraPhaseSpaceExample.cpp, and HydraPhaseSpaceExample.cu.
Definition at line 68 of file Events.h.
Member Typedef Documentation
template<size_t N, unsigned int BACKEND> typedef detail::BackendTraits<BACKEND> hydra::Events< N, BACKEND >::system_t
Definition at line 70 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef iterator::value_type hydra::Events< N, BACKEND >::value_type
Definition at line 85 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<GBool_t> hydra::Events< N, BACKEND >::vector_bool
Definition at line 80 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<GBool_t>::const_iterator hydra::Events< N, BACKEND >::vector_bool_const_iterator
Definition at line 82 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<GBool_t>::iterator hydra::Events< N, BACKEND >::vector_bool_iterator
Definition at line 81 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<Vector4R> hydra::Events< N, BACKEND >::vector_particles
Definition at line 72 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<Vector4R>::const_iterator hydra::Events< N, BACKEND >::vector_particles_const_iterator
Definition at line 74 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<Vector4R>::iterator hydra::Events< N, BACKEND >::vector_particles_iterator
Definition at line 73 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<GReal_t> hydra::Events< N, BACKEND >::vector_real
Definition at line 76 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<GReal_t>::const_iterator hydra::Events< N, BACKEND >::vector_real_const_iterator
Definition at line 78 of file Events.h.
template<size_t N, unsigned int BACKEND> typedef system_t::template container<GReal_t>::iterator hydra::Events< N, BACKEND >::vector_real_iterator
Definition at line 77 of file Events.h.
Constructor & Destructor Documentation
template<size_t N, unsigned int BACKEND> hydra::Events< N, BACKEND >::Events () inline
Definition at line 90 of file Events.h.
template<size_t N, unsigned int BACKEND> hydra::Events< N, BACKEND >::Events (GLong_t nevents) inline
Definition at line 95 of file Events.h.
template<size_t N, unsigned int BACKEND> template<unsigned int BACKEND2> hydra::Events< N, BACKEND >::Events (Events< N, BACKEND2 > const & other) inline
Definition at line 123 of file Events.h.
References hydra::Events< N, BACKEND >::DaughtersBegin(), hydra::Events< N, BACKEND >::DaughtersEnd(), hydra::Events< N, BACKEND >::FlagsBegin(), hydra::Events< N, BACKEND >::FlagsEnd(), hydra::Events< N, BACKEND >::WeightsBegin(), and hydra::Events< N, BACKEND >::WeightsEnd().
template<size_t N, unsigned int BACKEND> hydra::Events< N, BACKEND >::~Events () inline
Definition at line 199 of file Events.h.
Member Function Documentation
template<size_t N, unsigned int BACKEND> iterator hydra::Events< N, BACKEND >::begin () inline
Definition at line 278 of file Events.h.
template<size_t N, unsigned int BACKEND> vector_particles_const_iterator hydra::Events< N, BACKEND >::DaughtersBegin (GInt_t i) const inline
Definition at line 229 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Events(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> vector_particles_iterator hydra::Events< N, BACKEND >::DaughtersBegin (GInt_t i) inline
Definition at line 255 of file Events.h.
template<size_t N, unsigned int BACKEND> vector_particles_const_iterator hydra::Events< N, BACKEND >::DaughtersEnd (GInt_t i) const inline
Definition at line 234 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Events(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> vector_particles_iterator hydra::Events< N, BACKEND >::DaughtersEnd (GInt_t i) inline
Definition at line 260 of file Events.h.
template<size_t N, unsigned int BACKEND> iterator hydra::Events< N, BACKEND >::end () inline
Definition at line 280 of file Events.h.
template<size_t N, unsigned int BACKEND> vector_bool_const_iterator hydra::Events< N, BACKEND >::FlagsBegin () const inline
Definition at line 213 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Events(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> vector_bool_iterator hydra::Events< N, BACKEND >::FlagsBegin () inline
Definition at line 239 of file Events.h.
template<size_t N, unsigned int BACKEND> vector_bool_const_iterator hydra::Events< N, BACKEND >::FlagsEnd () const inline
Definition at line 217 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Events(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> vector_bool_iterator hydra::Events< N, BACKEND >::FlagsEnd () inline
Definition at line 243 of file Events.h.
template<size_t N, unsigned int BACKEND> GReal_t hydra::Events< N, BACKEND >::GetMaxWeight () const inline
Definition at line 201 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> GLong_t hydra::Events< N, BACKEND >::GetNEvents () const inline
Definition at line 205 of file Events.h.
Referenced by hydra::PhaseSpace< N, GRND >::Generate(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> template<unsigned int BACKEND2> Events<N,BACKEND>& hydra::Events< N, BACKEND >::operator= (Events< N, BACKEND2 > const & other) inline
Definition at line 160 of file Events.h.
References hydra::Events< N, BACKEND >::DaughtersBegin(), hydra::Events< N, BACKEND >::DaughtersEnd(), hydra::Events< N, BACKEND >::FlagsBegin(), hydra::Events< N, BACKEND >::FlagsEnd(), hydra::Events< N, BACKEND >::GetMaxWeight(), hydra::Events< N, BACKEND >::GetNEvents(), hydra::Events< N, BACKEND >::WeightsBegin(), and hydra::Events< N, BACKEND >::WeightsEnd().
template<size_t N, unsigned int BACKEND> value_type hydra::Events< N, BACKEND >::operator[] (size_t i) inline
Definition at line 271 of file Events.h.
template<size_t N, unsigned int BACKEND> void hydra::Events< N, BACKEND >::SetMaxWeight (GReal_t maxWeight) inline
Definition at line 265 of file Events.h.
template<size_t N, unsigned int BACKEND> void hydra::Events< N, BACKEND >::SetNEvents (GLong_t nEvents) inline
Definition at line 209 of file Events.h.
template<size_t N, unsigned int BACKEND> GULong_t hydra::Events< N, BACKEND >::Unweight (size_t seed) inline
Flag the accepted and rejected events
Definition at line 282 of file Events.h.
References hydra::Events< N, BACKEND >::iterator, and hydra::kTrue.
template<size_t N, unsigned int BACKEND> vector_real_const_iterator hydra::Events< N, BACKEND >::WeightsBegin () const inline
Definition at line 221 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Events(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> vector_real_iterator hydra::Events< N, BACKEND >::WeightsBegin () inline
Definition at line 247 of file Events.h.
template<size_t N, unsigned int BACKEND> vector_real_const_iterator hydra::Events< N, BACKEND >::WeightsEnd () const inline
Definition at line 225 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Events(), and hydra::Events< N, BACKEND >::operator=().
template<size_t N, unsigned int BACKEND> vector_real_iterator hydra::Events< N, BACKEND >::WeightsEnd () inline
Definition at line 251 of file Events.h.
Member Data Documentation
template<size_t N, unsigned int BACKEND> decltype(detail::get_zip_iterator(vector_real_iterator(), std::array< vector_particles_iterator,N>())) typedef hydra::Events< N, BACKEND >::iterator
Definition at line 84 of file Events.h.
Referenced by hydra::Events< N, BACKEND >::Unweight().
The documentation for this struct was generated from the following file:
Events.h