Hydra: hydra::Pdf< FUNCTOR, INTEGRATOR > Struct Template Reference
hydra::Pdf< FUNCTOR, INTEGRATOR > Struct Template Reference
Public Types
typedef void hydra_pdf_tag
typedef detail::PdfBase< FUNCTOR, INTEGRATOR >::type base_type
Public Member Functions
template<typename U = FUNCTOR>
__host__ __device__ Pdf (U const &functor, INTEGRATOR *integrator)
__host__ __device__ Pdf (Pdf< FUNCTOR, INTEGRATOR > const &other)
__host__ __device__ ~Pdf ()
__host__ __device__ Pdf< FUNCTOR, INTEGRATOR > & operator= (Pdf< FUNCTOR, INTEGRATOR > const &other)
__host__ void PrintRegisteredParameters ()
__host__ void SetParameters (const std::vector< double > &parameters)
__host__ void UpdateNorm (const std::vector< double > &parameters) const
__host__ __device__ INTEGRATOR * GetIntegrator () const
__host__ void SetIntegrator (INTEGRATOR *integrator)
__host__ __device__ FUNCTOR GetFunctor () const
__host__ __device__ void SetFunctor (FUNCTOR functor)
__host__ __device__ GReal_t GetNorm () const
__host__ __device__ void SetNorm (GReal_t norm)
template<typename T1 >
__host__ __device__ GReal_t operator() (T1 &&t)
template<typename T1 , typename T2 >
__host__ __device__ GReal_t operator() (T1 &&t, T2 &&cache)
template<typename T >
__host__ __device__ GReal_t operator() (T *x, T *p)
Detailed Description
template<typename FUNCTOR, typename INTEGRATOR>
struct hydra::Pdf< FUNCTOR, INTEGRATOR >
Definition at line 59 of file Pdf.h.
Member Typedef Documentation
template<typename FUNCTOR, typename INTEGRATOR> typedef detail::PdfBase<FUNCTOR, INTEGRATOR>::type hydra::Pdf< FUNCTOR, INTEGRATOR >::base_type
Definition at line 67 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> typedef void hydra::Pdf< FUNCTOR, INTEGRATOR >::hydra_pdf_tag
Definition at line 62 of file Pdf.h.
Constructor & Destructor Documentation
template<typename FUNCTOR, typename INTEGRATOR> template<typename U = FUNCTOR> __host__ __device__ hydra::Pdf< FUNCTOR, INTEGRATOR >::Pdf (U const & functor, INTEGRATOR * integrator) inline
Definition at line 73 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ hydra::Pdf< FUNCTOR, INTEGRATOR >::Pdf (Pdf< FUNCTOR, INTEGRATOR > const & other) inline
Definition at line 90 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ hydra::Pdf< FUNCTOR, INTEGRATOR >::~Pdf () inline
Definition at line 104 of file Pdf.h.
Member Function Documentation
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ FUNCTOR hydra::Pdf< FUNCTOR, INTEGRATOR >::GetFunctor () const inline
Definition at line 178 of file Pdf.h.
Referenced by hydra::Pdf< FUNCTOR, INTEGRATOR >::operator=().
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ INTEGRATOR* hydra::Pdf< FUNCTOR, INTEGRATOR >::GetIntegrator () const inline
Definition at line 169 of file Pdf.h.
Referenced by hydra::Pdf< FUNCTOR, INTEGRATOR >::operator=().
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ GReal_t hydra::Pdf< FUNCTOR, INTEGRATOR >::GetNorm () const inline
Definition at line 186 of file Pdf.h.
Referenced by hydra::Pdf< FUNCTOR, INTEGRATOR >::operator=().
template<typename FUNCTOR, typename INTEGRATOR> template<typename T1 > __host__ __device__ GReal_t hydra::Pdf< FUNCTOR, INTEGRATOR >::operator() (T1 && t) inline
Definition at line 196 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> template<typename T1 , typename T2 > __host__ __device__ GReal_t hydra::Pdf< FUNCTOR, INTEGRATOR >::operator() (T1 && t, T2 && cache) inline
Definition at line 204 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> template<typename T > __host__ __device__ GReal_t hydra::Pdf< FUNCTOR, INTEGRATOR >::operator() (T * x, T * p) inline
Definition at line 212 of file Pdf.h.
References HYDRA_LOG, and hydra::INFO.
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ Pdf<FUNCTOR,INTEGRATOR>& hydra::Pdf< FUNCTOR, INTEGRATOR >::operator= (Pdf< FUNCTOR, INTEGRATOR > const & other) inline
Definition at line 108 of file Pdf.h.
References hydra::Pdf< FUNCTOR, INTEGRATOR >::GetFunctor(), hydra::Pdf< FUNCTOR, INTEGRATOR >::GetIntegrator(), and hydra::Pdf< FUNCTOR, INTEGRATOR >::GetNorm().
template<typename FUNCTOR, typename INTEGRATOR> __host__ void hydra::Pdf< FUNCTOR, INTEGRATOR >::PrintRegisteredParameters () inline
Definition at line 135 of file Pdf.h.
References HYDRA_CALLER, HYDRA_ENDL, and HYDRA_MSG.
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ void hydra::Pdf< FUNCTOR, INTEGRATOR >::SetFunctor (FUNCTOR functor) inline
Definition at line 182 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> __host__ void hydra::Pdf< FUNCTOR, INTEGRATOR >::SetIntegrator (INTEGRATOR * integrator) inline
Definition at line 174 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> __host__ __device__ void hydra::Pdf< FUNCTOR, INTEGRATOR >::SetNorm (GReal_t norm) inline
Definition at line 190 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> __host__ void hydra::Pdf< FUNCTOR, INTEGRATOR >::SetParameters (const std::vector< double > & parameters) inline
Definition at line 145 of file Pdf.h.
template<typename FUNCTOR, typename INTEGRATOR> __host__ void hydra::Pdf< FUNCTOR, INTEGRATOR >::UpdateNorm (const std::vector< double > & parameters) const inline
Definition at line 155 of file Pdf.h.
References HYDRA_LOG, hydra::INFO, and hydra::Print::Level().
The documentation for this struct was generated from the following file:
Pdf.h