Hydra: hydra::Parameter Struct Reference
hydra::Parameter Struct Reference
Public Member Functions
__host__ __device__ Parameter ()
Parameter (std::string const &name, GReal_t value, GReal_t error, GReal_t downlim, GReal_t uplim)
Parameter (std::string const &name, GReal_t value, GReal_t error)
Parameter (std::string const &name, GReal_t value)
__host__ __device__ Parameter (Parameter const &other)
__host__ Parameter & Error (GReal_t error)
__host__ __device__ GReal_t GetError () const
__host__ __device__ unsigned int GetIndex () const
__host__ __device__ GReal_t GetLowerLim () const
__host__ __device__ const GChar_t * GetName () const
__host__ __device__ GReal_t GetUpperLim () const
__host__ __device__ GReal_t GetValue () const
__host__ __device__ GBool_t HasError () const
__host__ __device__ GBool_t IsLimited () const
__host__ Parameter & Limits (GReal_t lowlim, GReal_t uplim)
__host__ Parameter & Name (std::string const &name)
__host__ __device__ operator GReal_t ()
__host__ __device__ GReal_t operator() ()
__host__ __device__ Parameter & operator*= (const GReal_t value)
__host__ __device__ Parameter & operator*= (Parameter const &other)
__host__ __device__ Parameter & operator+= (const GReal_t value)
__host__ __device__ Parameter & operator+= (Parameter const &other)
__host__ __device__ Parameter & operator-= (const GReal_t value)
__host__ __device__ Parameter & operator-= (Parameter const &other)
__host__ __device__ Parameter & operator/= (const GReal_t value)
__host__ __device__ Parameter & operator/= (Parameter const &other)
__host__ __device__ Parameter & operator= (Parameter const &other)
__host__ __device__ Parameter & operator= (const GReal_t value)
__host__ void Reset (const std::vector< double > &parameters)
__host__ __device__ void SetError (GReal_t error)
__host__ __device__ void SetHasError (GBool_t nullError)
__host__ __device__ void SetIndex (unsigned int index)
__host__ __device__ void SetLimited (GBool_t limited)
__host__ __device__ void SetLimits (GReal_t lower, GReal_t upper)
__host__ __device__ void SetLowerLim (GReal_t downLim)
__host__ void SetName (const std::string &name)
__host__ __device__ void SetUpperLim (GReal_t upLim)
__host__ __device__ void SetValue (GReal_t value)
__host__ Parameter & Value (GReal_t value)
Static Public Member Functions
static __host__ Parameter Create ()
Detailed Description
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 52 of file Parameter.h.
Constructor & Destructor Documentation
__host__ __device__ hydra::Parameter::Parameter () inline
Definition at line 55 of file Parameter.h.
Referenced by Create().
hydra::Parameter::Parameter (std::string const & name, GReal_t value, GReal_t error, GReal_t downlim, GReal_t uplim) inline
Definition at line 67 of file Parameter.h.
hydra::Parameter::Parameter (std::string const & name, GReal_t value, GReal_t error) inline
Definition at line 78 of file Parameter.h.
hydra::Parameter::Parameter (std::string const & name, GReal_t value) inline
Definition at line 90 of file Parameter.h.
__host__ __device__ hydra::Parameter::Parameter (Parameter const & other) inline
Definition at line 105 of file Parameter.h.
References GetName().
Member Function Documentation
static __host__ Parameter hydra::Parameter::Create () inline static
Definition at line 318 of file Parameter.h.
References Parameter().
__host__ Parameter& hydra::Parameter::Error (GReal_t error) inline
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 329 of file Parameter.h.
Referenced by main().
__host__ __device__ GReal_t hydra::Parameter::GetError () const inline
Definition at line 283 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), hydra::operator<<(), and operator=().
__host__ __device__ unsigned int hydra::Parameter::GetIndex () const inline
Definition at line 227 of file Parameter.h.
Referenced by hydra::operator<<(), operator=(), and hydra::BaseFunctor< LambdaWrapper< ReturnType(ArgType), L >, ReturnType, 0 >::SetParameters().
__host__ __device__ GReal_t hydra::Parameter::GetLowerLim () const inline
Definition at line 216 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), hydra::operator<<(), and operator=().
__host__ __device__ const GChar_t* hydra::Parameter::GetName () const inline
Definition at line 260 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), hydra::operator<<(), operator=(), and Parameter().
__host__ __device__ GReal_t hydra::Parameter::GetUpperLim () const inline
Definition at line 237 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), hydra::operator<<(), and operator=().
__host__ __device__ GReal_t hydra::Parameter::GetValue () const inline
Definition at line 271 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), operator*=(), operator+=(), operator-=(), operator/=(), hydra::operator<<(), and operator=().
__host__ __device__ GBool_t hydra::Parameter::HasError () const inline
Definition at line 304 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), and operator=().
__host__ __device__ GBool_t hydra::Parameter::IsLimited () const inline
Definition at line 294 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter(), and operator=().
__host__ Parameter& hydra::Parameter::Limits (GReal_t lowlim, GReal_t uplim) inline
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 342 of file Parameter.h.
Referenced by main().
__host__ Parameter& hydra::Parameter::Name (std::string const & name) inline
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 323 of file Parameter.h.
Referenced by main().
__host__ __device__ hydra::Parameter::operator GReal_t () inline
Definition at line 314 of file Parameter.h.
__host__ __device__ GReal_t hydra::Parameter::operator() () inline
Definition at line 211 of file Parameter.h.
__host__ __device__ Parameter& hydra::Parameter::operator*= (const GReal_t value) inline
Definition at line 177 of file Parameter.h.
__host__ __device__ Parameter& hydra::Parameter::operator*= (Parameter const & other) inline
Definition at line 185 of file Parameter.h.
References GetValue().
__host__ __device__ Parameter& hydra::Parameter::operator+= (const GReal_t value) inline
Definition at line 145 of file Parameter.h.
__host__ __device__ Parameter& hydra::Parameter::operator+= (Parameter const & other) inline
Definition at line 153 of file Parameter.h.
References GetValue().
__host__ __device__ Parameter& hydra::Parameter::operator-= (const GReal_t value) inline
Definition at line 161 of file Parameter.h.
__host__ __device__ Parameter& hydra::Parameter::operator-= (Parameter const & other) inline
Definition at line 169 of file Parameter.h.
References GetValue().
__host__ __device__ Parameter& hydra::Parameter::operator/= (const GReal_t value) inline
Definition at line 194 of file Parameter.h.
__host__ __device__ Parameter& hydra::Parameter::operator/= (Parameter const & other) inline
Definition at line 202 of file Parameter.h.
References GetValue().
__host__ __device__ Parameter& hydra::Parameter::operator= (Parameter const & other) inline
Definition at line 121 of file Parameter.h.
References GetError(), GetIndex(), GetLowerLim(), GetName(), GetUpperLim(), GetValue(), HasError(), and IsLimited().
__host__ __device__ Parameter& hydra::Parameter::operator= (const GReal_t value) inline
Definition at line 137 of file Parameter.h.
__host__ void hydra::Parameter::Reset (const std::vector< double > & parameters) inline
Definition at line 276 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetError (GReal_t error) inline
Definition at line 288 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetHasError (GBool_t nullError) inline
Definition at line 309 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetIndex (unsigned int index) inline
Definition at line 232 of file Parameter.h.
Referenced by hydra::UserParameters::AddParameter().
__host__ __device__ void hydra::Parameter::SetLimited (GBool_t limited) inline
Definition at line 299 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetLimits (GReal_t lower, GReal_t upper) inline
Definition at line 242 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetLowerLim (GReal_t downLim) inline
Definition at line 221 of file Parameter.h.
__host__ void hydra::Parameter::SetName (const std::string & name) inline
Definition at line 265 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetUpperLim (GReal_t upLim) inline
Definition at line 249 of file Parameter.h.
__host__ __device__ void hydra::Parameter::SetValue (GReal_t value) inline
Definition at line 255 of file Parameter.h.
__host__ Parameter& hydra::Parameter::Value (GReal_t value) inline
Examples:
HydraFitExample.cpp, and HydraFitExample.cu.
Definition at line 336 of file Parameter.h.
Referenced by main().
The documentation for this struct was generated from the following file:
Parameter.h