Hydra: HydraEvaluateExample.cu File Reference
HydraEvaluateExample.cu File Reference
This is an example of how to use hydra::Eval to evaluate C++11 lambdas using the CUDA backend.
Functions
GInt_t main (int argv, char **argc)
Detailed Description
The usage and the expected output is something like this:
 ./Hydra_Example_NVCC_DEVICE_CUDA_HOST_OMP_Eval -n=10000000
--------------------------------------------------------------
| Evaluation of [sin(x), cos(x)]
| Time (ms) = 0.268075
--------------------------------------------------------------
--------------------------------------------------------------
| Evaluation of [sin(x)^2 + cos(x)^2]
| Time (ms) = 0.213697
--------------------------------------------------------------
|>   0 [sin(x), cos(x)] = (-0.252592278 -0.967572809) ............... [sin(x)^2 + cos(x)^2] = 1
|>   1 [sin(x), cos(x)] = (0.932195527 -0.361955107) ............... [sin(x)^2 + cos(x)^2] = 1
|>   2 [sin(x), cos(x)] = (0.585050502 0.810996862) ............... [sin(x)^2 + cos(x)^2] = 1
|>   3 [sin(x), cos(x)] = (0.851355528 0.524589139) ............... [sin(x)^2 + cos(x)^2] = 1
|>   4 [sin(x), cos(x)] = (0.921620144 0.388093171) ............... [sin(x)^2 + cos(x)^2] = 1
|>   5 [sin(x), cos(x)] = (-0.989926331 0.141583398) ............... [sin(x)^2 + cos(x)^2] = 1
|>   6 [sin(x), cos(x)] = (-0.775938693 -0.630808327) ............... [sin(x)^2 + cos(x)^2] = 1
|>   7 [sin(x), cos(x)] = (0.879555884 0.475795593) ............... [sin(x)^2 + cos(x)^2] = 1
|>   8 [sin(x), cos(x)] = (0.964678017 0.263431819) ............... [sin(x)^2 + cos(x)^2] = 1
|>   9 [sin(x), cos(x)] = (-0.999776981 -0.0211184451) ............... [sin(x)^2 + cos(x)^2] = 1
Definition in file HydraEvaluateExample.cu.
Function Documentation
GInt_t main (int argv, char ** argc)
number of entries or trials
Examples:
HydraEvaluateExample.cu.
Definition at line 115 of file HydraEvaluateExample.cu.
References hydra::Eval(), hydra::make_range(), PI, hydra::Random< GRND >::Uniform(), and hydra::wrap_lambda().