Hydra: HydraPhaseSpaceExample.cu File Reference
HydraPhaseSpaceExample.cu File Reference
HydraPhaseSpaceExample take parameters from the command line and generates sample of 3-body phase-space decays in parallel using the CUDA backend.
Functions
GInt_t main (int argv, char **argc)
Detailed Description
Parameters
-m=<double> invariant mass of the mother particle
-a=<double> invariant mass of the first daughter particle
-b=<double> invariant mass of the second daughter particle
-c=<double> invariant mass of the third daughter particle
-n=<long> number of events to generate.
Usage:
./Hydra_Example_NVCC_DEVICE_CUDA_HOST_OMP_PHSP -c=<double> -b=<double> -a=<double> -m=<double> -n=<long>
For example, the command below:
./Hydra_Example_NVCC_DEVICE_CUDA_HOST_OMP_PHSP  -n=10000000 -m=5.2795 -a=3.096916 -b=0.493677 -c=0.13957018
will print some stuff to standard output and produce the plot:
Definition in file HydraPhaseSpaceExample.cu.
Function Documentation
GInt_t main (int argv, char ** argc)
Create PhaseSpace object for B0-> K pi J/psi
Examples:
HydraPhaseSpaceExample.cu.
Definition at line 115 of file HydraPhaseSpaceExample.cu.
References hydra::Eval(), hydra::make_range(), hydra::Vector4R::mass(), and hydra::wrap_lambda().